version: '3.8'

services:
  frontend:
    # build:
      # context: ./ui
      # dockerfile: Dockerfile
    image: manndshelby/invoice-frontend:prod
    container_name: frontend
    expose:
      - "3000"
    networks:
      - appnet
  backend:
    # build:
      # context: ./backend
      # dockerfile: dockerfile
    image: manndshelby/invoice-backend:prod
    container_name: php-prod
    ports:
      - "8000:8000"
    networks:
      - appnet
    volumes:
      - shared_data:/var/www/html/storage
      
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
volumes:
  shared_data:
    driver: local
    driver_opts:
      type: none
      device: ./storage
      o: bind
  