# FROM php:8.3-cli
# # Install system dependencies
# RUN apt-get update && apt-get install -y \
#     unzip \
#     git \
#     curl
# # Install Composer
# RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# WORKDIR /var/www/html

# COPY . .

# RUN composer install 
# RUN composer dump-autoload 
# EXPOSE 8000
# CMD ["php", "-S", "0.0.0.0:8000", "-t", "public", "router.php"]

# Use a PHP base image
FROM php:8.3-cli

# Install system dependencies required by zip and gd
RUN apt-get update && apt-get install -y \
    libzip-dev \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    zip \
    unzip \
    git \
    && docker-php-ext-configure zip \
    && docker-php-ext-install zip \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install gd

# Copy project files
WORKDIR /var/www/html
COPY . .

# Install composer dependencies
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN composer install
RUN apt install libreoffice -y 
# Expose port and command (adjust if needed)
EXPOSE 8000
CMD ["php", "-S", "0.0.0.0:8000", "-t", "public","router.php"]
