/* eslint-disable */
// @ts-nocheck
// GENERATED by scripts/split-generator.mjs from ui/src/lib/excelGenerator.ts.
// The body below is a verbatim copy. Do not edit or reformat it by hand —
// re-run `npm run docs:split` instead. The original was written with
// TypeScript strictness disabled, so it is excluded from type checking;
// correctness is established by scripts/compare-generators.mts, which diffs
// every cell against the original generator.

import ExcelJS from 'exceljs'
import { format } from 'date-fns'
import { convertNamesToInitials, formatNames, round3 } from './helpers'
import type { LegacyInvoiceData, LoadedImage } from './types'

void ExcelJS
void format
void round3
void convertNamesToInitials
void formatNames

export interface DocumentContext extends Record<string, any> {}

/** Derived values shared by all seven sheets — the original's prelude. */
export const buildContext = async (
  data: LegacyInvoiceData,
  images: { header?: LoadedImage; footer?: LoadedImage; signature?: LoadedImage }
): Promise<DocumentContext> => {
    void images

    // Exporter Details
    let companyName = data.exporter.company_name || "";
    let companyAddress = data.exporter.company_address || "";
    let email = data.exporter.email || "";
    let taxid = data.exporter.tax_id || "";
    let ieCode = data.exporter.ie_code || "";
    let panNo = data.exporter.pan_number || "";
    let gstinNo = data.exporter.gstin_number || "";
    let stateCode = data.exporter.state_code || "";
    let invoiceNo = data.invoice_number || "";
    let invoiceDate = data.invoice_date || "";
    // invoiceDate = normalizeDateSeparator(invoiceDate, '.');
    // let [year, month, day] = invoiceDate.split('/');
    // invoiceDate = `${month}/${year}/${day}`;
    let buyersOrderNo = data.buyer.order_number || "";
    let buyersOrderDate = data.buyer.order_date || "";
    // [year, month, day] = buyersOrderDate.split('-');
    // buyersOrderDate = `${day}/${month}/${year}`;
    let poNo = data.buyer.po_number === "-" ? "" : data.buyer.po_number;
    let consignee = data.buyer.consignee || "";
    let notifyParty = data.buyer.notify_party || "";
    let formattedNotifyParty = convertNamesToInitials(notifyParty);

    let preCarriage = data.shipping.pre_carriage === "-" ? "" : data.shipping.pre_carriage;
    let vassalFlightNo = data.shipping.vessel_flight_no === "-" ? "" : data.shipping.vessel_flight_no;
    let placeOfReceipt = data.shipping.place_of_receipt || "";
    let portOfLoading = data.shipping.port_of_loading || "";
    let portOfDischarge = data.shipping.port_of_discharge || "";
    let finalDestination = data.shipping.final_destination || "";
    let countryOfOrigin = data.shipping.country_of_origin || "";
    let origin = data.shipping.origin_details || "";
    // let termsOfDelivery = data.payment_term || "FOB";
    let termsOfDeliveryMain = data.payment_term || "";
    let termsOfDelivery: String;
    if (termsOfDeliveryMain == "CIF -> FOB") {
        termsOfDelivery = "CIF";
    } else {
        termsOfDelivery = termsOfDeliveryMain;
    }
    let termsOfDeliveryMainAt = data.shipping.terms_of_delivery || "";
    let paymentTerms = data.shipping.payment || "";
    let shippingMethod = data.shipping.shipping_method || "";
    let currency = data.currancy_type || "";
    let currencyRate = data.currancy_rate || "";
    let containerType = data.product_details.nos || "";
    let marksAndNos = data.product_details.marks || "";

    // product_name, size, quantity, unit, sqm_box, total_sqm, price, amount , net_weight, gross_weight

    const reverseTransformProducts = (data: any[]) => { // mann patel
        const result: any[] = [];

        data.forEach((category) => {
            // Add the category as the first element
            result.push([category.category_name, category.hsn_code]);

            // Add all products under the category
            category.products.forEach((product: any) => {
                result.push([
                    product.product_name,
                    product.size,
                    product.quantity,
                    product.unit,
                    product.sqm,
                    product.total_sqm,
                    product.price,
                    product.total_price,
                    product.net_weight,
                    product.gross_weight,
                ]);
            });
        });

        return result;
    };

    let products = reverseTransformProducts(data.product_details.product_section);
    // const products = [
    //   ['Glazed porcelain Floor Tiles ', 482931],
    //   ['Ceramica White', '600X1200', 1000, 'BOX', 1.44, 1440, 10.0, 14400.0, 32522.00, 65465.00],
    //   ['Stone Grey', '600X1200', 1000, 'BOX', 1.44, 1440, 10.0, 14400.0, 32522.00, 65465.00],
    //   ['Marble Mist', '600X1200', 1000, 'BOX', 1.44, 1440, 10.0, 14400.0, 32522.00, 65465.00],
    //   ['Ocean Blue', '600X600', 1000, 'BOX', 1.44, 1440, 10.0, 14400.0, 32522.00, 65465.00],
    //   ['Sunset Beige', '600X600', 1000, 'BOX', 1.44, 1440, 10.0, 14400.0, 32522.00, 65465.00],
    //   ['Granite Spark', '600X600', 1000, 'BOX', 1.44, 1440, 10.0, 14400.0, 32522.00, 65465.00],
    //   ['Lava Black', '600X600', 1000, 'BOX', 1.44, 1440, 10.0, 14400.0, 32522.00, 65465.00],
    //   ['Glazed Ceramic Wall tiles', 294762],
    //   ['Ivory Pearl', '600X1200', 1000, 'BOX', 1.44, 1440, 10.0, 14400.0, 32522.00, 65465.00],
    //   ['Alpine Frost', '600X1200', 1000, 'BOX', 1.44, 1440, 10.0, 14400.0, 32522.00, 65465.00],
    //   ['Sahara Sand', '600X1200', 1000, 'BOX', 1.44, 1440, 10.0, 14400.0, 32522.00, 65465.00],
    //   ['Cement Ash', '600X600', 1000, 'BOX', 1.44, 1440, 10.0, 14400.0, 32522.00, 65465.00],
    //   ['Coral Blush', '600X600', 1000, 'BOX', 1.44, 1440, 10.0, 14400.0, 32522.00, 65465.00],
    //   ['Shadow Brown', '600X600', 1000, 'BOX', 1.44, 1440, 10.0, 14400.0, 32522.00, 65465.00],
    // ];
    let packageInfo = data.package.number_of_package || "";
    let [totalPackages, unitOfIt] = packageInfo.split(' ');

    let noOfPackages = totalPackages;
    console.log(data.package.number_of_package);
    console.log(data.annexure.gross_weight);
    let grossWeight = Number(data.annexure.gross_weight) || "";
    let netWeight = Number(data.annexure.net_weight) || "";
    let totalSQM = data.package.total_sqm || "";
    let insurance = data.product_details.insurance || "";
    let freight = data.product_details.freight || "";
    let fOBEuro = data.package.total_amount - insurance - freight;
    let totalFOBEuro = data.package.total_amount;
    if (termsOfDeliveryMain === "CIF -> FOB") {
        fOBEuro = data.package.total_amount;
        totalFOBEuro = data.package.total_amount - insurance - freight;
    }
    let amountInWords = data.package.amount_in_words || "";
    let gstCirculerNumber = data.package.gst_circular || "";
    // let customDate = data.invoice_date || "26-04-2025";
    let arn = data.package.app_ref_number || "";
    let lutDate = data.package.lut_date || "";
    // [year, month, day] = lutDate.split('-');
    // lutDate = `${day}/${month}/${year}`;
    let totalInINR = data.package.taxable_value || "";

    let gstValue = data.package.gst_amount || "";   // New value // mann patel
    function formatSupplierDetails(suppliers) { // mann Patel
        return suppliers.map(supplier => {
            // Convert GSTIN to numeric-only (if required)
            const numericGstin = supplier.gstin_number;

            // Format date from 'yyyy-mm-dd' to 'dd.mm.yyyy'
            let [year, month, day] = supplier.date.split('-');
            let formattedDate = `${day}/${month}/${year}`;

            return [
                supplier.supplier_name,
                numericGstin,
                supplier.tax_invoice_no,
                formattedDate  // Use formatted date or fallback to original
            ];
        });
    }
    let supplierDetails = formatSupplierDetails(data.suppliers || []); // mann patel

    // const supplierDetails = [
    //   ['abc', 3254626216, 'asf/235', '12.02.2025'],
    //   ['def', 3254263511, 'aag/235', '16.02.2025'],
    //   ['ghi', 3252626216, 'dhf/235', '12.12.2025'],
    //   ['jkl', 3246526216, 'hdt/235', '12.06.2025'],
    //   ['mno', 3254632526, 'rth/235', '16.02.2025'],
    //   ['pqr', 3254632526, 'rth/235', '16.02.2025'],
    //   ['xyz', 3254632526, 'rth/235', '16.02.2025'],
    // ];

    // Packing List
    const convertArrayToFormat = (
        data: Array<{ [key: string]: any }>,
        containerSize: string, // Static value for container size
        additionalData: Array<{ booking_no: string; tare_weight: number }> // Array for booking_no and tare_weight
    ): Array<any> => {
        return data.map((item, idx) => [
            item.container_number || '',
            item.line_seal_number || '',
            item.rfid_number || '',
            item.design_no || '',
            item.quantity_box || 0,
            item.net_weight || 0.0,
            item.gross_weight || 0.0,
            containerSize, // Static value for container size
            additionalData[idx]?.booking_no || '', // Booking number from additional data
            additionalData[idx]?.tare_weight || 0, // Tare weight from additional data
        ]);
    };

    // zala your work
    // container_no , line_seal_no , rfid_seal , description , quantity , container.net_weight , container.gross_weight , annexure.container_size , vgn.booking_no , vgn.tare_weight
    // let containerDetails = [
    //   ['EWRUJ4875265', "T 234567884", 'SFSS 1233 2133', 'TILES', 1000, 32522.00, 65465.00, '1 X 20\'', 'SFY35789526', 2342],
    //   ['EWRUJ4875265', "T 234567884", 'SFSS 1233 2133', 'TILES', 1000, 32522.00, 65465.00, '1 X 20\'', 'SFY35789526', 2342],
    //   ['EWRUJ4875265', "T 234567884", 'SFSS 1233 2133', 'TILES', 1000, 32522.00, 65465.00, '1 X 20\'', 'SFY35789526', 2342],
    //   ['EWRUJ4875265', "T 234567884", 'SFSS 1233 2133', 'TILES', 1000, 32522.00, 65465.00, '1 X 20\'', 'SFY35789526', 2342],
    //   ['EWRUJ4875265', "T 234567884", 'SFSS 1233 2133', 'TILES', 1000, 32522.00, 65465.00, '1 X 20\'', 'SFY35789526', 2342],
    //   ['EWRUJ4875265', "T 234567884", 'SFSS 1233 2133', 'TILES', 1000, 32522.00, 65465.00, '1 X 20\'', 'SFY35789526', 2342],
    //   ['EWRUJ4875265', "T 234567884", 'SFSS 1233 2133', 'TILES', 1000, 32522.00, 65465.00, '1 X 20\'', 'SFY35789526', 2342], 
    // ];


    let containerDetails = convertArrayToFormat(data.product_details.containers, data.product_details.marks, data.vgm.containers);
    let totalPallet = data.product_details.total_pallet_count || "";

    // Annexure
    let range = data.annexure.range || "";
    let division = data.annexure.division || "";
    let commissionerate = data.annexure.commissionerate || "";
    let branchCodeNo = data.annexure.branch_no === "-" ? "" : data.annexure.branch_no;
    let binNo = data.annexure.bin_no === "-" ? "" : data.annexure.bin_no;
    let manufacturer = data.annexure.manufacturer_name || "";
    let manufacturerAddress = data.annexure.manufacturer_address || "";
    let manufacturerGST = data.annexure.manufacturer_gstin_no || "";
    let ann5 = data.annexure.officer_designation1 || "";
    let ann6 = data.annexure.officer_designation2 || "";
    let ann9a = data.annexure.question9a || "";
    let ann9b = data.annexure.question9b || "";
    let ann9c = data.annexure.question9c || "";
    let ann10a = data.annexure.non_containerized || "";
    let ann10b = data.annexure.containerized || "";
    let locationCode = data.annexure.location_code || "";
    let ssPermissionNo = data.annexure.manufacturer_permission || "";
    // let issuedBy = "*******************************************************************************************";
    let selfSealingCircularNo = "59/2010" // new values
    let selfSealingCircularNoDate = "23.12.2010" // new values

    //vgn
    let nameOfOfficial = data.vgm.authorized_name || "";
    let numberOfOfficial = data.vgm.authorized_contact || "";
    let vgn5 = data.vgm.container_number || "";
    let containerSize = data.vgm.container_size || "";
    let vgn7 = data.vgm.permissible_weight || "";
    let vgn8 = data.vgm.weighbridge_registration || "";
    let vgn9 = data.vgm.verified_gross_mass || "";
    let unitOfMeasure = data.vgm.unit_of_measurement || "";
    let vgn12 = data.vgm.weighing_slip_no || "";
    let vgn13 = data.vgm.type || "";
    let vgn14 = data.vgm.IMDG_class || "";


    // let packegingType = unitOfIt;  // Ignore it for now
    let packegingType = products[1][3];  // Ignore it for now
    for (let i = 2; i < products.length; i++) {
        if (products[i].length !== 2) {
            if (!(packegingType.includes(products[i][3]))) {
                packegingType += "/" + products[i][3];
            }
        }
    }

    // let type = "sanitary";
    let typeMain = data.product_type.toLowerCase() || "sanitary"; // Default to "sanitary" if not provided
    let taxStatus = data.integrated_tax.toLowerCase() || "with";

    console.log("typeMain", typeMain, "totalSQM", totalSQM);
    if (typeMain === "mix" && (totalSQM === "NaN" || totalSQM === "" || totalSQM === 0)) { // true
        typeMain = "sanitary";
    } else if (typeMain === "mix") {
        typeMain = "tiles";
    }
    let type: String;

    if (typeMain === "tiles") {
        type = "sanitary"; // 7 column
    } else {
        type = "tiles"; // 4 column
    }
    console.log("type", type);




const headerUrl = data.exporter?.header;

const footerUrl = data.exporter?.footer;

const signatureUrl = data.exporter?.signature;

const configurePrintSheet = (sheet: ExcelJS.Worksheet) => {
        sheet.pageSetup = {
            paperSize: 9,            // A4
            orientation: 'portrait',
            fitToPage: true,
            fitToWidth: 1,           // Fit width to one page
            fitToHeight: 0,          // Allow height to flow onto multiple pages
            horizontalCentered: true,
            margins: {
                left: 0.2,
                right: 0.2,
                top: 0.4,
                bottom: 0.4,
                header: 0.2,
                footer: 0.2,
            },
        };
    };

const setGlobalFontSize = (
        worksheet: ExcelJS.Worksheet,
        fontSize: number = 10
    ) => {
        worksheet.eachRow((row) => {
            row.eachCell((cell) => {
                const currentFont = cell.font || {};

                // ✅ Only apply size if it's not already defined
                if (!currentFont.size) {
                    cell.font = {
                        ...currentFont,
                        size: fontSize,
                    };
                }
            });
        });
    };

const pixelToExcelWidth = (px) => {
        return Math.round(((px - 5) / 7) * 100) / 100;
    };

const columnWidths = [
        47 - 2,  // A (index 1)
        16,  // B
        33,  // C
        33,  // D
        33 - 2,  // E
        33 - 2,  // F
        33 - 2,  // G
        33 - 2,  // H
        72 - 2,  // I
        18 - 2,  // J
        42 - 2,  // K
        34 - 2,  // L
        43 - 2,  // M
        43 - 2,  // N
        43 - 2,  // O
        64 - 2,  // P
        3 - 2,   // Q
        126 - 2, // R
        38,  // S
        38,  // T
        39 - 2,  // U
        71 - 2,  // V
        35 - 2,  // W
        35 - 2,  // X
        75 - 2,  // Y
        85 - 2,  // Z
        84 - 2,  // AA (index 27)
    ];

const setOuterBorder = (range: string, sheet: ExcelJS.Worksheet, thickness: ExcelJS.BorderStyle = 'thin') => {
        const [startRef, endRef] = range.split(':');

        const colToNum = (col: string): number =>
            col.split('').reduce((r, c) => r * 26 + c.charCodeAt(0) - 64, 0);

        const getRowCol = (ref: string) => {
            const match = ref.match(/^([A-Z]+)(\d+)$/);
            if (!match) throw new Error(`Invalid ref ${ref}`);
            const [, colLetters, rowStr] = match;
            return { row: +rowStr, col: colToNum(colLetters) };
        };

        const { row: startRow, col: startCol } = getRowCol(startRef);
        const { row: endRow, col: endCol } = getRowCol(endRef);

        for (let row = startRow; row <= endRow; row++) {
            for (let col = startCol; col <= endCol; col++) {
                const cell = sheet.getCell(row, col);
                cell.border = {
                    top: row === startRow ? { style: thickness } : cell.border?.top,
                    bottom: row === endRow ? { style: thickness } : cell.border?.bottom,
                    left: col === startCol ? { style: thickness } : cell.border?.left,
                    right: col === endCol ? { style: thickness } : cell.border?.right,
                };

                // 🔧 Extra fix for Column A (first column)
                if (col === 1) {
                    cell.border.left = { style: thickness };
                }
            }
        }
    };

    return {
        companyName,
        companyAddress,
        email,
        taxid,
        ieCode,
        panNo,
        gstinNo,
        stateCode,
        invoiceNo,
        invoiceDate,
        buyersOrderNo,
        buyersOrderDate,
        poNo,
        consignee,
        notifyParty,
        formattedNotifyParty,
        preCarriage,
        vassalFlightNo,
        placeOfReceipt,
        portOfLoading,
        portOfDischarge,
        finalDestination,
        countryOfOrigin,
        origin,
        termsOfDeliveryMain,
        termsOfDelivery,
        termsOfDeliveryMainAt,
        paymentTerms,
        shippingMethod,
        currency,
        currencyRate,
        containerType,
        marksAndNos,
        reverseTransformProducts,
        products,
        packageInfo,
        noOfPackages,
        grossWeight,
        netWeight,
        totalSQM,
        insurance,
        freight,
        fOBEuro,
        totalFOBEuro,
        amountInWords,
        gstCirculerNumber,
        arn,
        lutDate,
        totalInINR,
        gstValue,
        supplierDetails,
        convertArrayToFormat,
        containerDetails,
        totalPallet,
        range,
        division,
        commissionerate,
        branchCodeNo,
        binNo,
        manufacturer,
        manufacturerAddress,
        manufacturerGST,
        ann5,
        ann6,
        ann9a,
        ann9b,
        ann9c,
        ann10a,
        ann10b,
        locationCode,
        ssPermissionNo,
        selfSealingCircularNo,
        selfSealingCircularNoDate,
        nameOfOfficial,
        numberOfOfficial,
        vgn5,
        containerSize,
        vgn7,
        vgn8,
        vgn9,
        unitOfMeasure,
        vgn12,
        vgn13,
        vgn14,
        packegingType,
        typeMain,
        taxStatus,
        type,
        totalPackages,
        unitOfIt,
        headerUrl,
        footerUrl,
        signatureUrl,
        configurePrintSheet,
        setGlobalFontSize,
        pixelToExcelWidth,
        columnWidths,
        setOuterBorder,
    }
}
