/* eslint-disable */
// @ts-nocheck
// GENERATED by scripts/split-generator.mjs from ui/src/lib/excelGenerator.ts.
// The body below is a verbatim copy. Do not edit or reformat it by hand —
// re-run `npm run docs:split` instead. The original was written with
// TypeScript strictness disabled, so it is excluded from type checking;
// correctness is established by scripts/compare-generators.mts, which diffs
// every cell against the original generator.
// Source lines 4848-5492.

import ExcelJS from 'exceljs'
import { format } from 'date-fns'
import { convertNamesToInitials, formatNames, round3 } from '../helpers'
import { loadImageBuffer } from '../loadImageBuffer'
import type { DocumentContext } from '../context'
import type { SheetState } from '../state'

void ExcelJS
void format
void round3
void convertNamesToInitials
void formatNames
void loadImageBuffer

export const buildAnnexure = async (
  ctx: DocumentContext,
  state: SheetState,
  built: Record<string, any> = {}
): Promise<{ workbook: any; sheet: any; state: SheetState; built: Record<string, any> }> => {
    void built
    const {
        companyName,
        taxid,
        ieCode,
        panNo,
        gstinNo,
        stateCode,
        invoiceNo,
        invoiceDate,
        consignee,
        finalDestination,
        termsOfDelivery,
        noOfPackages,
        grossWeight,
        netWeight,
        gstCirculerNumber,
        arn,
        lutDate,
        totalInINR,
        gstValue,
        containerDetails,
        range,
        division,
        commissionerate,
        branchCodeNo,
        binNo,
        manufacturer,
        manufacturerAddress,
        manufacturerGST,
        ann5,
        ann6,
        ann9a,
        ann9b,
        ann9c,
        ann10a,
        ann10b,
        locationCode,
        ssPermissionNo,
        selfSealingCircularNo,
        selfSealingCircularNoDate,
        packegingType,
        taxStatus,
        type,
        signatureUrl,
        configurePrintSheet,
        setGlobalFontSize,
        pixelToExcelWidth,
        setOuterBorder
    } = ctx
    let { row, allProductsType, MAX_WIDTH } = state
    let signature: any, vgnSignatureW: any, vgnSignatureH: any

    const annexureWorkbook = new ExcelJS.Workbook();
    const annexure = annexureWorkbook.addWorksheet('ANNEXURE');
    configurePrintSheet(annexure);

    if (signatureUrl) {

        const { buffer, extension, width, height } = await loadImageBuffer(signatureUrl);
        signature = annexureWorkbook.addImage({
            buffer: buffer,
            extension: extension,
        });
        vgnSignatureW = width;
        vgnSignatureH = height;

    }

    annexure.mergeCells('A1:AA1');
    annexure.getCell('A1').value = "ANNEXURE";
    annexure.getCell('A1').font = { bold: true };
    annexure.getCell('A1').alignment = { horizontal: 'center' };

    annexure.mergeCells('A2:AA2');
    annexure.getCell('A2').value = "OFFICE OF THE SUPERITENTNDENT OF GST";
    annexure.getCell('A2').font = { bold: true };
    annexure.getCell('A2').alignment = { horizontal: 'center' };

    annexure.mergeCells('A3:G3');
    annexure.getCell('A3').value = `RANGE: ${range}`;
    annexure.getCell('A3').alignment = { horizontal: 'left' };

    annexure.mergeCells('H3:P3');
    annexure.getCell('H3').value = `DIVISION: ${division}`;
    annexure.getCell('H3').alignment = { horizontal: 'left' };

    annexure.mergeCells('Q3:AA3');
    annexure.getCell('Q3').value = `COMMISSIONERATE: ${commissionerate}`;
    annexure.getCell('Q3').alignment = { horizontal: 'left' };

    annexure.mergeCells('A4:AA4');
    annexure.getCell('A4').value = "EXAMINATION REPORT FOR FACTORY SEALED CONTAINER";
    annexure.getCell('A4').font = { bold: true };
    annexure.getCell('A4').alignment = { horizontal: 'center' };
    setOuterBorder('A1:AA4', annexure);

    annexure.mergeCells('A5:A6');
    annexure.getCell('A5').value = 1;
    // annexure.getCell('A5').font = { bold: true };
    annexure.getCell('A5').alignment = { horizontal: 'right', vertical: 'top' };

    annexure.mergeCells('B5:L6');
    annexure.getCell('B5').value = "NAME OF EXPORTER";
    // annexure.getCell('B5').font = { bold: true };
    annexure.getCell('B5').alignment = { horizontal: 'left', vertical: 'top' };
    setOuterBorder('A5:L6', annexure);

    annexure.mergeCells('M5:AA5');
    annexure.getCell('M5').value = companyName;
    annexure.getCell('M5').font = { bold: true };
    annexure.getCell('M5').alignment = { horizontal: 'left' };
    setOuterBorder('M5:AA5', annexure);

    annexure.mergeCells('M6:AA6');
    annexure.getCell('M6').value = `TAX ID: ${taxid}`;
    annexure.getCell('M6').alignment = { horizontal: 'left' };
    setOuterBorder('M6:AA6', annexure);

    annexure.mergeCells('A7:A10');
    annexure.getCell('A7').value = 2;
    // annexure.getCell('A7').font = { bold: true };
    annexure.getCell('A7').alignment = { horizontal: 'right', vertical: 'top' };

    annexure.mergeCells('B7:L8');
    annexure.getCell('B7').value = "(a) I.E.CODE No.";
    // annexure.getCell('B7').font = { bold: true };
    annexure.getCell('B7').alignment = { horizontal: 'left', vertical: 'top' };

    annexure.mergeCells('B9:L9');
    annexure.getCell('B9').value = "(b) BRANCH CODE No.";
    // annexure.getCell('B9').font = { bold: true };
    annexure.getCell('B9').alignment = { horizontal: 'left', vertical: 'top' };

    annexure.mergeCells('B10:L10');
    annexure.getCell('B10').value = "(c) BIN No.";
    // annexure.getCell('B10').font = { bold: true };
    annexure.getCell('B10').alignment = { horizontal: 'left', vertical: 'top' };
    setOuterBorder('A7:L10', annexure);

    annexure.mergeCells('M7:T7');
    annexure.getCell('M7').value = `I.E. CODE #: ${ieCode}`;
    annexure.getCell('M7').font = { bold: true };
    annexure.getCell('M7').alignment = { horizontal: 'left' };

    annexure.mergeCells('M8:T8');
    annexure.getCell('M8').value = `GSTIN NO. #: ${gstinNo}`;
    annexure.getCell('M8').alignment = { horizontal: 'left' };

    annexure.mergeCells('U7:AA7');
    annexure.getCell('U7').value = `PAN NO. #: ${panNo}`;
    annexure.getCell('U7').alignment = { horizontal: 'left' };

    annexure.mergeCells('U8:AA8');
    annexure.getCell('U8').value = `STATE CODE : ${stateCode}`;
    annexure.getCell('U8').alignment = { horizontal: 'left' };
    setOuterBorder('M7:AA8', annexure);

    annexure.mergeCells('M9:AA9');
    annexure.getCell('M9').value = branchCodeNo;
    annexure.getCell('M9').alignment = { horizontal: 'left' };
    setOuterBorder('M9:AA9', annexure);

    annexure.mergeCells('M10:AA10');
    annexure.getCell('M10').value = binNo;
    annexure.getCell('M10').alignment = { horizontal: 'left' };
    setOuterBorder('M10:AA10', annexure);

    annexure.mergeCells('A11:A16');
    annexure.getCell('A11').value = 3;
    // annexure.getCell('A11').font = { bold: true };
    annexure.getCell('A11').alignment = { horizontal: 'right', vertical: 'top' };

    annexure.mergeCells('B11:L11');
    annexure.getCell('B11').value = "NAME OF THE MANUFACTURER";
    // annexure.getCell('B11').font = { bold: true };
    annexure.getCell('B11').alignment = { horizontal: 'left', vertical: 'top' };

    annexure.mergeCells('B12:L12');
    annexure.getCell('B12').value = "(DIFFERENCE FROM THE EXPORTER)";
    // annexure.getCell('B12').font = { bold: true };
    annexure.getCell('B12').alignment = { horizontal: 'left', vertical: 'top' };

    annexure.mergeCells('B13:L13');
    annexure.getCell('B13').value = "FACTORY ADDRESS";
    // annexure.getCell('B13').font = { bold: true };
    annexure.getCell('B13').alignment = { horizontal: 'left', vertical: 'top' };
    setOuterBorder('A11:L16', annexure);

    annexure.mergeCells('M11:AA11');
    annexure.getCell('M11').value = manufacturer;
    annexure.getCell('M11').font = { bold: true };
    annexure.getCell('M11').alignment = { horizontal: 'left' };

    annexure.mergeCells('M12:AA15');
    annexure.getCell('M12').value = manufacturerAddress;
    annexure.getCell('M12').alignment = { wrapText: true, horizontal: 'left', vertical: 'top' };

    annexure.mergeCells('M16:AA16');
    annexure.getCell('M16').value = `GST:  ${manufacturerGST}`;
    annexure.getCell('M16').alignment = { horizontal: 'left' };
    setOuterBorder('M11:AA16', annexure);

    annexure.getCell('A17').value = 4;
    // annexure.getCell('A17').font = { bold: true };
    annexure.getCell('A17').alignment = { horizontal: 'right' };

    annexure.mergeCells('B17:L17');
    annexure.getCell('B17').value = "DATE OF EXAMINATION";
    // annexure.getCell('B17').font = { bold: true };
    annexure.getCell('B17').alignment = { horizontal: 'left' };
    setOuterBorder('A17:L17', annexure);

    annexure.mergeCells('M17:AA17');
    annexure.getCell('M17').value = `Dt. ${invoiceDate}`;
    annexure.getCell('M17').font = { bold: true };
    annexure.getCell('M17').alignment = { horizontal: 'left' };
    setOuterBorder('M17:AA17', annexure);

    annexure.mergeCells('A18:A19');
    annexure.getCell('A18').value = 5;
    // annexure.getCell('A18').font = { bold: true };
    annexure.getCell('A18').alignment = { horizontal: 'right', vertical: 'top' };

    annexure.mergeCells('B18:L18');
    annexure.getCell('B18').value = "NAME AND DESIGNATION OF THE EXAMINING";
    // annexure.getCell('B18').font = { bold: true };
    annexure.getCell('B18').alignment = { horizontal: 'left', vertical: 'top' };

    annexure.mergeCells('B19:L19');
    annexure.getCell('B19').value = "OFFICER / INSPECTOR / EO / PO";
    // annexure.getCell('B19').font = { bold: true };
    annexure.getCell('B19').alignment = { horizontal: 'left', vertical: 'top' };
    setOuterBorder('A18:L19', annexure);

    annexure.mergeCells('M18:AA18');
    annexure.getCell('M18').value = ann5;
    annexure.getCell('M18').font = { bold: true };
    annexure.getCell('M18').alignment = { horizontal: 'left' };
    setOuterBorder('M18:AA18', annexure);

    annexure.mergeCells('M19:AA19');
    setOuterBorder('M19:AA19', annexure);

    annexure.mergeCells('A20:A21');
    annexure.getCell('A20').value = 6;
    // annexure.getCell('A20').font = { bold: true };
    annexure.getCell('A20').alignment = { horizontal: 'right', vertical: 'top' };

    annexure.mergeCells('B20:L20');
    annexure.getCell('B20').value = "NAME AND DESIGNATION OF THE EXAMINING";
    // annexure.getCell('B20').font = { bold: true };
    annexure.getCell('B20').alignment = { horizontal: 'left', vertical: 'top' };

    annexure.mergeCells('B21:L21');
    annexure.getCell('B21').value = "OFFICER / APPRAISER / SUPERINTENDENT ";
    // annexure.getCell('B21').font = { bold: true };
    annexure.getCell('B21').alignment = { horizontal: 'left', vertical: 'top' };
    setOuterBorder('A20:L21', annexure);

    annexure.mergeCells('M20:AA20');
    annexure.getCell('M20').value = ann6;
    annexure.getCell('M20').font = { bold: true };
    annexure.getCell('M20').alignment = { horizontal: 'left' };
    setOuterBorder('M20:AA20', annexure);

    annexure.mergeCells('M21:AA21');
    setOuterBorder('M21:AA21', annexure);

    annexure.mergeCells('A22:A23');
    annexure.getCell('A22').value = 7;
    // annexure.getCell('A22').font = { bold: true };
    annexure.getCell('A22').alignment = { horizontal: 'right', vertical: 'top' };

    annexure.mergeCells('B22:L22');
    annexure.getCell('B22').value = "(a) NAME OF COMMISERATE / DIVISION / RANGE";
    // annexure.getCell('B22').font = { bold: true };
    annexure.getCell('B22').alignment = { horizontal: 'left', vertical: 'top' };

    annexure.mergeCells('B23:L23');
    annexure.getCell('B23').value = "(b) LOCATION CODEO";
    // annexure.getCell('B23').font = { bold: true };
    annexure.getCell('B23').alignment = { horizontal: 'left', vertical: 'top' };
    setOuterBorder('A22:L23', annexure);

    annexure.mergeCells('M22:AA22');
    annexure.getCell('M22').value = `${commissionerate} /${division} / ${range}`;
    annexure.getCell('M22').font = { bold: true };
    annexure.getCell('M22').alignment = { horizontal: 'left' };
    setOuterBorder('M22:AA22', annexure);

    annexure.mergeCells('M23:AA23');
    annexure.getCell('M23').value = locationCode;
    annexure.getCell('M23').font = { bold: true };
    annexure.getCell('M23').alignment = { horizontal: 'left' };
    setOuterBorder('M23:AA23', annexure);

    annexure.mergeCells('A24:A30');
    annexure.getCell('A24').value = 8;
    // annexure.getCell('A24').font = { bold: true };
    annexure.getCell('A24').alignment = { horizontal: 'right', vertical: 'top' };

    annexure.mergeCells('B24:L24');
    annexure.getCell('B24').value = "PARTICULARS OF EXPORT INVOICE";
    // annexure.getCell('B24').font = { bold: true };
    annexure.getCell('B24').alignment = { horizontal: 'left' };

    annexure.mergeCells('B25:L25');
    annexure.getCell('B25').value = "(a) EXPORT INVOICE No";
    // annexure.getCell('B25').font = { bold: true };
    annexure.getCell('B25').alignment = { horizontal: 'left' };

    annexure.mergeCells('B26:L26');
    annexure.getCell('B26').value = "(b) TOTAL No. OF PACKAGES";
    // annexure.getCell('B26').font = { bold: true };
    annexure.getCell('B26').alignment = { horizontal: 'left' };

    annexure.mergeCells('B27:L27');
    annexure.getCell('B27').value = "(c) NAME AND ADDRESS OF THE CONSIGNEE";
    // annexure.getCell('B27').font = { bold: true };
    annexure.getCell('B27').alignment = { horizontal: 'left' };
    setOuterBorder('A24:L30', annexure);

    annexure.mergeCells('M24:AA24');
    setOuterBorder('M24:AA24', annexure);

    annexure.mergeCells('M25:AA25');
    annexure.getCell('M25').value = `${invoiceNo}  Dt.${invoiceDate}`;
    annexure.getCell('M25').font = { bold: true };
    annexure.getCell('M25').alignment = { horizontal: 'left' };
    setOuterBorder('M25:AA25', annexure);

    annexure.mergeCells('M26:AA26');
    annexure.getCell('M26').value = `${noOfPackages} ${packegingType}`;
    annexure.getCell('M26').font = { bold: true };
    annexure.getCell('M26').alignment = { horizontal: 'left' };
    setOuterBorder('M26:AA26', annexure);

    annexure.mergeCells('M27:AA30');
    annexure.getCell('M27').value = `${consignee}\n${finalDestination}`;
    annexure.getCell('M27').font = { bold: true };
    annexure.getCell('M27').alignment = { wrapText: true, horizontal: 'left', vertical: 'top' };
    setOuterBorder('M27:AA30', annexure);


    annexure.mergeCells('A31:A33');
    annexure.getCell('A31').value = 9;
    // annexure.getCell('A31').font = { bold: true };
    annexure.getCell('A31').alignment = { horizontal: 'right', vertical: 'top' };

    annexure.mergeCells('B31:V31');
    annexure.getCell('B31').value = "(a) IS THE DESCRIPTION OF THE GOODS THE QUANTITY AND THERE VALUE AS PER PARTICULARS FURNISHED IN THE EXPORT INVOICE";
    // annexure.getCell('B31').font = { bold: true };
    annexure.getCell('B31').alignment = { horizontal: 'left' };

    annexure.mergeCells('B32:V32');
    annexure.getCell('B32').value = "(b) WHETHER SAMPLES IS DRAWN FOR BEING FORWARDED TO PORT OF EXPORT";
    // annexure.getCell('B32').font = { bold: true };
    annexure.getCell('B32').alignment = { horizontal: 'left' };

    annexure.mergeCells('B33:V33');
    annexure.getCell('B33').value = "(c) IF YES THE No. OF THE SEAL OF THE PACKAGE CONTAINING THE SAMPLE ";
    // annexure.getCell('B33').font = { bold: true };
    annexure.getCell('B33').alignment = { horizontal: 'left' };
    setOuterBorder('A31:V33', annexure);

    annexure.mergeCells('W31:AA31');
    annexure.getCell('W31').value = ann9a;
    annexure.getCell('W31').font = { bold: true };
    annexure.getCell('W31').alignment = { horizontal: 'left' };
    setOuterBorder('W31:AA31', annexure);

    annexure.mergeCells('W32:AA32');
    annexure.getCell('W32').value = ann9b;
    annexure.getCell('W32').font = { bold: true };
    annexure.getCell('W32').alignment = { horizontal: 'left' };
    setOuterBorder('W32:AA32', annexure);

    annexure.mergeCells('W33:AA33');
    annexure.getCell('W33').value = ann9c;
    annexure.getCell('W33').font = { bold: true };
    annexure.getCell('W33').alignment = { horizontal: 'left' };
    setOuterBorder('W33:AA33', annexure);

    annexure.mergeCells('A34:A36');
    annexure.getCell('A34').value = 10;
    // annexure.getCell('A34').font = { bold: true };
    annexure.getCell('A34').alignment = { horizontal: 'right', vertical: 'top' };

    annexure.mergeCells('B34:V34');
    annexure.getCell('B34').value = "CENTRAL EXCISE / CUSTOM SEAL No.";
    // annexure.getCell('B34').font = { bold: true };
    annexure.getCell('B34').alignment = { horizontal: 'left' };

    annexure.mergeCells('B35:V35');
    annexure.getCell('B35').value = "(a) FOR NON CONTAINERIZED CARGO No.OF PACKAGES";
    // annexure.getCell('B35').font = { bold: true };
    annexure.getCell('B35').alignment = { horizontal: 'left' };

    annexure.mergeCells('B36:V36');
    annexure.getCell('B36').value = "(b) FOR CONTAINERAISED CARGO";
    // annexure.getCell('B36').font = { bold: true };
    annexure.getCell('B36').alignment = { horizontal: 'left' };
    setOuterBorder('A34:V36', annexure);

    annexure.mergeCells('W34:AA34');
    annexure.getCell('W34').alignment = { horizontal: 'left' };
    setOuterBorder('W34:AA34', annexure);

    annexure.mergeCells('W35:AA35');
    annexure.getCell('W35').value = ann10a;
    annexure.getCell('W35').font = { bold: true };
    annexure.getCell('W35').alignment = { horizontal: 'left' };
    setOuterBorder('W35:AA35', annexure);

    annexure.mergeCells('W36:AA36');
    annexure.getCell('W36').value = ann10b;
    annexure.getCell('W36').font = { bold: true };
    annexure.getCell('W36').alignment = { horizontal: 'left' };
    setOuterBorder('W36:AA36', annexure);

    annexure.mergeCells('A37:B38');
    annexure.getCell('A37').value = "Sr. No.";
    annexure.getCell('A37').font = { bold: true };
    annexure.getCell('A37').alignment = { horizontal: 'center', vertical: 'middle' };
    setOuterBorder('A37:B38', annexure);

    annexure.mergeCells('C37:G38');
    annexure.getCell('C37').value = "CONTAINER NO.";
    annexure.getCell('C37').font = { bold: true };
    annexure.getCell('C37').alignment = { horizontal: 'center', vertical: 'middle' };
    setOuterBorder('C37:G38', annexure);

    annexure.mergeCells('H37:N38');
    annexure.getCell('H37').value = "LINE SEAL NO.";
    annexure.getCell('H37').font = { bold: true };
    annexure.getCell('H37').alignment = { horizontal: 'center', vertical: 'middle' };
    setOuterBorder('H37:N38', annexure);

    annexure.mergeCells('O37:S38');
    annexure.getCell('O37').value = "RFID SEAL";
    annexure.getCell('O37').font = { bold: true };
    annexure.getCell('O37').alignment = { horizontal: 'center', vertical: 'middle' };
    setOuterBorder('O37:S38', annexure);

    annexure.mergeCells('T37:V38');
    annexure.getCell('T37').value = "SIZE";
    annexure.getCell('T37').font = { bold: true };
    annexure.getCell('T37').alignment = { horizontal: 'center', vertical: 'middle' };
    setOuterBorder('T37:V38', annexure);

    annexure.mergeCells('W37:AA38');
    annexure.getCell('W37').value = "NO OF PACKAGES";
    annexure.getCell('W37').font = { bold: true };
    annexure.getCell('W37').alignment = { horizontal: 'center', vertical: 'middle' };
    setOuterBorder('W37:AA38', annexure);

    row = 39;

    for (let i = 0; i < containerDetails.length; i++) {
        annexure.mergeCells('A' + row + ':B' + row);
        annexure.getCell('A' + row).value = i + 1;
        annexure.getCell('A' + row).alignment = { horizontal: 'center' };
        setOuterBorder('A' + row + ':B' + row, annexure);

        annexure.mergeCells('C' + row + ':G' + row);
        annexure.getCell('C' + row).value = containerDetails[i][0];
        annexure.getCell('C' + row).alignment = { horizontal: 'center' };
        setOuterBorder('C' + row + ':G' + row, annexure);

        annexure.mergeCells('H' + row + ':N' + row);
        annexure.getCell('H' + row).value = containerDetails[i][1];
        annexure.getCell('H' + row).alignment = { horizontal: 'center' };
        setOuterBorder('H' + row + ':N' + row, annexure);

        annexure.mergeCells('O' + row + ':S' + row);
        annexure.getCell('O' + row).value = containerDetails[i][2];;
        annexure.getCell('O' + row).alignment = { horizontal: 'center' };
        setOuterBorder('O' + row + ':S' + row, annexure);

        annexure.mergeCells('T' + row + ':V' + row);
        annexure.getCell('T' + row).value = containerDetails[i][7];
        annexure.getCell('T' + row).alignment = { horizontal: 'center' };
        setOuterBorder('T' + row + ':V' + row, annexure);

        annexure.mergeCells('W' + row + ':AA' + row);
        annexure.getCell('W' + row).value = `${containerDetails[i][4]} ${packegingType}`;
        annexure.getCell('W' + row).alignment = { horizontal: 'center' };
        setOuterBorder('W' + row + ':AA' + row, annexure);

        row++;
    }

    let startRow = row;

    row += 4;

    annexure.getCell('A' + row).value = 11;
    annexure.getCell('A' + row).font = { bold: true };
    annexure.getCell('A' + row).alignment = { horizontal: 'right' };

    annexure.mergeCells('B' + row + ':E' + row);
    annexure.getCell('B' + row).value = "S.S. PERMISSION No.";
    annexure.getCell('B' + row).font = { bold: true };
    annexure.getCell('B' + row).alignment = { horizontal: 'left' };

    annexure.mergeCells('F' + row + ':AA' + (row + 1));
    annexure.getCell('F' + row).value = ssPermissionNo;
    annexure.getCell('F' + row).font = { color: { argb: 'FFFF0000' }, bold: true, size: 11 };
    annexure.getCell('F' + row).alignment = { wrapText: true, horizontal: 'left', vertical: 'top' };
    row += 2;

    // annexure.mergeCells('F' + row + ':AA' + row);
    // annexure.getCell('F' + row).value = issuedBy;
    // annexure.getCell('F' + row).font = { color: { argb: 'FFFF0000' }, bold: true };
    // annexure.getCell('F' + row).alignment = { horizontal: 'left' };
    // row++;

    annexure.getCell('A' + row).value = 12;
    annexure.getCell('A' + row).font = { bold: true };
    annexure.getCell('A' + row).alignment = { horizontal: 'right' };

    annexure.mergeCells('B' + row + ':AA' + row);
    annexure.getCell('B' + row).value = gstCirculerNumber;
    annexure.getCell('B' + row).font = { italic: true };
    annexure.getCell('B' + row).alignment = { horizontal: 'left' };
    row++;

    annexure.mergeCells('A' + row + ':A' + (row + 1));
    annexure.getCell('A' + row).value = 13;
    annexure.getCell('A' + row).font = { bold: true };
    annexure.getCell('A' + row).alignment = { horizontal: 'right', vertical: 'top' };

    annexure.mergeCells('B' + row + ':AA' + (row + 1));
    if (taxStatus === "without") {
        annexure.getCell('B' + row).value = `LETTER OF UNDERTAKING NO.ACKNOWLEDGMENT FOR LUT  APPLICATION REFERENCE NUMBER (ARN) ${arn}\nDT:${lutDate}`;
    } else {
        annexure.getCell('B' + row).value = `SUPPLY MEANT FOR EXPORT ON PAYMENT OF IGST UNDER CLAIM OF REFUND RS. TOTAL : ${gstValue}\n(TAXABLE ${termsOfDelivery} INR VALUE ${totalInINR}@ 18%)                                                                            ${gstValue}  `;
    }
    annexure.getCell('B' + row).font = { italic: true };
    annexure.getCell('B' + row).alignment = { wrapText: true, horizontal: 'left', vertical: 'top' };
    row += 2;

    annexure.mergeCells('A' + row + ':AA' + (row + 1));
    annexure.getCell('A' + row).value = `EXAMINED THE EXPORT GOODS COVERED UNDER THIS INVOICE ,DESCRIPTION OF THE GOODS WITH REFERENCE TO DBK & MEIS SCHEME & NET WAIGHT OF ALL ${allProductsType} ARE AS UNDER`;
    annexure.getCell('A' + row).alignment = { wrapText: true, horizontal: 'left', vertical: 'top' };
    row += 2;

    annexure.mergeCells('A' + row + ':AA' + row);
    annexure.getCell('A' + row).value = `EXPORT UNDER SELF SEALING UNDER Circular No. ${selfSealingCircularNo} Dated : ${selfSealingCircularNoDate}`;
    annexure.getCell('A' + row).font = { bold: true, underline: true };
    annexure.getCell('A' + row).alignment = { wrapText: true, horizontal: 'center' };
    row++;

    annexure.mergeCells('A' + row + ':AA' + (row + 1));
    annexure.getCell('A' + row).value = "Certified that the description and value of the goods coverd by this invoice have been checked by me and the goods have been packed and sealed with lead seal one time lock seal checked by me and the goods have been packed and sealed with lead seal/ one time lock seal.";
    annexure.getCell('A' + row).alignment = { wrapText: true, horizontal: 'left' };
    row += 3;

    annexure.mergeCells('A' + row + ':E' + row);
    annexure.getCell('A' + row).value = `For, ${companyName}`;
    annexure.getCell('A' + row).font = { bold: true };
    annexure.getCell('A' + row).alignment = { horizontal: 'left' };

    annexure.addImage(signature, {
        tl: { col: 3, row: (row - 1) }, // X66 (X = col 24 → 24 - 1 = 23 → 22 for 0-based)
        ext: { width: 100, height: 100 }, // adjust size as needed
    });

    annexure.mergeCells('O' + row + ':AA' + row);
    annexure.getCell('O' + row).value = `NET WEIGHT: ${netWeight} KGS        GROSS WEIGHT: ${grossWeight} KGS`;
    // annexure.getCell('O' + row).fill = {
    //     type: 'pattern',
    //     pattern: 'solid',
    //     fgColor: { argb: 'FFFFFF00' },
    // };
    annexure.getCell('O' + row).font = { bold: true };
    annexure.getCell('O' + row).alignment = { horizontal: 'left' };
    row += 4;

    annexure.mergeCells('A' + row + ':D' + row);
    annexure.getCell('A' + row).value = "AUTHORISED SIGN.";
    annexure.getCell('A' + row).font = { bold: true };
    annexure.getCell('A' + row).alignment = { horizontal: 'left' };
    row++;

    annexure.mergeCells('A' + row + ':E' + row);
    annexure.getCell('A' + row).value = "SIGNATURE OF EXPORTER";
    annexure.getCell('A' + row).alignment = { horizontal: 'left' };

    setOuterBorder('A' + startRow + ':AA' + row, annexure);

    MAX_WIDTH = 4;

    annexure.columns.forEach((column) => {
        let maxLength = 10;

        column.eachCell({ includeEmpty: true }, (cell) => {
            const cellValue = cell.value ? cell.value.toString() : '';
            const lines = cellValue.split('\n');
            const longestLine = Math.max(...lines.map(line => line.length));
            if (longestLine > maxLength) {
                maxLength = longestLine;
            }
        });

        column.width = Math.min(maxLength + 2, MAX_WIDTH); // 👈 LIMIT IT
    });

    for (let i = 1; i <= 12; i++) {
        annexure.getColumn(i).width = pixelToExcelWidth(50);
    }

    setGlobalFontSize(annexure);





















































































    // The sheet comes off the workbook rather than the local binding: in some
    // sections that binding is declared inside a conditional and is not in
    // scope here. It is the same object either way.
    return {
        workbook: annexureWorkbook,
        sheet: annexureWorkbook.worksheets[0],
        state: { ...state, row, allProductsType, MAX_WIDTH },
        built: {
            ...built,
            annexureWorkbook: annexureWorkbook,
            annexure: annexureWorkbook.worksheets[0]
        }
    }
}
