/* eslint-disable */
// @ts-nocheck
// GENERATED by scripts/split-generator.mjs from ui/src/lib/excelGenerator.ts.
// The body below is a verbatim copy. Do not edit or reformat it by hand —
// re-run `npm run docs:split` instead. The original was written with
// TypeScript strictness disabled, so it is excluded from type checking;
// correctness is established by scripts/compare-generators.mts, which diffs
// every cell against the original generator.
// Source lines 6078-7535.

import ExcelJS from 'exceljs'
import { format } from 'date-fns'
import { convertNamesToInitials, formatNames, round3 } from '../helpers'
import { loadImageBuffer } from '../loadImageBuffer'
import type { DocumentContext } from '../context'
import type { SheetState } from '../state'

void ExcelJS
void format
void round3
void convertNamesToInitials
void formatNames
void loadImageBuffer

export const buildCustomerInvoice = async (
  ctx: DocumentContext,
  state: SheetState,
  built: Record<string, any> = {}
): Promise<{ workbook: any; sheet: any; state: SheetState; built: Record<string, any> }> => {
    void built
    const {
        companyName,
        companyAddress,
        email,
        taxid,
        ieCode,
        panNo,
        gstinNo,
        stateCode,
        invoiceNo,
        invoiceDate,
        buyersOrderNo,
        buyersOrderDate,
        poNo,
        consignee,
        notifyParty,
        preCarriage,
        vassalFlightNo,
        placeOfReceipt,
        portOfLoading,
        portOfDischarge,
        finalDestination,
        countryOfOrigin,
        origin,
        termsOfDeliveryMain,
        termsOfDelivery,
        termsOfDeliveryMainAt,
        paymentTerms,
        shippingMethod,
        currency,
        currencyRate,
        containerType,
        marksAndNos,
        products,
        grossWeight,
        netWeight,
        insurance,
        freight,
        totalFOBEuro,
        amountInWords,
        arn,
        lutDate,
        totalInINR,
        gstValue,
        supplierDetails,
        packegingType,
        taxStatus,
        type,
        unitOfIt,
        signatureUrl,
        configurePrintSheet,
        setGlobalFontSize,
        pixelToExcelWidth,
        columnWidths,
        setOuterBorder
    } = ctx
    let { srNo, row, hsnCode, allProductsType, skipRow, addSkipRow, MAX_WIDTH } = state
    const { worksheet } = built
    let signature: any, vgnSignatureW: any, vgnSignatureH: any

    const customerInvoiceWorkbook = new ExcelJS.Workbook();
    const customerInvoice = customerInvoiceWorkbook.addWorksheet('CI');

    if (signatureUrl) {

        const { buffer, extension, width, height } = await loadImageBuffer(signatureUrl);
        signature = customerInvoiceWorkbook.addImage({
            buffer: buffer,
            extension: extension,
        });
        vgnSignatureW = width;
        vgnSignatureH = height;

    }
    

    customerInvoiceWorkbook.calcProperties.fullCalcOnLoad = true;
    customerInvoice.getColumn(1).width = 5;
    customerInvoice.getCell('A1').value = worksheet.getCell('A1').value || ' ';
    configurePrintSheet(customerInvoice);
    customerInvoice.getColumn(17).hidden = true;


    customerInvoice.mergeCells('A1:AA1');
    customerInvoice.getCell('A1').value = 'COMMERCIAL INVOICE';
    customerInvoice.getCell('A1').font = { bold: true };
    customerInvoice.getCell('A1').alignment = { horizontal: 'center' };
    setOuterBorder('A1:AA1', customerInvoice);

    // ✅ Red note below title
    customerInvoice.mergeCells('A2:AA2');
    // if (taxStatus === "without") {
    //   customerInvoice.getCell('A2').value = '“SUPPLY MEANT FOR EXPORT UNDER BOND & LUT- LETTER OF UNDERTAKING WITHOUT PAYMENT OF INTEGRATED TAX”';
    // } else if (taxStatus === "with") {
    //   customerInvoice.getCell('A2').value = '“SUPPLY MEANT FOR EXPORT WITH PAYMENT OF INTEGRATED TAX (IGST)”';
    // }
    // // customerInvoice.getCell('A2').font = { bold: true, color: { argb: 'FFFF0000' } };
    // customerInvoice.getCell('A2').font = { bold: true, italic: true };
    // customerInvoice.getCell('A2').alignment = { horizontal: 'center' };
    setOuterBorder('A2:AA2', customerInvoice);
    customerInvoice.getRow(2).hidden = true;

    // ✅ Exporter Info
    customerInvoice.mergeCells('A3:N3');
    customerInvoice.getCell('A3').value = `EXPORTER:`;
    customerInvoice.getCell('A3').alignment = { wrapText: true, vertical: 'top' };
    customerInvoice.getCell('A3').font = { bold: true, underline: true };

    customerInvoice.mergeCells('A4:N10');
    customerInvoice.getCell('A4').value = `${companyName}\n${companyAddress}`;
    customerInvoice.getCell('A4').alignment = { wrapText: true, vertical: 'top' };
    customerInvoice.getCell('A4').font = { bold: true };
    setOuterBorder('A4:N10', customerInvoice);

    // ✅ Email & Tax No

    customerInvoice.mergeCells('A11:B11');
    customerInvoice.getCell('A11').value = `EMAIL:`;
    customerInvoice.getCell('A11').font = { bold: true };
    customerInvoice.getCell('A11').alignment = { wrapText: true };

    customerInvoice.mergeCells('A12:B12');
    customerInvoice.getCell('A12').value = `TAX ID:`;
    customerInvoice.getCell('A12').font = { bold: true };
    customerInvoice.getCell('A12').alignment = { wrapText: true };

    customerInvoice.mergeCells('C11:N11');
    customerInvoice.getCell('C11').value = email;
    customerInvoice.getCell('C11').alignment = { wrapText: true };

    customerInvoice.mergeCells('C12:N12');
    customerInvoice.getCell('C12').value = taxid;
    customerInvoice.getCell('C12').alignment = { wrapText: true };
    setOuterBorder('A11:N12', customerInvoice);

    // ✅ Invoice No. & Date
    customerInvoice.mergeCells('O3:T3');
    customerInvoice.getCell('O3').value = "Invoice No. & Date:";
    customerInvoice.getCell('O3').font = { bold: true };
    customerInvoice.getCell('O3').alignment = { horizontal: 'center' };

    customerInvoice.mergeCells('O4:T4');
    customerInvoice.getCell('O4').value = `${invoiceNo}`;

    customerInvoice.mergeCells('O5:T5');
    customerInvoice.getCell('O5').value = `Dt. ${invoiceDate}`;

    setOuterBorder('O3:T5', customerInvoice);

    // ✅ Exporter's Ref
    customerInvoice.mergeCells('U3:AA3');
    customerInvoice.getCell('U3').value = "Exporter’s Ref.:";
    customerInvoice.getCell('U3').font = { bold: true };

    customerInvoice.mergeCells('U4:AA12');
    customerInvoice.getCell('U4').value = `I. E. Code #: ${ieCode}\nPAN No #: ${panNo}\nGSTIN No #: ${gstinNo}\nSTATE CODE : ${stateCode}`;
    customerInvoice.getCell('U4').alignment = { wrapText: true, vertical: 'top' };
    setOuterBorder('U3:AA12', customerInvoice);

    // ✅ Buyer's Order No
    customerInvoice.mergeCells('O6:T6');
    customerInvoice.getCell('O6').value = "Buyer's Order no. & Date";
    customerInvoice.getCell('O6').font = { bold: true };

    customerInvoice.mergeCells('O7:T8');
    customerInvoice.getCell('O7').value = `${buyersOrderNo}    ${buyersOrderDate}`;
    customerInvoice.getCell('O7').alignment = { wrapText: true, vertical: 'top' };

    customerInvoice.mergeCells('O12:T12');
    customerInvoice.getCell('O12').value = `PO No: ${poNo}`;
    setOuterBorder('O6:T12', customerInvoice);

    // ✅ Consignee
    customerInvoice.mergeCells('A13:N13');
    customerInvoice.getCell('A13').value = "Consignee:";
    customerInvoice.getCell('A13').font = { bold: true, underline: true };

    customerInvoice.mergeCells('A14:N19');
    customerInvoice.getCell('A14').value = `${consignee}`;
    customerInvoice.getCell('A14').alignment = { wrapText: true, vertical: 'top' };
    setOuterBorder('A13:N19', customerInvoice);

    // ✅ Notify Party
    customerInvoice.mergeCells('O13:AA13');
    customerInvoice.getCell('O13').value = "Notify Party # :";
    customerInvoice.getCell('O13').font = { bold: true };

    customerInvoice.mergeCells('O14:AA19');
    customerInvoice.getCell('O14').value = `${notifyParty}`;
    customerInvoice.getCell('O14').font = { bold: true };
    customerInvoice.getCell('O14').alignment = { wrapText: true, vertical: 'top' };
    setOuterBorder('O13:AA19', customerInvoice, 'medium'); // Removalble

    customerInvoice.mergeCells('A20:G20');
    customerInvoice.getCell('A20').value = 'Pre-Carriage By';
    // customerInvoice.getCell('A20').font = { bold: true };
    customerInvoice.getCell('A20').alignment = { horizontal: 'center' };

    customerInvoice.mergeCells('A21:G21');
    customerInvoice.getCell('A21').value = `${preCarriage}`;
    customerInvoice.getCell('A21').font = { color: { argb: 'FFFF0000' }, bold: true };
    customerInvoice.getCell('A21').alignment = { horizontal: 'center' };
    setOuterBorder('A20:G21', customerInvoice);

    customerInvoice.mergeCells('H20:N20');
    customerInvoice.getCell('H20').value = "Place of Receipt by Pre-Carrier";
    // customerInvoice.getCell('H20').font = { bold: true };
    customerInvoice.getCell('H20').alignment = { horizontal: 'center' };

    customerInvoice.mergeCells('H21:N21');
    customerInvoice.getCell('H21').value = `${placeOfReceipt}`;
    customerInvoice.getCell('H21').font = { color: { argb: 'FFFF0000' }, bold: true };
    customerInvoice.getCell('H21').alignment = { horizontal: 'center' };
    setOuterBorder('H20:N21', customerInvoice);

    customerInvoice.mergeCells('O20:V20');
    // customerInvoice.getCell('O20').value = `Country of Origin of Goods : ${countryOfOrigin}`;
    customerInvoice.getCell('O20').value = {
        richText: [
            { text: 'Country of Origin of Goods : ', font: { bold: false } },
            // { text: countryOfOrigin, font: { bold: true } }
            { text: "INDIA", font: { bold: true } }
        ]
    };
    customerInvoice.getCell('O20').alignment = { horizontal: 'center' };

    customerInvoice.mergeCells('O21:V21');
    // customerInvoice.getCell('O21').value = `ORIGIN : ${origin}`;
    customerInvoice.getCell('O21').value = `ORIGIN : DISTRICT MORBI, STATE GUJARAT`;
    customerInvoice.getCell('O21').font = { bold: true };
    customerInvoice.getCell('O21').alignment = { horizontal: 'center' };
    setOuterBorder('O20:V21', customerInvoice);

    customerInvoice.mergeCells('W20:AA20');
    customerInvoice.getCell('W20').value = "Country of Final Destination";
    customerInvoice.getCell('W20').alignment = { horizontal: 'center' };

    customerInvoice.mergeCells('W21:AA21');
    customerInvoice.getCell('W21').value = `${finalDestination}`;
    customerInvoice.getCell('W21').font = { bold: true };
    customerInvoice.getCell('W21').alignment = { horizontal: 'center' };
    setOuterBorder('W20:AA21', customerInvoice);

    customerInvoice.mergeCells('A22:G22');
    customerInvoice.getCell('A22').value = 'Vessel Flight No.';
    // customerInvoice.getCell('A22').font = { bold: true };
    customerInvoice.getCell('A22').alignment = { horizontal: 'center' };

    customerInvoice.mergeCells('A23:G23');
    customerInvoice.getCell('A23').value = `${vassalFlightNo}`;
    customerInvoice.getCell('A23').font = { color: { argb: 'FFFF0000' }, bold: true };
    customerInvoice.getCell('A23').alignment = { horizontal: 'center' };
    setOuterBorder('A22:G23', customerInvoice);

    customerInvoice.mergeCells('H22:N22');
    customerInvoice.getCell('H22').value = "Port of Loading";
    // customerInvoice.getCell('H22').font = { bold: true };
    customerInvoice.getCell('H22').alignment = { horizontal: 'center' };

    customerInvoice.mergeCells('H23:N23');
    customerInvoice.getCell('H23').value = `${portOfLoading}`;
    customerInvoice.getCell('H23').font = { color: { argb: 'FFFF0000' }, bold: true };
    customerInvoice.getCell('H23').alignment = { horizontal: 'center' };
    setOuterBorder('H22:N23', customerInvoice);

    customerInvoice.mergeCells('A24:G24');
    customerInvoice.getCell('A24').value = 'Port of Discharge';
    // customerInvoice.getCell('A24').font = { bold: true };
    customerInvoice.getCell('A24').alignment = { horizontal: 'center' };

    customerInvoice.mergeCells('A25:G26');
    customerInvoice.getCell('A25').value = `${portOfDischarge}`;
    customerInvoice.getCell('A25').font = { color: { argb: 'FFFF0000' }, bold: true };
    customerInvoice.getCell('A25').alignment = { horizontal: 'center', vertical: 'middle' };
    setOuterBorder('A24:G26', customerInvoice);

    customerInvoice.mergeCells('H24:N24');
    customerInvoice.getCell('H24').value = "Final Destination";
    // customerInvoice.getCell('H24').font = { bold: true };
    customerInvoice.getCell('H24').alignment = { horizontal: 'center' };

    customerInvoice.mergeCells('H25:N26');
    customerInvoice.getCell('H25').value = `${finalDestination}`;
    customerInvoice.getCell('H25').font = { color: { argb: 'FFFF0000' }, bold: true };
    customerInvoice.getCell('H25').alignment = { horizontal: 'center', vertical: 'middle' };
    setOuterBorder('H24:N26', customerInvoice);

    customerInvoice.mergeCells('O22:AA22');
    customerInvoice.getCell('O22').value = "Terms of Delivery & Payment :-";
    customerInvoice.getCell('O22').font = { bold: true };

    customerInvoice.mergeCells('O23:AA23');
    if (termsOfDelivery === "FOB") {
        customerInvoice.getCell('O23').value = termsOfDeliveryMainAt;
    } else {
        customerInvoice.getCell('O23').value = termsOfDeliveryMainAt;
    }
    customerInvoice.getCell('O23').font = { color: { argb: 'FFFF0000' } };

    customerInvoice.mergeCells('O24:AA25');
    customerInvoice.getCell('O24').value = `PAYMENT : ${paymentTerms}`;
    customerInvoice.getCell('O24').font = { name: 'Arial', color: { argb: 'FFFF0000' } };
    customerInvoice.getCell('O24').alignment = { wrapText: true, horizontal: 'left', vertical: 'top' };

    customerInvoice.mergeCells('O26:U26');
    customerInvoice.getCell('O26').value = shippingMethod;
    setOuterBorder('O22:AA26', customerInvoice);

    // if (type !== "tiles") {
    //   customerInvoice.mergeCells('W26:Y26');
    //   customerInvoice.getCell('W26').value = `${currency} RATE:`;
    //   customerInvoice.getCell('W26').alignment = { horizontal: 'center' };
    //   customerInvoice.getCell('W26').font = { bold: true };

    //   customerInvoice.mergeCells('Z26:AA26');
    //   customerInvoice.getCell('Z26').value = currencyRate;
    //   // customerInvoice.getCell('Z26').fill = {
    //   //     type: 'pattern',
    //   //     pattern: 'solid',
    //   //     fgColor: { argb: 'FFFFFF00' }, // Yellow fill
    //   // };
    //   customerInvoice.getCell('Z26').alignment = { horizontal: 'center' };
    //   customerInvoice.getCell('Z26').font = { bold: true };
    //   setOuterBorder('W26:AA26', customerInvoice, 'medium');
    // } else {
    //   customerInvoice.mergeCells('V26:X26');
    //   customerInvoice.getCell('V26').value = `${currency} RATE:`;
    //   customerInvoice.getCell('V26').alignment = { horizontal: 'center' };
    //   customerInvoice.getCell('V26').font = { bold: true };

    //   customerInvoice.mergeCells('Y26:AA26');
    //   customerInvoice.getCell('Y26').value = currencyRate;
    //   customerInvoice.getCell('Y26').alignment = { horizontal: 'center' };
    //   // customerInvoice.getCell('Y26').fill = {
    //   //     type: 'pattern',
    //   //     pattern: 'solid',
    //   //     fgColor: { argb: 'FFFFFF00' }, // Yellow fill
    //   // };
    //   customerInvoice.getCell('Y26').font = { bold: true };
    //   setOuterBorder('V26:AA26', customerInvoice, 'medium');
    // }

    customerInvoice.mergeCells('A27:D27');
    customerInvoice.getCell('A27').value = "Marks & Nos.";
    customerInvoice.getCell('A27').font = { bold: true };
    customerInvoice.getCell('A27').alignment = { horizontal: 'center' };

    if (containerType === 'FCL') {
        customerInvoice.mergeCells('A28:D28');
        customerInvoice.getCell('A28').value = `${marksAndNos} ${containerType}`;
        customerInvoice.getCell('A28').font = { bold: true };
        customerInvoice.getCell('A28').alignment = { horizontal: 'center' };
        setOuterBorder('A27:D28', customerInvoice, 'medium');
    } else {
        customerInvoice.mergeCells('A28:D28');
        customerInvoice.getCell('A28').value = `${containerType}`;
        customerInvoice.getCell('A28').font = { bold: true };
        customerInvoice.getCell('A28').alignment = { horizontal: 'center', vertical: 'middle' };
        setOuterBorder('A27:D28', customerInvoice, 'medium');
    }
    customerInvoice.getRow(28).height = 24;

    customerInvoice.mergeCells('E27:Q28');
    customerInvoice.getCell('E27').value = "Description of Goods";
    customerInvoice.getCell('E27').font = { bold: true };
    customerInvoice.getCell('E27').alignment = { horizontal: 'center', vertical: 'middle' };
    setOuterBorder('E27:Q28', customerInvoice, 'medium');

    if (type !== "tiles") {
        customerInvoice.getCell('R27').value = "SIZE";
        customerInvoice.getCell('R27').font = { bold: true };
        customerInvoice.getCell('R27').alignment = { horizontal: 'center', vertical: 'middle' };

        customerInvoice.getCell('R28').value = "MM";
        customerInvoice.getCell('R28').font = { bold: true };
        customerInvoice.getCell('R28').alignment = { horizontal: 'center', vertical: 'middle' };
        setOuterBorder('R27:R28', customerInvoice, 'medium');

        customerInvoice.mergeCells('S27:T27')
        customerInvoice.getCell('S27').value = "QUANTITY";
        customerInvoice.getCell('S27').font = { bold: true };
        customerInvoice.getCell('S27').alignment = { horizontal: 'center', vertical: 'middle' };

        customerInvoice.mergeCells('S28:T28')
        customerInvoice.getCell('S28').value = packegingType;
        customerInvoice.getCell('S28').font = { bold: true };
        customerInvoice.getCell('S28').alignment = { wrapText: true, horizontal: 'center', vertical: 'middle' };
        setOuterBorder('S27:T28', customerInvoice, 'medium');
        if (packegingType.length > 8) {
            customerInvoice.getCell('S28').font = { size: 8, bold: true };
        }

        customerInvoice.mergeCells('U27:V27')
        customerInvoice.getCell('U27').value = "UNIT TYPE";
        customerInvoice.getCell('U27').font = { bold: true };
        customerInvoice.getCell('U27').alignment = { horizontal: 'center', vertical: 'middle' };

        customerInvoice.mergeCells('U28:V28')
        customerInvoice.getCell('U28').value = packegingType;
        customerInvoice.getCell('U28').font = { bold: true };
        customerInvoice.getCell('U28').alignment = { wrapText: true, horizontal: 'center', vertical: 'middle' };
        setOuterBorder('U27:V28', customerInvoice, 'medium');

        customerInvoice.mergeCells('W27:X27')
        customerInvoice.getCell('W27').value = "SQM/";
        customerInvoice.getCell('W27').font = { bold: true };
        customerInvoice.getCell('W27').alignment = { horizontal: 'center', vertical: 'middle' };

        customerInvoice.mergeCells('W28:X28')
        customerInvoice.getCell('W28').value = unitOfIt;
        customerInvoice.getCell('W28').font = { bold: true };
        customerInvoice.getCell('W28').alignment = { horizontal: 'center', vertical: 'middle' };
        setOuterBorder('W27:X28', customerInvoice, 'medium');

        customerInvoice.getCell('Y27').value = "TOTAL";
        customerInvoice.getCell('Y27').font = { bold: true };
        customerInvoice.getCell('Y27').alignment = { horizontal: 'center', vertical: 'middle' };

        customerInvoice.getCell('Y28').value = "SQM";
        customerInvoice.getCell('Y28').font = { bold: true };
        customerInvoice.getCell('Y28').alignment = { horizontal: 'center', vertical: 'middle' };
        setOuterBorder('Y27:Y28', customerInvoice, 'medium');

        customerInvoice.getCell('Z27').value = "PRICE/";
        customerInvoice.getCell('Z27').font = { bold: true };
        customerInvoice.getCell('Z27').alignment = { horizontal: 'center', vertical: 'middle' };

        customerInvoice.getCell('Z28').value = "SQM";
        customerInvoice.getCell('Z28').font = { bold: true };
        customerInvoice.getCell('Z28').alignment = { horizontal: 'center', vertical: 'middle' };
        setOuterBorder('Z27:Z28', customerInvoice, 'medium');

        customerInvoice.getCell('AA27').value = "AMOUNT";
        customerInvoice.getCell('AA27').font = { bold: true };
        customerInvoice.getCell('AA27').alignment = { horizontal: 'center', vertical: 'middle' };

        customerInvoice.getCell('AA28').value = `IN (${currency})`;
        customerInvoice.getCell('AA28').font = { bold: true };
        customerInvoice.getCell('AA28').alignment = { horizontal: 'center', vertical: 'middle' };
        setOuterBorder('AA27:AA28', customerInvoice, 'medium');
    }
    else {
        customerInvoice.mergeCells('R27:S27')
        customerInvoice.getCell('R27').value = "QUANTITY";
        customerInvoice.getCell('R27').font = { bold: true };
        customerInvoice.getCell('R27').alignment = { horizontal: 'center', vertical: 'middle' };

        customerInvoice.mergeCells('R28:S28')
        customerInvoice.getCell('R28').value = "PKGS";
        customerInvoice.getCell('R28').font = { bold: true };
        customerInvoice.getCell('R28').alignment = { horizontal: 'center', vertical: 'middle' };
        setOuterBorder('R27:S28', customerInvoice);

        customerInvoice.mergeCells('T27:U27')
        customerInvoice.getCell('T27').value = "UNIT TYPE";
        customerInvoice.getCell('T27').font = { bold: true };
        customerInvoice.getCell('T27').alignment = { horizontal: 'center', vertical: 'middle' };

        customerInvoice.mergeCells('T28:U28')
        customerInvoice.getCell('T28').value = packegingType;
        customerInvoice.getCell('T28').font = { bold: true };
        customerInvoice.getCell('T28').alignment = { horizontal: 'center', vertical: 'middle' };
        setOuterBorder('T27:U28', customerInvoice);
        if (packegingType.length > 8) {
            customerInvoice.getCell('T28').font = { size: 8, bold: true };
        }

        customerInvoice.mergeCells('V27:X27')
        customerInvoice.getCell('V27').value = "RATE PER";
        customerInvoice.getCell('V27').font = { bold: true };
        customerInvoice.getCell('V27').alignment = { horizontal: 'center', vertical: 'middle' };

        customerInvoice.mergeCells('V28:X28')
        customerInvoice.getCell('V28').value = `UNIT (${currency})`;
        customerInvoice.getCell('V28').font = { bold: true };
        customerInvoice.getCell('V28').alignment = { horizontal: 'center', vertical: 'middle' };
        setOuterBorder('V27:X28', customerInvoice);

        customerInvoice.mergeCells('Y27:AA27')
        customerInvoice.getCell('Y27').value = "AMOUNT/";
        customerInvoice.getCell('Y27').font = { bold: true };
        customerInvoice.getCell('Y27').alignment = { horizontal: 'center', vertical: 'middle' };

        customerInvoice.mergeCells('Y28:AA28')
        customerInvoice.getCell('Y28').value = `IN (${currency})`;
        customerInvoice.getCell('Y28').font = { bold: true };
        customerInvoice.getCell('Y28').alignment = { horizontal: 'center', vertical: 'middle' };
        setOuterBorder('Y27:AA28', customerInvoice);
    }
    if (packegingType.length > 6) {
        customerInvoice.getRow(28).height = 36;
    }

    customerInvoice.getCell('A29').value = "SR NO.";
    customerInvoice.getCell('A29').font = { bold: true };
    customerInvoice.getCell('A29').alignment = { horizontal: 'center', vertical: 'middle' };
    customerInvoice.getCell('A29').border = {
        top: { style: 'thin', color: { argb: 'FF000000' } },     // black
        left: { style: 'thin', color: { argb: 'FF000000' } },
        bottom: { style: 'thin', color: { argb: 'FF000000' } },
        right: { style: 'thin', color: { argb: 'FF000000' } },
    };

    customerInvoice.mergeCells('B29:D29');
    customerInvoice.getCell('B29').value = "HSN CODE";
    customerInvoice.getCell('B29').font = { bold: true };
    customerInvoice.getCell('B29').alignment = { horizontal: 'center', vertical: 'middle' };
    setOuterBorder('B29:D29', customerInvoice);

    // Table saction

    srNo = 1;
    row = 28;
    // hsnCode: number;
    // allProductsType: string;
    for (let i = 0; i < products.length; i++) {
        if (type !== "tiles") {
            row++;
            if (products[i].length === 2) {
                customerInvoice.mergeCells('E' + row + ':Q' + row);
                customerInvoice.getCell('E' + row).value = products[i][0];
                // customerInvoice.getCell('E' + row).fill = {
                //     type: 'pattern',
                //     pattern: 'solid',
                //     fgColor: { argb: 'FFFFCC99' }, // Light orange / peach
                // };
                customerInvoice.getCell('E' + row).font = { bold: true, size: 12 };
                customerInvoice.getCell('E' + row).alignment = { horizontal: 'center', vertical: 'middle' };
                customerInvoice.getRow(row).height = 46;
                setOuterBorder('E' + row + ':Q' + row, customerInvoice);
                hsnCode = Number(products[i][1]);
                if (i == 0) {
                    allProductsType = String(products[i][0]);
                }
                else {
                    allProductsType += '/' + String(products[i][0]);
                }

                if (i !== 0) {
                    customerInvoice.getCell('A' + row).border = {
                        top: { style: 'thin', color: { argb: 'FF000000' } },     // black
                        left: { style: 'thin', color: { argb: 'FF000000' } },
                        bottom: { style: 'thin', color: { argb: 'FF000000' } },
                        right: { style: 'thin', color: { argb: 'FF000000' } },
                    };

                    setOuterBorder('B' + row + ':D' + row, customerInvoice);
                }
                setOuterBorder('E' + row + ':Q' + row, customerInvoice);

                customerInvoice.getCell('R' + row).border = {
                    top: { style: 'thin', color: { argb: 'FF000000' } },     // black
                    left: { style: 'thin', color: { argb: 'FF000000' } },
                    bottom: { style: 'thin', color: { argb: 'FF000000' } },
                    right: { style: 'thin', color: { argb: 'FF000000' } },
                };

                setOuterBorder('S' + row + ':T' + row, customerInvoice);
                setOuterBorder('U' + row + ':V' + row, customerInvoice);
                setOuterBorder('W' + row + ':X' + row, customerInvoice);

                customerInvoice.getCell('Y' + row).border = {
                    top: { style: 'thin', color: { argb: 'FF000000' } },     // black
                    left: { style: 'thin', color: { argb: 'FF000000' } },
                    bottom: { style: 'thin', color: { argb: 'FF000000' } },
                    right: { style: 'thin', color: { argb: 'FF000000' } },
                };

                customerInvoice.getCell('Z' + row).border = {
                    top: { style: 'thin', color: { argb: 'FF000000' } },     // black
                    left: { style: 'thin', color: { argb: 'FF000000' } },
                    bottom: { style: 'thin', color: { argb: 'FF000000' } },
                    right: { style: 'thin', color: { argb: 'FF000000' } },
                };

                customerInvoice.getCell('AA' + row).border = {
                    top: { style: 'thin', color: { argb: 'FF000000' } },     // black
                    left: { style: 'thin', color: { argb: 'FF000000' } },
                    bottom: { style: 'thin', color: { argb: 'FF000000' } },
                    right: { style: 'thin', color: { argb: 'FF000000' } },
                };

            } else {

                customerInvoice.getCell('A' + row).value = srNo;
                customerInvoice.getCell('A' + row).alignment = { wrapText: true, horizontal: 'center', vertical: 'middle' };
                customerInvoice.getCell('A' + row).border = {
                    top: { style: 'thin', color: { argb: 'FF000000' } },     // black
                    left: { style: 'thin', color: { argb: 'FF000000' } },
                    bottom: { style: 'thin', color: { argb: 'FF000000' } },
                    right: { style: 'thin', color: { argb: 'FF000000' } },
                };
                srNo++;

                customerInvoice.mergeCells('B' + row + ':D' + row);
                customerInvoice.getCell('B' + row).value = hsnCode;
                customerInvoice.getCell('B' + row).font = { bold: true };
                customerInvoice.getCell('B' + row).alignment = { wrapText: true, horizontal: 'center', vertical: 'middle' };
                setOuterBorder('B' + row + ':D' + row, customerInvoice);

                customerInvoice.mergeCells('E' + row + ':Q' + row);
                customerInvoice.getCell('E' + row).value = products[i][0];
                customerInvoice.getCell('E' + row).font = { size: 12 };
                customerInvoice.getCell('E' + row).alignment = { wrapText: true, horizontal: 'center', vertical: 'middle' };
                setOuterBorder('E' + row + ':Q' + row, customerInvoice);
                if (String(products[i][0]).length > 56) {
                    customerInvoice.getRow(row).height = 36;
                }

                if (products[i][1] === "-") {
                    customerInvoice.getCell('R' + row).value = "-";
                } else {
                    customerInvoice.getCell('R' + row).value = products[i][1];
                }
                customerInvoice.getCell('R' + row).alignment = { wrapText: true, horizontal: 'center', vertical: 'middle' };
                customerInvoice.getCell('R' + row).font = { size: 12 };
                customerInvoice.getCell('R' + row).border = {
                    top: { style: 'thin', color: { argb: 'FF000000' } },     // black
                    left: { style: 'thin', color: { argb: 'FF000000' } },
                    bottom: { style: 'thin', color: { argb: 'FF000000' } },
                    right: { style: 'thin', color: { argb: 'FF000000' } },
                };

                customerInvoice.mergeCells('S' + row + ':T' + row);
                customerInvoice.getCell('S' + row).value = products[i][2];
                customerInvoice.getCell('S' + row).font = { size: 12 };
                customerInvoice.getCell('S' + row).alignment = { wrapText: true, horizontal: 'center', vertical: 'middle' };
                setOuterBorder('S' + row + ':T' + row, customerInvoice);

                customerInvoice.mergeCells('U' + row + ':V' + row);
                customerInvoice.getCell('U' + row).value = products[i][3];
                customerInvoice.getCell('U' + row).font = { size: 12 };
                customerInvoice.getCell('U' + row).alignment = { wrapText: true, horizontal: 'center', vertical: 'middle' };
                setOuterBorder('U' + row + ':V' + row, customerInvoice);

                customerInvoice.mergeCells('W' + row + ':X' + row);
                if (products[i][4] === "-") {
                    customerInvoice.getCell('W' + row).value = "-";
                } else {
                    customerInvoice.getCell('W' + row).value = products[i][4];
                }
                customerInvoice.getCell('W' + row).font = { size: 12 };
                customerInvoice.getCell('W' + row).alignment = { wrapText: true, horizontal: 'center', vertical: 'middle' };
                setOuterBorder('W' + row + ':X' + row, customerInvoice);

                if (products[i][5] === "-") {
                    customerInvoice.getCell('Y' + row).value = "-";
                } else {
                    if (products[i][4] === "-") {
                        if (products[i][5] === "" || products[i][5] === 0) {
                            customerInvoice.getCell('Y' + row).value = "-";
                        } else {
                            customerInvoice.getCell('Y' + row).value = products[i][5];
                        }
                    } else {
                        customerInvoice.getCell('Y' + row).value = { formula: `S${row}*W${row}`, result: 0 };
                    }
                }
                customerInvoice.getCell('Y' + row).alignment = { wrapText: true, horizontal: 'center', vertical: 'middle' };
                customerInvoice.getCell('Y' + row).font = { size: 12 };
                customerInvoice.getCell('Y' + row).border = {
                    top: { style: 'thin', color: { argb: 'FF000000' } },     // black
                    left: { style: 'thin', color: { argb: 'FF000000' } },
                    bottom: { style: 'thin', color: { argb: 'FF000000' } },
                    right: { style: 'thin', color: { argb: 'FF000000' } },
                };

                customerInvoice.getCell('Z' + row).value = products[i][6];
                customerInvoice.getCell('Z' + row).alignment = { wrapText: true, horizontal: 'center', vertical: 'middle' };
                customerInvoice.getCell('Z' + row).font = { size: 12 };
                customerInvoice.getCell('Z' + row).border = {
                    top: { style: 'thin', color: { argb: 'FF000000' } },     // black
                    left: { style: 'thin', color: { argb: 'FF000000' } },
                    bottom: { style: 'thin', color: { argb: 'FF000000' } },
                    right: { style: 'thin', color: { argb: 'FF000000' } },
                };
                customerInvoice.getCell('Z' + row).numFmt = '0.00';

                // customerInvoice.getCell('AA' + row).value = products[i][7];
                if (products[i][1] === "-") {
                    if (products[i][5] === "" || products[i][5] === 0) {
                        customerInvoice.getCell('AA' + row).value = { formula: `ROUND(S${row}*Z${row}, 2)`, result: 0 };
                    } else {
                        customerInvoice.getCell('AA' + row).value = { formula: `ROUND(Y${row}*Z${row}, 2)`, result: 0 };
                    }
                } else {
                    customerInvoice.getCell('AA' + row).value = { formula: `ROUND(Y${row}*Z${row}, 2)`, result: 0 };
                }
                customerInvoice.getCell('AA' + row).numFmt = '0.00';
                customerInvoice.getCell('AA' + row).alignment = { wrapText: true, horizontal: 'center', vertical: 'middle' };
                customerInvoice.getCell('AA' + row).font = { size: 12 };
                customerInvoice.getCell('AA' + row).border = {
                    top: { style: 'thin', color: { argb: 'FF000000' } },     // black
                    left: { style: 'thin', color: { argb: 'FF000000' } },
                    bottom: { style: 'thin', color: { argb: 'FF000000' } },
                    right: { style: 'thin', color: { argb: 'FF000000' } },
                };

            }
        }
        else {
            row++;
            if (products[i].length === 2) {
                customerInvoice.mergeCells('E' + row + ':Q' + row);
                customerInvoice.getCell('E' + row).value = products[i][0];
                // customerInvoice.getCell('E' + row).fill = {
                //     type: 'pattern',
                //     pattern: 'solid',
                //     fgColor: { argb: 'FFFFCC99' }, // Light orange / peach
                // };

                customerInvoice.getCell('E' + row).font = { bold: true, size: 12 };
                customerInvoice.getCell('E' + row).alignment = { horizontal: 'center', vertical: 'middle' };
                customerInvoice.getRow(row).height = 46;
                setOuterBorder('E' + row + ':Q' + row, customerInvoice);
                hsnCode = Number(products[i][1]);
                if (i == 0) {
                    allProductsType = String(products[i][0]);
                }
                else {
                    allProductsType += '/' + String(products[i][0]);
                }

                if (i !== 0) {
                    customerInvoice.getCell('A' + row).border = {
                        top: { style: 'thin', color: { argb: 'FF000000' } },     // black
                        left: { style: 'thin', color: { argb: 'FF000000' } },
                        bottom: { style: 'thin', color: { argb: 'FF000000' } },
                        right: { style: 'thin', color: { argb: 'FF000000' } },
                    };

                    setOuterBorder('B' + row + ':D' + row, customerInvoice);
                }
                setOuterBorder('E' + row + ':Q' + row, customerInvoice);

                setOuterBorder('R' + row + ':S' + row, customerInvoice);
                setOuterBorder('T' + row + ':U' + row, customerInvoice);
                setOuterBorder('V' + row + ':X' + row, customerInvoice);
                setOuterBorder('Y' + row + ':AA' + row, customerInvoice);

            } else {
                customerInvoice.getCell('A' + row).value = srNo;
                customerInvoice.getCell('A' + row).alignment = { wrapText: true, horizontal: 'center', vertical: 'middle' };
                customerInvoice.getCell('A' + row).border = {
                    top: { style: 'thin', color: { argb: 'FF000000' } },     // black
                    left: { style: 'thin', color: { argb: 'FF000000' } },
                    bottom: { style: 'thin', color: { argb: 'FF000000' } },
                    right: { style: 'thin', color: { argb: 'FF000000' } },
                };
                srNo++;

                customerInvoice.mergeCells('B' + row + ':D' + row);
                customerInvoice.getCell('B' + row).value = hsnCode;
                customerInvoice.getCell('B' + row).font = { bold: true };
                customerInvoice.getCell('B' + row).alignment = { wrapText: true, horizontal: 'center', vertical: 'middle' };
                setOuterBorder('B' + row + ':D' + row, customerInvoice);

                customerInvoice.mergeCells('E' + row + ':Q' + row);
                customerInvoice.getCell('E' + row).value = products[i][0];
                customerInvoice.getCell('E' + row).font = { size: 12 };
                customerInvoice.getCell('E' + row).alignment = { wrapText: true, horizontal: 'center', vertical: 'middle' };
                setOuterBorder('E' + row + ':Q' + row, customerInvoice);
                if (String(products[i][0]).length > 56) {
                    customerInvoice.getRow(row).height = 36;
                }

                customerInvoice.mergeCells('R' + row + ':S' + row);
                customerInvoice.getCell('R' + row).value = products[i][2];
                customerInvoice.getCell('R' + row).font = { size: 12 };
                customerInvoice.getCell('R' + row).alignment = { wrapText: true, horizontal: 'center', vertical: 'middle' };
                setOuterBorder('R' + row + ':S' + row, customerInvoice);

                customerInvoice.mergeCells('T' + row + ':U' + row);
                customerInvoice.getCell('T' + row).value = products[i][3];
                customerInvoice.getCell('T' + row).font = { size: 12 };
                customerInvoice.getCell('T' + row).alignment = { wrapText: true, horizontal: 'center', vertical: 'middle' };
                setOuterBorder('T' + row + ':U' + row, customerInvoice);

                customerInvoice.mergeCells('V' + row + ':X' + row);
                customerInvoice.getCell('V' + row).value = products[i][6];
                customerInvoice.getCell('V' + row).numFmt = '0.00';
                customerInvoice.getCell('V' + row).font = { size: 12 };
                customerInvoice.getCell('V' + row).alignment = { wrapText: true, horizontal: 'center', vertical: 'middle' };
                setOuterBorder('V' + row + ':X' + row, customerInvoice);

                customerInvoice.mergeCells('Y' + row + ':AA' + row);
                // customerInvoice.getCell('Y' + row).value = products[i][7];
                customerInvoice.getCell('Y' + row).value = { formula: `ROUND(R${row}*V${row}, 2)`, result: 0 };
                customerInvoice.getCell('Y' + row).numFmt = '0.00';
                customerInvoice.getCell('Y' + row).font = { size: 12 };
                customerInvoice.getCell('Y' + row).alignment = { wrapText: true, horizontal: 'center', vertical: 'middle' };
                setOuterBorder('Y' + row + ':AA' + row, customerInvoice);
            }
        }
    }

    row++;
    customerInvoice.mergeCells('A' + row + ':D' + (row + 3));
    setOuterBorder('A' + row + ':D' + (row + 3), customerInvoice);

    skipRow = 2;
    addSkipRow = 3;
    if (taxStatus == "with") {
        skipRow = 2;
        addSkipRow = 3;
    }
    if (type !== "tiles") {
        for (let i = 0; i < skipRow; i++) {
            setOuterBorder('E' + row + ':Q' + row, customerInvoice);

            customerInvoice.getCell('R' + row).border = {
                top: { style: 'thin', color: { argb: 'FF000000' } },     // black
                left: { style: 'thin', color: { argb: 'FF000000' } },
                bottom: { style: 'thin', color: { argb: 'FF000000' } },
                right: { style: 'thin', color: { argb: 'FF000000' } },
            };

            setOuterBorder('S' + row + ':T' + row, customerInvoice);
            setOuterBorder('U' + row + ':V' + row, customerInvoice);
            setOuterBorder('W' + row + ':X' + row, customerInvoice);

            customerInvoice.getCell('Y' + row).border = {
                top: { style: 'thin', color: { argb: 'FF000000' } },     // black
                left: { style: 'thin', color: { argb: 'FF000000' } },
                bottom: { style: 'thin', color: { argb: 'FF000000' } },
                right: { style: 'thin', color: { argb: 'FF000000' } },
            };

            customerInvoice.getCell('Z' + row).border = {
                top: { style: 'thin', color: { argb: 'FF000000' } },     // black
                left: { style: 'thin', color: { argb: 'FF000000' } },
                bottom: { style: 'thin', color: { argb: 'FF000000' } },
                right: { style: 'thin', color: { argb: 'FF000000' } },
            };

            customerInvoice.getCell('AA' + row).border = {
                top: { style: 'thin', color: { argb: 'FF000000' } },     // black
                left: { style: 'thin', color: { argb: 'FF000000' } },
                bottom: { style: 'thin', color: { argb: 'FF000000' } },
                right: { style: 'thin', color: { argb: 'FF000000' } },
            };
            row++;
        }

        customerInvoice.mergeCells('R' + row + ':R' + (row + addSkipRow));
        setOuterBorder('R' + row + ':R' + (row + addSkipRow), customerInvoice);
        customerInvoice.mergeCells('S' + row + ':T' + (row + addSkipRow));
        setOuterBorder('S' + row + ':T' + (row + addSkipRow), customerInvoice);
        customerInvoice.mergeCells('U' + row + ':V' + (row + addSkipRow));
        setOuterBorder('U' + row + ':V' + (row + addSkipRow), customerInvoice);
        customerInvoice.mergeCells('W' + row + ':X' + (row + addSkipRow));
        setOuterBorder('W' + row + ':X' + (row + addSkipRow), customerInvoice);
        customerInvoice.mergeCells('Y' + row + ':Y' + (row + addSkipRow));
        setOuterBorder('Y' + row + ':Y' + (row + addSkipRow), customerInvoice);
        customerInvoice.mergeCells('Z' + row + ':Z' + (row + addSkipRow));
        setOuterBorder('Z' + row + ':Z' + (row + addSkipRow), customerInvoice);
        customerInvoice.mergeCells('AA' + row + ':AA' + (row + addSkipRow));
        setOuterBorder('AA' + row + ':AA' + (row + addSkipRow), customerInvoice);
    }
    else {
        for (let i = 0; i < skipRow; i++) {
            setOuterBorder('E' + row + ':Q' + row, customerInvoice);

            setOuterBorder('R' + row + ':S' + row, customerInvoice);
            setOuterBorder('T' + row + ':U' + row, customerInvoice);
            setOuterBorder('V' + row + ':X' + row, customerInvoice);
            setOuterBorder('Y' + row + ':AA' + row, customerInvoice);
            row++;
        }

        customerInvoice.mergeCells('R' + row + ':S' + (row + addSkipRow));
        setOuterBorder('R' + row + ':S' + (row + addSkipRow), customerInvoice);
        customerInvoice.mergeCells('T' + row + ':U' + (row + addSkipRow));
        setOuterBorder('T' + row + ':U' + (row + addSkipRow), customerInvoice);
        customerInvoice.mergeCells('V' + row + ':X' + (row + addSkipRow));
        setOuterBorder('V' + row + ':X' + (row + addSkipRow), customerInvoice);
        customerInvoice.mergeCells('Y' + row + ':AA' + (row + addSkipRow));
        setOuterBorder('Y' + row + ':AA' + (row + addSkipRow), customerInvoice);
    }

    if (taxStatus == "with") {
        // customerInvoice.mergeCells('E' + row + ':Q' + row);
        //   customerInvoice.getCell('E' + row).value = "CERTIFIED THAT GOODS ARE OF INDIAN ORIGIN";
        //   customerInvoice.getCell('E' + row).font = { name: 'Arial' };
        //   customerInvoice.getCell('E' + row).alignment = { horizontal: 'center' };
        // setOuterBorder('E' + row + ':Q' + row, customerInvoice);
        // row++;
    }

    // customerInvoice.mergeCells('E' + row + ':Q' + row);
    // customerInvoice.getCell('E' + row).value = "Export Under Duty Drawback Scheme";
    // customerInvoice.getCell('E' + row).font = { bold: true };
    // customerInvoice.getCell('E' + row).alignment = { horizontal: 'center' };
    // setOuterBorder('E' + row + ':Q' + row, customerInvoice);
    // row++;

    // customerInvoice.mergeCells('E' + row + ':Q' + (row + 1));
    // customerInvoice.getCell('E' + row).value = "I/we shall claim under chapter 3 incentive of FTP as admissible at time policy in force - MEIS, RODTEP ";
    // customerInvoice.getCell('E' + row).font = { bold: true };
    // customerInvoice.getCell('E' + row).alignment = { wrapText: true, horizontal: 'center' };
    // setOuterBorder('E' + row + ':Q' + (row + 1), customerInvoice);
    // row += 2;

    customerInvoice.mergeCells('E' + row + ':Q' + (row + 1));
    setOuterBorder('E' + row + ':Q' + (row + 1), customerInvoice);
    row += 2;

    if (type !== 'tiles') {
        customerInvoice.mergeCells('A' + row + ':E' + row);
        customerInvoice.getCell('A' + row).value = "NET WT. (KGS): ";
        customerInvoice.getCell('A' + row).font = { underline: true };
        customerInvoice.getCell('A' + row).alignment = { horizontal: 'right' };
        setOuterBorder('A' + row + ':E' + row, customerInvoice);

        customerInvoice.mergeCells('F' + row + ':H' + row);
        customerInvoice.getCell('F' + row).value = netWeight;
        customerInvoice.getCell('F' + row).numFmt = '0.00';
        // customerInvoice.getCell('F' + row).fill = {
        //     type: 'pattern',
        //     pattern: 'solid',
        //     fgColor: { argb: 'FFFFFF00' },
        // };
        customerInvoice.getCell('F' + row).font = { bold: true, underline: true };
        customerInvoice.getCell('F' + row).alignment = { horizontal: 'left' };
        setOuterBorder('F' + row + ':H' + row, customerInvoice);

        customerInvoice.mergeCells('I' + row + ':Q' + row);
        setOuterBorder('I' + row + ':Q' + row, customerInvoice);
        row++;

        customerInvoice.mergeCells('A' + row + ':E' + row);
        customerInvoice.getCell('A' + row).value = "GROSS WT.(KGS): ";
        customerInvoice.getCell('A' + row).font = { underline: true };
        customerInvoice.getCell('A' + row).alignment = { horizontal: 'right' };
        setOuterBorder('A' + row + ':E' + row, customerInvoice);

        customerInvoice.mergeCells('F' + row + ':H' + row);
        customerInvoice.getCell('F' + row).value = grossWeight;
        customerInvoice.getCell('F' + row).numFmt = '0.00';
        // customerInvoice.getCell('F' + row).fill = {
        //     type: 'pattern',
        //     pattern: 'solid',
        //     fgColor: { argb: 'FFFFFF00' },
        // };
        customerInvoice.getCell('F' + row).font = { bold: true, underline: true };
        customerInvoice.getCell('F' + row).alignment = { horizontal: 'left' };
        setOuterBorder('F' + row + ':H' + row, customerInvoice);

        customerInvoice.mergeCells('I' + row + ':Q' + row);
        setOuterBorder('I' + row + ':Q' + row, customerInvoice);
        row++;
    } else {
        customerInvoice.mergeCells('A' + row + ':D' + row);
        customerInvoice.getCell('A' + row).value = "NET WT. (KGS): ";
        customerInvoice.getCell('A' + row).font = { underline: true };
        customerInvoice.getCell('A' + row).alignment = { horizontal: 'right' };
        setOuterBorder('A' + row + ':D' + row, customerInvoice);

        customerInvoice.mergeCells('E' + row + ':G' + row);
        customerInvoice.getCell('E' + row).value = netWeight;
        customerInvoice.getCell('E' + row).numFmt = '0.00';
        // customerInvoice.getCell('E' + row).fill = {
        //     type: 'pattern',
        //     pattern: 'solid',
        //     fgColor: { argb: 'FFFFFF00' },
        // };
        customerInvoice.getCell('E' + row).font = { bold: true, underline: true };
        customerInvoice.getCell('E' + row).alignment = { horizontal: 'left' };
        setOuterBorder('E' + row + ':G' + row, customerInvoice);

        customerInvoice.mergeCells('H' + row + ':Q' + row);
        setOuterBorder('H' + row + ':Q' + row, customerInvoice);
        row++;

        customerInvoice.mergeCells('A' + row + ':D' + row);
        customerInvoice.getCell('A' + row).value = "GROSS WT.(KGS): ";
        customerInvoice.getCell('A' + row).font = { underline: true };
        customerInvoice.getCell('A' + row).alignment = { horizontal: 'right' };
        setOuterBorder('A' + row + ':D' + row, customerInvoice);

        customerInvoice.mergeCells('E' + row + ':G' + row);
        customerInvoice.getCell('E' + row).value = grossWeight;
        customerInvoice.getCell('E' + row).numFmt = '0.00';
        // customerInvoice.getCell('E' + row).fill = {
        //     type: 'pattern',
        //     pattern: 'solid',
        //     fgColor: { argb: 'FFFFFF00' },
        // };
        customerInvoice.getCell('E' + row).font = { bold: true, underline: true };
        customerInvoice.getCell('E' + row).alignment = { horizontal: 'left' };
        setOuterBorder('E' + row + ':G' + row, customerInvoice);

        customerInvoice.mergeCells('H' + row + ':Q' + row);
        setOuterBorder('H' + row + ':Q' + row, customerInvoice);
        row++;
    }

    customerInvoice.mergeCells('A' + row + ':G' + row);
    customerInvoice.getCell('A' + row).value = "Nos. of Kind Packages";
    customerInvoice.getCell('A' + row).font = { bold: true };
    customerInvoice.getCell('A' + row).alignment = { horizontal: 'center' };

    customerInvoice.mergeCells('H' + row + ':Q' + (row + 1));
    customerInvoice.getCell('H' + row).value = "Total     >>>>>>>>>>";
    customerInvoice.getCell('H' + row).font = { bold: true };
    customerInvoice.getCell('H' + row).alignment = { horizontal: 'center', vertical: 'middle' };
    setOuterBorder('H' + row + ':Q' + (row + 1), customerInvoice);

    if (type !== "tiles") {
        setOuterBorder('R' + row + ':R' + (row + 1), customerInvoice);

        customerInvoice.mergeCells('S' + row + ':T' + row);
        customerInvoice.getCell('S' + row).value = { formula: `SUM(S30:S${row - 1})`, result: 0 };
        ;
        customerInvoice.getCell('S' + row).font = { bold: true };
        customerInvoice.getCell('S' + row).alignment = { horizontal: 'center' };

        setOuterBorder('U' + row + ':V' + (row + 1), customerInvoice);

        customerInvoice.mergeCells('W' + row + ':Y' + row);
        customerInvoice.getCell('W' + row).value = `TOTAL SQM`;
        customerInvoice.getCell('W' + row).font = { bold: true };
        customerInvoice.getCell('W' + row).alignment = { horizontal: 'center' };

        customerInvoice.mergeCells('W' + (row + 1) + ':Y' + (row + 1));
        customerInvoice.getCell('W' + (row + 1)).value = { formula: `SUM(Y30:Y${row - 1})`, result: 0 };
        ;
        customerInvoice.getCell('W' + (row + 1)).font = { bold: true };
        customerInvoice.getCell('W' + (row + 1)).alignment = { horizontal: 'center' };
        setOuterBorder('W' + row + ':Y' + (row + 1), customerInvoice);

        customerInvoice.mergeCells('Z' + row + ':Z' + (row + 1));
        if (termsOfDeliveryMain === "CIF -> FOB") {
            customerInvoice.getCell('Z' + row).value = `CIF ${currency}`;
            // } else if (termsOfDeliveryMain === "CNF") {
            //     customerInvoice.getCell('Z' + row).value = `TOTAL ${termsOfDelivery} ${currency}`;
        } else {
            customerInvoice.getCell('Z' + row).value = `${termsOfDelivery} ${currency}`;
        }
        customerInvoice.getCell('Z' + row).font = { bold: true };
        customerInvoice.getCell('Z' + row).alignment = { wrapText: true, horizontal: 'center', vertical: 'middle' };
        setOuterBorder('Z' + row + ':Z' + (row + 1), customerInvoice);

        customerInvoice.mergeCells('AA' + row + ':AA' + (row + 1));
        if (termsOfDeliveryMain === "CIF -> FOB") {
            customerInvoice.getCell('AA' + row).value = { formula: `ROUND(SUM(AA${row + 2}:AA${row + 4}), 2)`, result: 0 };
        } else {
            customerInvoice.getCell('AA' + row).value = { formula: `ROUND(SUM(AA28:AA${row - 1}), 2)`, result: 0 };
        }        // customerInvoice.getCell('AA' + row).value = {
        //   formula: `SUM(AA30:AA${row-1})`,
        //   result: 0, // optional static value
        // };
        customerInvoice.getCell('AA' + row).font = { bold: true };
        customerInvoice.getCell('AA' + row).alignment = { horizontal: 'center', vertical: 'middle' };
        setOuterBorder('AA' + row + ':AA' + (row + 1), customerInvoice);
    }
    else {
        customerInvoice.mergeCells('R' + row + ':S' + row);
        customerInvoice.getCell('R' + row).value = { formula: `ROUND(SUM(R30:R${row - 1}), 2)`, result: 0 };
        customerInvoice.getCell('R' + row).font = { bold: true };
        customerInvoice.getCell('R' + row).alignment = { horizontal: 'center' };

        customerInvoice.mergeCells('T' + row + ':U' + row);
        customerInvoice.getCell('T' + row).value = "UNIT TYPE";
        customerInvoice.getCell('T' + row).font = { bold: true };
        customerInvoice.getCell('T' + row).alignment = { horizontal: 'center', vertical: 'middle' };
        setOuterBorder('T' + row + ':U' + row, customerInvoice);

        customerInvoice.mergeCells('T' + (row + 1) + ':U' + (row + 1));
        customerInvoice.getCell('T' + (row + 1)).value = packegingType;
        customerInvoice.getCell('T' + (row + 1)).font = { bold: true };
        customerInvoice.getCell('T' + (row + 1)).alignment = { horizontal: 'center', vertical: 'middle' };
        setOuterBorder('T' + (row + 1) + ':U' + (row + 1), customerInvoice);

        customerInvoice.mergeCells('V' + row + ':X' + (row + 1));
        if (termsOfDeliveryMain === "CIF -> FOB") {
            customerInvoice.getCell('V' + row).value = `CIF ${currency}`;
            // } else if (termsOfDeliveryMain === "CNF") {
            //     customerInvoice.getCell('V' + row).value = `TOTAL ${termsOfDelivery} ${currency}`;
        } else {
            customerInvoice.getCell('V' + row).value = `${termsOfDelivery} ${currency}`;
        }
        customerInvoice.getCell('V' + row).font = { bold: true };
        customerInvoice.getCell('V' + row).alignment = { horizontal: 'center', vertical: 'middle' };
        setOuterBorder('V' + row + ':X' + (row + 1), customerInvoice);



        customerInvoice.mergeCells('Y' + row + ':AA' + (row + 1));
        if (termsOfDeliveryMain === "CIF -> FOB") {
            customerInvoice.getCell('Y' + row).value = { formula: `ROUND(SUM(Y${row + 2}:Y${row + 4}), 2)`, result: 0 };
        } else {
            customerInvoice.getCell('Y' + row).value = { formula: `ROUND(SUM(Y30:Y${row - 1}), 2)`, result: 0 };
        }
        customerInvoice.getCell('Y' + row).font = { bold: true };
        customerInvoice.getCell('Y' + row).alignment = { horizontal: 'center', vertical: 'middle' };
        setOuterBorder('Y' + row + ':AA' + (row + 1), customerInvoice);
    }
    row++;

    customerInvoice.mergeCells('A' + row + ':G' + row);
    if (type !== "tiles") {
        customerInvoice.getCell('A' + row).value = { formula: `INT(SUM(S30:S${row - 2})) & " ${unitOfIt}"`, result: `0${unitOfIt}`, };
    }
    else {
        customerInvoice.getCell('A' + row).value = { formula: `INT(SUM(R30:R${row - 2})) & " ${unitOfIt}"`, result: `0${unitOfIt}`, };
    }
    customerInvoice.getCell('A' + row).font = { bold: true };
    customerInvoice.getCell('A' + row).alignment = { horizontal: 'center' };
    setOuterBorder('A' + (row - 1) + ':G' + row, customerInvoice);

    if (type !== "tiles") {
        customerInvoice.mergeCells('S' + row + ':T' + row);
        customerInvoice.getCell('S' + row).value = unitOfIt;
        customerInvoice.getCell('S' + row).font = { bold: true };
        customerInvoice.getCell('S' + row).alignment = { horizontal: 'center' };
        setOuterBorder('S' + (row - 1) + ':T' + row, customerInvoice);
    }
    else {
        customerInvoice.mergeCells('R' + row + ':S' + row);
        customerInvoice.getCell('R' + row).value = unitOfIt;
        customerInvoice.getCell('R' + row).font = { bold: true };
        customerInvoice.getCell('R' + row).alignment = { horizontal: 'center' };
        setOuterBorder('R' + (row - 1) + ':S' + row, customerInvoice);
    }
    row++;

    customerInvoice.mergeCells('A' + row + ':Q' + row);
    customerInvoice.getCell('A' + row).value = `TOTAL ${termsOfDelivery} ${currency}:`;
    customerInvoice.getCell('A' + row).font = { bold: true };
    customerInvoice.getCell('A' + row).alignment = { horizontal: 'left' };
    setOuterBorder('A' + row + ':Q' + row, customerInvoice);

    if (type === "sanitary" && termsOfDelivery === "CIF") {
        setOuterBorder('R' + row + ':R' + row, customerInvoice);
        setOuterBorder('S' + row + ':Y' + row, customerInvoice);

        customerInvoice.mergeCells('Z' + row + ':Z' + row);
        customerInvoice.getCell('Z' + row).value = "INSURANCE";
        customerInvoice.getCell('Z' + row).font = { bold: true };
        customerInvoice.getCell('Z' + row).alignment = { horizontal: 'center' };
        setOuterBorder('Z' + row + ':Z' + row, customerInvoice);

        customerInvoice.mergeCells('AA' + row + ':AA' + row);
        customerInvoice.getCell('AA' + row).value = insurance;
        customerInvoice.getCell('AA' + row).font = { bold: true };
        customerInvoice.getCell('AA' + row).alignment = { horizontal: 'center' };
        setOuterBorder('AA' + row + ':AA' + row, customerInvoice);
    }
    else if (type === "tiles" && termsOfDelivery === "CIF") {
        customerInvoice.mergeCells('R' + row + ':X' + row);
        customerInvoice.getCell('R' + row).value = "INSURANCE";
        customerInvoice.getCell('R' + row).font = { bold: true };
        customerInvoice.getCell('R' + row).alignment = { horizontal: 'right' };
        setOuterBorder('R' + row + ':X' + row, customerInvoice);

        customerInvoice.mergeCells('Y' + row + ':AA' + row);
        customerInvoice.getCell('Y' + row).value = insurance;
        customerInvoice.getCell('Y' + row).font = { bold: true };
        customerInvoice.getCell('Y' + row).alignment = { horizontal: 'center' };
        setOuterBorder('Y' + row + ':AA' + row, customerInvoice);
    } else if (type === "sanitary") {
        setOuterBorder('R' + row + ':R' + row, customerInvoice);
        setOuterBorder('S' + row + ':Y' + row, customerInvoice);

        customerInvoice.mergeCells('Z' + row + ':Z' + row);
        setOuterBorder('Z' + row + ':Z' + row, customerInvoice);

        customerInvoice.mergeCells('AA' + row + ':AA' + row);
        setOuterBorder('AA' + row + ':AA' + row, customerInvoice);
    } else if (type === "tiles") {
        customerInvoice.mergeCells('R' + row + ':X' + row);
        setOuterBorder('R' + row + ':X' + row, customerInvoice);

        customerInvoice.mergeCells('Y' + row + ':AA' + row);
        setOuterBorder('Y' + row + ':AA' + row, customerInvoice);
    }
    row++;

    customerInvoice.mergeCells('A' + row + ':Q' + (row + 1));
    customerInvoice.getCell('A' + row).value = `${amountInWords}.`;
    // customerInvoice.getCell('A' + row).fill = {
    //     type: 'pattern',
    //     pattern: 'solid',
    //     fgColor: { argb: 'FFFFFF00' },
    // };

    customerInvoice.getCell('A' + row).font = { bold: true };
    customerInvoice.getCell('A' + row).alignment = { horizontal: 'left', vertical: 'top' };
    setOuterBorder('A' + row + ':Q' + (row + 1), customerInvoice);

    if (type === "sanitary") {
        customerInvoice.getCell('R' + row).border = {
            top: { style: 'thin', color: { argb: 'FF000000' } },     // black
            left: { style: 'thin', color: { argb: 'FF000000' } },
            bottom: { style: 'thin', color: { argb: 'FF000000' } },
            right: { style: 'thin', color: { argb: 'FF000000' } },
        };

        customerInvoice.getCell('R' + (row + 1)).border = {
            top: { style: 'thin', color: { argb: 'FF000000' } },     // black
            left: { style: 'thin', color: { argb: 'FF000000' } },
            bottom: { style: 'thin', color: { argb: 'FF000000' } },
            right: { style: 'thin', color: { argb: 'FF000000' } },
        };
    }

    setOuterBorder('S' + row + ':Y' + row, customerInvoice);

    if (type === "sanitary" && termsOfDelivery !== "FOB") {
        customerInvoice.mergeCells('Z' + row + ':Z' + row);
        customerInvoice.getCell('Z' + row).value = "FREIGHT";
        customerInvoice.getCell('Z' + row).font = { bold: true };
        customerInvoice.getCell('Z' + row).alignment = { horizontal: 'center' };
        setOuterBorder('Z' + row + ':Z' + row, customerInvoice);

        customerInvoice.mergeCells('AA' + row + ':AA' + row);
        customerInvoice.getCell('AA' + row).value = freight;
        customerInvoice.getCell('AA' + row).font = { bold: true };
        customerInvoice.getCell('AA' + row).alignment = { horizontal: 'center' };
        setOuterBorder('AA' + row + ':AA' + row, customerInvoice);
    }
    else if (type === "tiles" && termsOfDelivery !== "FOB") {
        customerInvoice.mergeCells('R' + row + ':X' + row);
        customerInvoice.getCell('R' + row).value = "FREIGHT";
        customerInvoice.getCell('R' + row).font = { bold: true };
        customerInvoice.getCell('R' + row).alignment = { horizontal: 'right' };
        setOuterBorder('R' + row + ':X' + row, customerInvoice);

        customerInvoice.mergeCells('Y' + row + ':AA' + row);
        customerInvoice.getCell('Y' + row).value = freight;
        customerInvoice.getCell('Y' + row).font = { bold: true };
        customerInvoice.getCell('Y' + row).alignment = { horizontal: 'center' };
        setOuterBorder('Y' + row + ':AA' + row, customerInvoice);
    } else if (type === "sanitary") {
        customerInvoice.mergeCells('Z' + row + ':Z' + row);
        setOuterBorder('Z' + row + ':Z' + row, customerInvoice);

        customerInvoice.mergeCells('AA' + row + ':AA' + row);
        setOuterBorder('AA' + row + ':AA' + row, customerInvoice);
    }
    else if (type === "tiles") {
        customerInvoice.mergeCells('R' + row + ':X' + row);
        setOuterBorder('R' + row + ':X' + row, customerInvoice);

        customerInvoice.mergeCells('Y' + row + ':AA' + row);
        setOuterBorder('Y' + row + ':AA' + row, customerInvoice);
    }
    row++;

    if (type === "sanitary") {
        customerInvoice.mergeCells('S' + row + ':Y' + row);
        if (termsOfDeliveryMain === "CIF -> FOB") {
            customerInvoice.getCell('S' + row).value = `TOTAL FOB ${currency}`;
        } else {
            customerInvoice.getCell('S' + row).value = `TOTAL ${termsOfDelivery} ${currency}`;
        }
        customerInvoice.getCell('S' + row).font = { bold: true };
        customerInvoice.getCell('S' + row).alignment = { horizontal: 'right' };
        setOuterBorder('S' + row + ':Y' + row, customerInvoice);

        if (termsOfDeliveryMain === "CIF -> FOB" || termsOfDeliveryMain === "FOB") {
            customerInvoice.getCell('AA' + row).value = { formula: `ROUND(SUM(AA28:AA${row - 5}), 4)`, result: 0 };
        } else {
            customerInvoice.getCell('AA' + row).value = { formula: `ROUND(SUM(AA${row - 5}:AA${row - 1}), 4)`, result: 0 };
        }
        customerInvoice.getCell('AA' + row).font = { bold: true };
        customerInvoice.getCell('AA' + row).alignment = { horizontal: 'center' };
        customerInvoice.getCell('AA' + row).border = {
            top: { style: 'thin', color: { argb: 'FF000000' } },     // black
            left: { style: 'thin', color: { argb: 'FF000000' } },
            bottom: { style: 'thin', color: { argb: 'FF000000' } },
            right: { style: 'thin', color: { argb: 'FF000000' } },
        };

    }
    else if (type === "tiles") {
        customerInvoice.mergeCells('R' + row + ':X' + row);
        if (termsOfDeliveryMain === "CIF -> FOB") {
            customerInvoice.getCell('R' + row).value = `TOTAL FOB ${currency}`;
        } else {
            customerInvoice.getCell('R' + row).value = `TOTAL ${termsOfDelivery} ${currency}`;
        }
        customerInvoice.getCell('R' + row).font = { bold: true };
        customerInvoice.getCell('R' + row).alignment = { horizontal: 'right' };
        setOuterBorder('R' + row + ':X' + row, customerInvoice);

        customerInvoice.mergeCells('Y' + row + ':AA' + row);
        // customerInvoice.getCell('Y' + row).value = totalFOBEuro;
        if (termsOfDeliveryMain === "CIF -> FOB" || termsOfDeliveryMain === "FOB") {
            customerInvoice.getCell('Y' + row).value = { formula: `ROUND(SUM(Y28:Y${row - 5}), 4)`, result: 0 };
        } else {
            customerInvoice.getCell('Y' + row).value = { formula: `ROUND(SUM(Y${row - 5}:Y${row - 1}), 4)`, result: 0 };
        }

        customerInvoice.getCell('Y' + row).font = { bold: true };
        customerInvoice.getCell('Y' + row).alignment = { horizontal: 'center' };
        setOuterBorder('Y' + row + ':AA' + row, customerInvoice);

    }

    customerInvoice.getCell('R' + (row + 1)).border = {
        top: { style: 'thin', color: { argb: 'FF000000' } },     // black
        left: { style: 'thin', color: { argb: 'FF000000' } },
        bottom: { style: 'thin', color: { argb: 'FF000000' } },
        right: { style: 'thin', color: { argb: 'FF000000' } },
    };

    row++;

    customerInvoice.mergeCells('A' + row + ':AA' + row);
    customerInvoice.getCell('A' + row).value = "CERTIFIED THAT GOODS ARE OF INDIAN ORIGIN";
    customerInvoice.getCell('A' + row).font = { bold: true };
    customerInvoice.getCell('A' + row).alignment = { horizontal: 'left' };
    setOuterBorder('A' + row + ':AA' + row, customerInvoice);
    row++;

    // customerInvoice.mergeCells('A' + row + ':AA' + (row + 1));
    // if (taxStatus === "without") {
    //   customerInvoice.getCell('A' + row).value = `LETTER OF UNDERTAKING NO.ACKNOWLEDGMENT FOR LUT  APPLICATION REFERENCE NUMBER (ARN) ${arn}\nDT:${lutDate}`;
    // } else {
    //   customerInvoice.getCell('A' + row).value = `SUPPLY MEANT FOR EXPORT ON PAYMENT OF IGST UNDER CLAIM OF REFUND RS. TOTAL : ${gstValue}\n(TAXABLE ${termsOfDelivery} INR VALUE ${totalInINR}@ 18%)                                                                            ${gstValue}  `;
    // }
    // customerInvoice.getCell('A' + row).font = { name: 'Arial', italic: true, color: { argb: 'FFFF0000' } };
    // customerInvoice.getCell('A' + row).alignment = { wrapText: true, horizontal: 'left', vertical: 'top' };
    // setOuterBorder('A' + row + ':AA' + (row + 1), customerInvoice);
    // row += 2;

    if (taxStatus === "with") {
        for (let i = 0; i < 4; i++) {
            customerInvoice.getCell('A' + (row + i)).border = {
                left: { style: 'thin', color: { argb: 'FF000000' } },
            }
        }
    }


    // if (supplierDetails.length % 2 === 0 || supplierDetails.length == 0) {
    if (type == "tiles") {
        customerInvoice.mergeCells('A' + row + ':M' + (row + 6));
        customerInvoice.getCell('A' + row).value = "Exporter Bank Details:\nBENEFICIARY NAME: ZERIC CERAMICA\nBANK NAME: HDFC BANK\nACCOUNT NUMBER: 50200052577831\nSWIFT CODE: HDFCINBBXXX\nIFSC CODE: HDFC0002499\nTAX ID: 24AACFZ6694H1ZP";
        customerInvoice.getCell('A' + row).font = { bold: true };
        customerInvoice.getCell('A' + row).alignment = { wrapText: true, horizontal: 'left' };
        setOuterBorder('A' + row + ':M' + (row + 6), customerInvoice);
    } else {
        customerInvoice.mergeCells('A' + row + ':Q' + (row + 6));
        customerInvoice.getCell('A' + row).value = "Exporter Bank Details:\nBENEFICIARY NAME: ZERIC CERAMICA\nBANK NAME: HDFC BANK\nACCOUNT NUMBER: 50200052577831\nSWIFT CODE: HDFCINBBXXX\nIFSC CODE: HDFC0002499\nTAX ID: 24AACFZ6694H1ZP";
        customerInvoice.getCell('A' + row).font = { bold: true };
        customerInvoice.getCell('A' + row).alignment = { wrapText: true, horizontal: 'left' };
        setOuterBorder('A' + row + ':Q' + (row + 6), customerInvoice);
    }
    // }


    if (type === "sanitary") {
        customerInvoice.mergeCells('R' + row + ':AA' + row);
        customerInvoice.getCell('R' + row).value = "Signature & Date";
        customerInvoice.getCell('R' + row).font = { bold: true };
        customerInvoice.getCell('R' + row).alignment = { horizontal: 'right' };
        row++;

        customerInvoice.mergeCells('R' + row + ':AA' + row);
        customerInvoice.getCell('R' + row).value = "For, ZERIC CERAMICA";
        customerInvoice.getCell('R' + row).font = { bold: true };
        customerInvoice.getCell('R' + row).alignment = { horizontal: 'right' };

        customerInvoice.addImage(signature, {
            tl: { col: 24, row: (row) }, // X66 (X = col 24 → 24 - 1 = 23 → 22 for 0-based)
            ext: { width: 100, height: 100 }, // adjust size as needed
        });
        row += 7;

        customerInvoice.mergeCells('R' + row + ':AA' + row);
        customerInvoice.getCell('R' + row).value = "AUTHORISED SIGN.";
        customerInvoice.getCell('R' + row).font = { bold: true };
        customerInvoice.getCell('R' + row).alignment = { horizontal: 'right' };
        setOuterBorder('R' + (row - 8) + ':AA' + row, customerInvoice);


        customerInvoice.mergeCells('A' + (row - 1) + ':Q' + row);
        customerInvoice.getCell('A' + (row - 1)).value = "Declaration:We declare that this invoice shows the actual price of the goods described and that all particulars are true and correct.";
        customerInvoice.getCell('A' + (row - 1)).font = { bold: true };
        customerInvoice.getCell('A' + (row - 1)).alignment = { wrapText: true, horizontal: 'left', vertical: 'top' };
        setOuterBorder('A' + (row - 1) + ':Q' + row, customerInvoice);
        setOuterBorder('A' + (row - 2) + ':Q' + (row - 2), customerInvoice);
    }
    else if (type === "tiles") {
        customerInvoice.mergeCells('N' + row + ':AA' + row);
        customerInvoice.getCell('N' + row).value = "Signature & Date";
        customerInvoice.getCell('N' + row).font = { bold: true };
        customerInvoice.getCell('N' + row).alignment = { horizontal: 'right' };
        row++;

        customerInvoice.mergeCells('N' + row + ':AA' + row);
        customerInvoice.getCell('N' + row).value = "For, ZERIC CERAMICA";
        customerInvoice.getCell('N' + row).font = { bold: true };
        customerInvoice.getCell('N' + row).alignment = { horizontal: 'right' };

        customerInvoice.addImage(signature, {
            tl: { col: 20, row: (row) }, // X66 (X = col 24 → 24 - 1 = 23 → 22 for 0-based)
            ext: { width: 100, height: 100 }, // adjust size as needed
        });
        row += 7;

        customerInvoice.mergeCells('N' + row + ':AA' + row);
        customerInvoice.getCell('N' + row).value = "AUTHORISED SIGN.";
        customerInvoice.getCell('N' + row).font = { bold: true };
        customerInvoice.getCell('N' + row).alignment = { horizontal: 'right' };
        setOuterBorder('N' + (row - 8) + ':AA' + row, customerInvoice);


        customerInvoice.mergeCells('A' + (row - 1) + ':M' + row);
        customerInvoice.getCell('A' + (row - 1)).value = "Declaration:We declare that this invoice shows the actual price of the goods described and that all particulars are true and correct.";
        customerInvoice.getCell('A' + (row - 1)).font = { bold: true };
        customerInvoice.getCell('A' + (row - 1)).alignment = { wrapText: true, horizontal: 'left', vertical: 'top' };
        setOuterBorder('A' + (row - 1) + ':M' + row, customerInvoice);
        setOuterBorder('A' + (row - 2) + ':M' + (row - 2), customerInvoice);
    }

    setOuterBorder('A1:AA' + row, customerInvoice, 'medium');

    customerInvoice.pageSetup.fitToPage = true;

    MAX_WIDTH = 5;
    if (type === "tiles") {

        customerInvoice.columns.forEach((column) => {
            let maxLength = 10;

            column.eachCell({ includeEmpty: true }, (cell) => {
                const cellValue = cell.value ? cell.value.toString() : '';
                const lines = cellValue.split('\n');
                const longestLine = Math.max(...lines.map(line => line.length));
                if (longestLine > maxLength) {
                    maxLength = longestLine;
                }
            });

            column.width = Math.min(maxLength + 2, MAX_WIDTH); // 👈 LIMIT IT
        });
        customerInvoice.getColumn(1).width = pixelToExcelWidth(50);
    }
    else if (type === "sanitary") {
        columnWidths.forEach((px, index) => {
            customerInvoice.getColumn(index + 1).width = pixelToExcelWidth(px);
        });
    }
    customerInvoice.getColumn(17).width = 0;

    setGlobalFontSize(customerInvoice);





































































    // The sheet comes off the workbook rather than the local binding: in some
    // sections that binding is declared inside a conditional and is not in
    // scope here. It is the same object either way.
    return {
        workbook: customerInvoiceWorkbook,
        sheet: customerInvoiceWorkbook.worksheets[0],
        state: { ...state, srNo, row, hsnCode, allProductsType, skipRow, addSkipRow, MAX_WIDTH },
        built: {
            ...built,
            customerInvoiceWorkbook: customerInvoiceWorkbook,
            customerInvoice: customerInvoiceWorkbook.worksheets[0]
        }
    }
}
