/* eslint-disable */
// @ts-nocheck
// GENERATED by scripts/split-generator.mjs from ui/src/lib/excelGenerator.ts.
// The body below is a verbatim copy. Do not edit or reformat it by hand —
// re-run `npm run docs:split` instead. The original was written with
// TypeScript strictness disabled, so it is excluded from type checking;
// correctness is established by scripts/compare-generators.mts, which diffs
// every cell against the original generator.
// Source lines 379-2275.

import ExcelJS from 'exceljs'
import { format } from 'date-fns'
import { convertNamesToInitials, formatNames, round3 } from '../helpers'
import { loadImageBuffer } from '../loadImageBuffer'
import type { DocumentContext } from '../context'
import type { SheetState } from '../state'

void ExcelJS
void format
void round3
void convertNamesToInitials
void formatNames
void loadImageBuffer

export const buildCustomInvoice = async (
  ctx: DocumentContext,
  state: SheetState,
  built: Record<string, any> = {}
): Promise<{ workbook: any; sheet: any; state: SheetState; built: Record<string, any> }> => {
    void built
    const {
        companyName,
        companyAddress,
        email,
        taxid,
        ieCode,
        panNo,
        gstinNo,
        stateCode,
        invoiceNo,
        invoiceDate,
        buyersOrderNo,
        buyersOrderDate,
        poNo,
        formattedNotifyParty,
        preCarriage,
        vassalFlightNo,
        placeOfReceipt,
        portOfLoading,
        portOfDischarge,
        finalDestination,
        countryOfOrigin,
        origin,
        termsOfDeliveryMain,
        termsOfDelivery,
        termsOfDeliveryMainAt,
        paymentTerms,
        shippingMethod,
        currency,
        currencyRate,
        containerType,
        marksAndNos,
        products,
        grossWeight,
        netWeight,
        insurance,
        freight,
        totalFOBEuro,
        amountInWords,
        gstCirculerNumber,
        arn,
        lutDate,
        totalInINR,
        gstValue,
        supplierDetails,
        packegingType,
        taxStatus,
        type,
        unitOfIt,
        signatureUrl,
        configurePrintSheet,
        setGlobalFontSize,
        pixelToExcelWidth,
        columnWidths,
        setOuterBorder
    } = ctx
    let signature: any, vgnSignatureW: any, vgnSignatureH: any

    // Create a new workbook
    const workbook = new ExcelJS.Workbook();
    const worksheet = workbook.addWorksheet('CUSTOM INVOICE');

   // e.g., "https://api.example.com/exporter/header"


    // let response = await fetch('/devabhai.png'); // <-- relative to `public/`
    // let arrayBuf = await response.arrayBuffer();

    // ✅ Add image to workbook









    if (signatureUrl) {

        const { buffer, extension, width, height } = await loadImageBuffer(signatureUrl);
        signature = workbook.addImage({
            buffer: buffer,
            extension: extension,
        });
        vgnSignatureW = width;
        vgnSignatureH = height;

    }





    worksheet.getColumn(1).width = 5;
    worksheet.getCell('A1').value = worksheet.getCell('A1').value || ' ';



    configurePrintSheet(worksheet);
    // worksheet.pageSetup = {
    //   paperSize: 9,            // A4
    //   orientation: 'portrait',
    //   fitToPage: true,
    //   fitToWidth: 1,           // Fit width to one page
    //   horizontalCentered: true,
    // };




    //setting font size to 10
    worksheet.eachRow((row) => {
        row.eachCell((cell) => {
            cell.font = { size: 12 };
        });
    });

    // Setting widht for each column

    worksheet.getColumn(17).hidden = true;








    workbook.calcProperties.fullCalcOnLoad = true;


    worksheet.mergeCells('A1:AA1');
    worksheet.getCell('A1').value = 'CUSTOMS INVOICE';
    worksheet.getCell('A1').font = { bold: true };
    worksheet.getCell('A1').alignment = { horizontal: 'center' };
    setOuterBorder('A1:AA1', worksheet);

    // ✅ Red note below title
    worksheet.mergeCells('A2:AA2');
    if (taxStatus === "without") {
        worksheet.getCell('A2').value = '“SUPPLY MEANT FOR EXPORT UNDER BOND & LUT- LETTER OF UNDERTAKING WITHOUT PAYMENT OF INTEGRATED TAX”';
    } else if (taxStatus === "with") {
        worksheet.getCell('A2').value = '“SUPPLY MEANT FOR EXPORT WITH PAYMENT OF INTEGRATED TAX (IGST)”';
    }
    // worksheet.getCell('A2').font = { bold: true, color: { argb: 'FFFF0000' } };
    worksheet.getCell('A2').font = { bold: true, italic: true };
    worksheet.getCell('A2').alignment = { horizontal: 'center' };
    setOuterBorder('A2:AA2', worksheet);

    // ✅ Exporter Info
    worksheet.mergeCells('A3:N3');
    worksheet.getCell('A3').value = `EXPORTER:`;
    worksheet.getCell('A3').alignment = { wrapText: true, vertical: 'top' };
    worksheet.getCell('A3').font = { bold: true, underline: true };

    worksheet.mergeCells('A4:N10');
    worksheet.getCell('A4').value = `${companyName}\n${companyAddress}`;
    worksheet.getCell('A4').alignment = { wrapText: true, vertical: 'top' };
    worksheet.getCell('A4').font = { bold: true };
    setOuterBorder('A4:N10', worksheet);

    // ✅ Email & Tax No

    worksheet.mergeCells('A11:B11');
    worksheet.getCell('A11').value = `EMAIL:`;
    worksheet.getCell('A11').font = { bold: true };
    worksheet.getCell('A11').alignment = { wrapText: true };

    worksheet.mergeCells('A12:B12');
    worksheet.getCell('A12').value = `TAX ID:`;
    worksheet.getCell('A12').font = { bold: true };
    worksheet.getCell('A12').alignment = { wrapText: true };

    worksheet.mergeCells('C11:N11');
    worksheet.getCell('C11').value = email;
    worksheet.getCell('C11').alignment = { wrapText: true };

    worksheet.mergeCells('C12:N12');
    worksheet.getCell('C12').value = taxid;
    worksheet.getCell('C12').alignment = { wrapText: true };
    setOuterBorder('A11:N12', worksheet);

    // ✅ Invoice No. & Date
    worksheet.mergeCells('O3:T3');
    worksheet.getCell('O3').value = "Invoice No. & Date:";
    worksheet.getCell('O3').font = { bold: true };
    worksheet.getCell('O3').alignment = { horizontal: 'center' };

    worksheet.mergeCells('O4:T4');
    worksheet.getCell('O4').value = `${invoiceNo}`;

    worksheet.mergeCells('O5:T5');
    worksheet.getCell('O5').value = `Dt. ${invoiceDate}`;

    setOuterBorder('O3:T5', worksheet);

    // ✅ Exporter's Ref
    worksheet.mergeCells('U3:AA3');
    worksheet.getCell('U3').value = "Exporter’s Ref.:";
    worksheet.getCell('U3').font = { bold: true };

    worksheet.mergeCells('U4:AA12');
    worksheet.getCell('U4').value = `I. E. Code #: ${ieCode}\nPAN No #: ${panNo}\nGSTIN No #: ${gstinNo}\nSTATE CODE : ${stateCode}`;
    worksheet.getCell('U4').alignment = { wrapText: true, vertical: 'top' };
    setOuterBorder('U3:AA12', worksheet);

    // ✅ Buyer's Order No
    worksheet.mergeCells('O6:T6');
    worksheet.getCell('O6').value = "Buyer's Order no. & Date";
    worksheet.getCell('O6').font = { bold: true };

    worksheet.mergeCells('O7:T8');
    worksheet.getCell('O7').value = `${buyersOrderNo}    ${buyersOrderDate}`;
    worksheet.getCell('O7').alignment = { wrapText: true, vertical: 'top' };

    worksheet.mergeCells('O12:T12');
    worksheet.getCell('O12').value = `PO No: ${poNo}`;
    setOuterBorder('O6:T12', worksheet);

    // ✅ Consignee
    worksheet.mergeCells('A13:N13');
    worksheet.getCell('A13').value = "Consignee:";
    worksheet.getCell('A13').font = { bold: true, underline: true };

    worksheet.mergeCells('A14:N19');
    worksheet.getCell('A14').value = `TO THE ORDER`;
    worksheet.getCell('A14').alignment = { wrapText: true, vertical: 'top' };
    setOuterBorder('A13:N19', worksheet);

    // ✅ Notify Party
    worksheet.mergeCells('O13:AA13');
    worksheet.getCell('O13').value = "Notify Party # :";
    worksheet.getCell('O13').font = { bold: true };

    worksheet.mergeCells('O14:AA19');
    worksheet.getCell('O14').value = `${formattedNotifyParty}`;
    worksheet.getCell('O14').font = { bold: true };
    worksheet.getCell('O14').alignment = { wrapText: true, vertical: 'top' };
    setOuterBorder('O13:AA19', worksheet, 'medium'); // Removalble

    worksheet.mergeCells('A20:G20');
    worksheet.getCell('A20').value = 'Pre-Carriage By';
    // worksheet.getCell('A20').font = { bold: true };
    worksheet.getCell('A20').alignment = { horizontal: 'center' };

    worksheet.mergeCells('A21:G21');
    worksheet.getCell('A21').value = `${preCarriage}`;
    worksheet.getCell('A21').font = { color: { argb: 'FFFF0000' }, bold: true };
    worksheet.getCell('A21').alignment = { horizontal: 'center' };
    setOuterBorder('A20:G21', worksheet);

    worksheet.mergeCells('H20:N20');
    worksheet.getCell('H20').value = "Place of Receipt by Pre-Carrier";
    // worksheet.getCell('H20').font = { bold: true };
    worksheet.getCell('H20').alignment = { horizontal: 'center' };

    worksheet.mergeCells('H21:N21');
    worksheet.getCell('H21').value = `${placeOfReceipt}`;
    worksheet.getCell('H21').font = { color: { argb: 'FFFF0000' }, bold: true };
    worksheet.getCell('H21').alignment = { horizontal: 'center' };
    setOuterBorder('H20:N21', worksheet);

    worksheet.mergeCells('O20:V20');
    // worksheet.getCell('O20').value = `Country of Origin of Goods : ${countryOfOrigin}`;
    worksheet.getCell('O20').value = {
        richText: [
            { text: 'Country of Origin of Goods : ', font: { bold: false } },
            // { text: countryOfOrigin, font: { bold: true } }
            { text: "INDIA", font: { bold: true } }
        ]
    };
    worksheet.getCell('O20').alignment = { horizontal: 'center' };

    worksheet.mergeCells('O21:V21');
    // worksheet.getCell('O21').value = `ORIGIN : ${origin}`;
    worksheet.getCell('O21').value = `ORIGIN : DISTRICT MORBI, STATE GUJARAT`;
    worksheet.getCell('O21').font = { bold: true };
    worksheet.getCell('O21').alignment = { horizontal: 'center' };
    setOuterBorder('O20:V21', worksheet);

    worksheet.mergeCells('W20:AA20');
    worksheet.getCell('W20').value = "Country of Final Destination";
    worksheet.getCell('W20').alignment = { horizontal: 'center' };

    worksheet.mergeCells('W21:AA21');
    worksheet.getCell('W21').value = `${finalDestination}`;
    worksheet.getCell('W21').font = { bold: true };
    worksheet.getCell('W21').alignment = { horizontal: 'center' };
    setOuterBorder('W20:AA21', worksheet);

    worksheet.mergeCells('A22:G22');
    worksheet.getCell('A22').value = 'Vessel Flight No.';
    // worksheet.getCell('A22').font = { bold: true };
    worksheet.getCell('A22').alignment = { horizontal: 'center' };

    worksheet.mergeCells('A23:G23');
    worksheet.getCell('A23').value = `${vassalFlightNo}`;
    worksheet.getCell('A23').font = { color: { argb: 'FFFF0000' }, bold: true };
    worksheet.getCell('A23').alignment = { horizontal: 'center' };
    setOuterBorder('A22:G23', worksheet);

    worksheet.mergeCells('H22:N22');
    worksheet.getCell('H22').value = "Port of Loading";
    // worksheet.getCell('H22').font = { bold: true };
    worksheet.getCell('H22').alignment = { horizontal: 'center' };

    worksheet.mergeCells('H23:N23');
    worksheet.getCell('H23').value = `${portOfLoading}`;
    worksheet.getCell('H23').font = { color: { argb: 'FFFF0000' }, bold: true };
    worksheet.getCell('H23').alignment = { horizontal: 'center' };
    setOuterBorder('H22:N23', worksheet);

    worksheet.mergeCells('A24:G24');
    worksheet.getCell('A24').value = 'Port of Discharge';
    // worksheet.getCell('A24').font = { bold: true };
    worksheet.getCell('A24').alignment = { horizontal: 'center' };

    worksheet.mergeCells('A25:G26');
    worksheet.getCell('A25').value = `${portOfDischarge}`;
    worksheet.getCell('A25').font = { color: { argb: 'FFFF0000' }, bold: true };
    worksheet.getCell('A25').alignment = { horizontal: 'center', vertical: 'middle' };
    setOuterBorder('A24:G26', worksheet);

    worksheet.mergeCells('H24:N24');
    worksheet.getCell('H24').value = "Final Destination";
    // worksheet.getCell('H24').font = { bold: true };
    worksheet.getCell('H24').alignment = { horizontal: 'center' };

    worksheet.mergeCells('H25:N26');
    worksheet.getCell('H25').value = `${finalDestination}`;
    worksheet.getCell('H25').font = { color: { argb: 'FFFF0000' }, bold: true };
    worksheet.getCell('H25').alignment = { horizontal: 'center', vertical: 'middle' };
    setOuterBorder('H24:N26', worksheet);

    worksheet.mergeCells('O22:AA22');
    worksheet.getCell('O22').value = "Terms of Delivery & Payment :-";
    worksheet.getCell('O22').font = { bold: true };

    worksheet.mergeCells('O23:AA23');
    if (termsOfDelivery === "FOB") {
        worksheet.getCell('O23').value = termsOfDeliveryMainAt;
    } else {
        worksheet.getCell('O23').value = termsOfDeliveryMainAt;
    }
    worksheet.getCell('O23').font = { color: { argb: 'FFFF0000' } };

    worksheet.mergeCells('O24:AA25');
    worksheet.getCell('O24').value = `PAYMENT : ${paymentTerms}`;
    worksheet.getCell('O24').font = { name: 'Arial', color: { argb: 'FFFF0000' } };
    worksheet.getCell('O24').alignment = { wrapText: true, horizontal: 'left', vertical: 'top' };

    worksheet.mergeCells('O26:U26');
    worksheet.getCell('O26').value = shippingMethod;
    setOuterBorder('O22:AA26', worksheet);

    if (type !== "tiles") {
        worksheet.mergeCells('W26:Y26');
        worksheet.getCell('W26').value = `${currency} RATE:`;
        worksheet.getCell('W26').alignment = { horizontal: 'center' };
        worksheet.getCell('W26').font = { bold: true };

        worksheet.mergeCells('Z26:AA26');
        worksheet.getCell('Z26').value = currencyRate;
        // worksheet.getCell('Z26').fill = {
        //     type: 'pattern',
        //     pattern: 'solid',
        //     fgColor: { argb: 'FFFFFF00' }, // Yellow fill
        // };

        worksheet.getCell('Z26').alignment = { horizontal: 'center' };
        worksheet.getCell('Z26').font = { bold: true };
        setOuterBorder('W26:AA26', worksheet, 'medium');
    } else {
        worksheet.mergeCells('V26:X26');
        worksheet.getCell('V26').value = `${currency} RATE:`;
        worksheet.getCell('V26').alignment = { horizontal: 'center' };
        worksheet.getCell('V26').font = { bold: true };

        worksheet.mergeCells('Y26:AA26');
        worksheet.getCell('Y26').value = currencyRate;
        worksheet.getCell('Y26').alignment = { horizontal: 'center' };
        // worksheet.getCell('Y26').fill = {
        //     type: 'pattern',
        //     pattern: 'solid',
        //     fgColor: { argb: 'FFFFFF00' }, // Yellow fill
        // };

        worksheet.getCell('Y26').font = { bold: true };
        setOuterBorder('V26:AA26', worksheet, 'medium');
    }

    worksheet.mergeCells('A27:D27');
    worksheet.getCell('A27').value = "Marks & Nos.";
    worksheet.getCell('A27').font = { bold: true };
    worksheet.getCell('A27').alignment = { horizontal: 'center' };

    if (containerType === 'FCL') {
        worksheet.mergeCells('A28:D28');
        worksheet.getCell('A28').value = `${marksAndNos} ${containerType}`;
        worksheet.getCell('A28').font = { bold: true };
        worksheet.getCell('A28').alignment = { horizontal: 'center' };
        setOuterBorder('A27:D28', worksheet, 'medium');
    } else {
        worksheet.mergeCells('A28:D28');
        worksheet.getCell('A28').value = `${containerType}`;
        worksheet.getCell('A28').font = { bold: true };
        worksheet.getCell('A28').alignment = { horizontal: 'center', vertical: 'middle' };
        setOuterBorder('A27:D28', worksheet, 'medium');
    }
    worksheet.getRow(28).height = 24;

    worksheet.mergeCells('E27:Q28');
    worksheet.getCell('E27').value = "Description of Goods";
    worksheet.getCell('E27').font = { bold: true };
    worksheet.getCell('E27').alignment = { horizontal: 'center', vertical: 'middle' };
    setOuterBorder('E27:Q28', worksheet, 'medium');

    if (type !== "tiles") {
        worksheet.getCell('R27').value = "SIZE";
        worksheet.getCell('R27').font = { bold: true };
        worksheet.getCell('R27').alignment = { horizontal: 'center', vertical: 'middle' };

        worksheet.getCell('R28').value = "MM";
        worksheet.getCell('R28').font = { bold: true };
        worksheet.getCell('R28').alignment = { horizontal: 'center', vertical: 'middle' };
        setOuterBorder('R27:R28', worksheet, 'medium');

        worksheet.mergeCells('S27:T27')
        worksheet.getCell('S27').value = "QUANTITY";
        worksheet.getCell('S27').font = { bold: true };
        worksheet.getCell('S27').alignment = { horizontal: 'center', vertical: 'middle' };

        worksheet.mergeCells('S28:T28')
        worksheet.getCell('S28').value = packegingType;
        worksheet.getCell('S28').font = { bold: true };
        worksheet.getCell('S28').alignment = { wrapText: true, horizontal: 'center', vertical: 'middle' };
        setOuterBorder('S27:T28', worksheet, 'medium');
        if (packegingType.length > 8) {
            worksheet.getCell('S28').font = { size: 8, bold: true };
        }

        worksheet.mergeCells('U27:V27')
        worksheet.getCell('U27').value = "UNIT TYPE";
        worksheet.getCell('U27').font = { bold: true };
        worksheet.getCell('U27').alignment = { horizontal: 'center', vertical: 'middle' };

        worksheet.mergeCells('U28:V28')
        worksheet.getCell('U28').value = packegingType;
        worksheet.getCell('U28').font = { bold: true };
        worksheet.getCell('U28').alignment = { wrapText: true, horizontal: 'center', vertical: 'middle' };
        setOuterBorder('U27:V28', worksheet, 'medium');

        worksheet.mergeCells('W27:X27')
        worksheet.getCell('W27').value = "SQM/";
        worksheet.getCell('W27').font = { bold: true };
        worksheet.getCell('W27').alignment = { horizontal: 'center', vertical: 'middle' };

        worksheet.mergeCells('W28:X28')
        worksheet.getCell('W28').value = unitOfIt;
        worksheet.getCell('W28').font = { bold: true };
        worksheet.getCell('W28').alignment = { horizontal: 'center', vertical: 'middle' };
        setOuterBorder('W27:X28', worksheet, 'medium');

        worksheet.getCell('Y27').value = "TOTAL";
        worksheet.getCell('Y27').font = { bold: true };
        worksheet.getCell('Y27').alignment = { horizontal: 'center', vertical: 'middle' };

        worksheet.getCell('Y28').value = "SQM";
        worksheet.getCell('Y28').font = { bold: true };
        worksheet.getCell('Y28').alignment = { horizontal: 'center', vertical: 'middle' };
        setOuterBorder('Y27:Y28', worksheet, 'medium');

        worksheet.getCell('Z27').value = "PRICE/";
        worksheet.getCell('Z27').font = { bold: true };
        worksheet.getCell('Z27').alignment = { horizontal: 'center', vertical: 'middle' };

        worksheet.getCell('Z28').value = "SQM";
        worksheet.getCell('Z28').font = { bold: true };
        worksheet.getCell('Z28').alignment = { horizontal: 'center', vertical: 'middle' };
        setOuterBorder('Z27:Z28', worksheet, 'medium');

        worksheet.getCell('AA27').value = "AMOUNT";
        worksheet.getCell('AA27').font = { bold: true };
        worksheet.getCell('AA27').alignment = { horizontal: 'center', vertical: 'middle' };

        worksheet.getCell('AA28').value = `IN (${currency})`;
        worksheet.getCell('AA28').font = { bold: true };
        worksheet.getCell('AA28').alignment = { horizontal: 'center', vertical: 'middle' };
        setOuterBorder('AA27:AA28', worksheet, 'medium');
    }
    else {
        worksheet.mergeCells('R27:S27')
        worksheet.getCell('R27').value = "QUANTITY";
        worksheet.getCell('R27').font = { bold: true };
        worksheet.getCell('R27').alignment = { horizontal: 'center', vertical: 'middle' };

        worksheet.mergeCells('R28:S28')
        worksheet.getCell('R28').value = "PKGS";
        worksheet.getCell('R28').font = { bold: true };
        worksheet.getCell('R28').alignment = { horizontal: 'center', vertical: 'middle' };
        setOuterBorder('R27:S28', worksheet);

        worksheet.mergeCells('T27:U27')
        worksheet.getCell('T27').value = "UNIT TYPE";
        worksheet.getCell('T27').font = { bold: true };
        worksheet.getCell('T27').alignment = { horizontal: 'center', vertical: 'middle' };

        worksheet.mergeCells('T28:U28')
        worksheet.getCell('T28').value = packegingType;
        worksheet.getCell('T28').font = { bold: true };
        worksheet.getCell('T28').alignment = { horizontal: 'center', vertical: 'middle' };
        setOuterBorder('T27:U28', worksheet);
        if (packegingType.length > 8) {
            worksheet.getCell('T28').font = { size: 8, bold: true };
        }

        worksheet.mergeCells('V27:X27')
        worksheet.getCell('V27').value = "RATE PER";
        worksheet.getCell('V27').font = { bold: true };
        worksheet.getCell('V27').alignment = { horizontal: 'center', vertical: 'middle' };

        worksheet.mergeCells('V28:X28')
        worksheet.getCell('V28').value = `UNIT (${currency})`;
        worksheet.getCell('V28').font = { bold: true };
        worksheet.getCell('V28').alignment = { horizontal: 'center', vertical: 'middle' };
        setOuterBorder('V27:X28', worksheet);

        worksheet.mergeCells('Y27:AA27')
        worksheet.getCell('Y27').value = "AMOUNT/";
        worksheet.getCell('Y27').font = { bold: true };
        worksheet.getCell('Y27').alignment = { horizontal: 'center', vertical: 'middle' };

        worksheet.mergeCells('Y28:AA28')
        worksheet.getCell('Y28').value = `IN (${currency})`;
        worksheet.getCell('Y28').font = { bold: true };
        worksheet.getCell('Y28').alignment = { horizontal: 'center', vertical: 'middle' };
        setOuterBorder('Y27:AA28', worksheet);
    }
    if (packegingType.length > 6) {
        worksheet.getRow(28).height = 36;
    }

    worksheet.getCell('A29').value = "SR NO.";
    worksheet.getCell('A29').font = { bold: true };
    worksheet.getCell('A29').alignment = { horizontal: 'center', vertical: 'middle' };
    worksheet.getCell('A29').border = {
        top: { style: 'thin', color: { argb: 'FF000000' } },     // black
        left: { style: 'thin', color: { argb: 'FF000000' } },
        bottom: { style: 'thin', color: { argb: 'FF000000' } },
        right: { style: 'thin', color: { argb: 'FF000000' } },
    };

    worksheet.mergeCells('B29:D29');
    worksheet.getCell('B29').value = "HSN CODE";
    worksheet.getCell('B29').font = { bold: true };
    worksheet.getCell('B29').alignment = { horizontal: 'center', vertical: 'middle' };
    setOuterBorder('B29:D29', worksheet);

    // Table saction

    let srNo = 1;
    let row = 28;
    let hsnCode: number;
    let allProductsType: string;
    for (let i = 0; i < products.length; i++) {
        if (type !== "tiles") {
            row++;
            if (products[i].length === 2) {
                worksheet.mergeCells('E' + row + ':Q' + row);
                worksheet.getCell('E' + row).value = products[i][0];
                // worksheet.getCell('E' + row).fill = {
                //     type: 'pattern',
                //     pattern: 'solid',
                //     fgColor: { argb: 'FFFFCC99' }, // Light orange / peach
                // };
                worksheet.getCell('E' + row).font = { bold: true, size: 12 };
                worksheet.getCell('E' + row).alignment = { horizontal: 'center', vertical: 'middle' };
                worksheet.getRow(row).height = 46;
                setOuterBorder('E' + row + ':Q' + row, worksheet);
                hsnCode = Number(products[i][1]);
                if (i == 0) {
                    allProductsType = String(products[i][0]);
                }
                else {
                    allProductsType += '/' + String(products[i][0]);
                }

                if (i !== 0) {
                    worksheet.getCell('A' + row).border = {
                        top: { style: 'thin', color: { argb: 'FF000000' } },     // black
                        left: { style: 'thin', color: { argb: 'FF000000' } },
                        bottom: { style: 'thin', color: { argb: 'FF000000' } },
                        right: { style: 'thin', color: { argb: 'FF000000' } },
                    };

                    setOuterBorder('B' + row + ':D' + row, worksheet);
                }
                setOuterBorder('E' + row + ':Q' + row, worksheet);

                worksheet.getCell('R' + row).border = {
                    top: { style: 'thin', color: { argb: 'FF000000' } },     // black
                    left: { style: 'thin', color: { argb: 'FF000000' } },
                    bottom: { style: 'thin', color: { argb: 'FF000000' } },
                    right: { style: 'thin', color: { argb: 'FF000000' } },
                };

                setOuterBorder('S' + row + ':T' + row, worksheet);
                setOuterBorder('U' + row + ':V' + row, worksheet);
                setOuterBorder('W' + row + ':X' + row, worksheet);

                worksheet.getCell('Y' + row).border = {
                    top: { style: 'thin', color: { argb: 'FF000000' } },     // black
                    left: { style: 'thin', color: { argb: 'FF000000' } },
                    bottom: { style: 'thin', color: { argb: 'FF000000' } },
                    right: { style: 'thin', color: { argb: 'FF000000' } },
                };

                worksheet.getCell('Z' + row).border = {
                    top: { style: 'thin', color: { argb: 'FF000000' } },     // black
                    left: { style: 'thin', color: { argb: 'FF000000' } },
                    bottom: { style: 'thin', color: { argb: 'FF000000' } },
                    right: { style: 'thin', color: { argb: 'FF000000' } },
                };

                worksheet.getCell('AA' + row).border = {
                    top: { style: 'thin', color: { argb: 'FF000000' } },     // black
                    left: { style: 'thin', color: { argb: 'FF000000' } },
                    bottom: { style: 'thin', color: { argb: 'FF000000' } },
                    right: { style: 'thin', color: { argb: 'FF000000' } },
                };

            } else {

                worksheet.getCell('A' + row).value = srNo;
                worksheet.getCell('A' + row).alignment = { wrapText: true, horizontal: 'center', vertical: 'middle' };
                worksheet.getCell('A' + row).border = {
                    top: { style: 'thin', color: { argb: 'FF000000' } },     // black
                    left: { style: 'thin', color: { argb: 'FF000000' } },
                    bottom: { style: 'thin', color: { argb: 'FF000000' } },
                    right: { style: 'thin', color: { argb: 'FF000000' } },
                };
                srNo++;

                worksheet.mergeCells('B' + row + ':D' + row);
                worksheet.getCell('B' + row).value = hsnCode;
                worksheet.getCell('B' + row).font = { bold: true };
                worksheet.getCell('B' + row).alignment = { wrapText: true, horizontal: 'center', vertical: 'middle' };
                setOuterBorder('B' + row + ':D' + row, worksheet);

                worksheet.mergeCells('E' + row + ':Q' + row);
                worksheet.getCell('E' + row).value = products[i][0];
                worksheet.getCell('E' + row).font = { size: 12 };
                worksheet.getCell('E' + row).alignment = { wrapText: true, horizontal: 'center', vertical: 'middle' };
                setOuterBorder('E' + row + ':Q' + row, worksheet);
                if (String(products[i][0]).length > 56) {
                    worksheet.getRow(row).height = 36;
                }

                if (products[i][1] === "-") {
                    worksheet.getCell('R' + row).value = "-";
                } else {
                    worksheet.getCell('R' + row).value = products[i][1];
                }
                worksheet.getCell('R' + row).alignment = { wrapText: true, horizontal: 'center', vertical: 'middle' };
                worksheet.getCell('R' + row).font = { size: 12 };
                worksheet.getCell('R' + row).border = {
                    top: { style: 'thin', color: { argb: 'FF000000' } },     // black
                    left: { style: 'thin', color: { argb: 'FF000000' } },
                    bottom: { style: 'thin', color: { argb: 'FF000000' } },
                    right: { style: 'thin', color: { argb: 'FF000000' } },
                };

                worksheet.mergeCells('S' + row + ':T' + row);
                worksheet.getCell('S' + row).value = products[i][2];
                worksheet.getCell('S' + row).font = { size: 12 };
                worksheet.getCell('S' + row).alignment = { wrapText: true, horizontal: 'center', vertical: 'middle' };
                setOuterBorder('S' + row + ':T' + row, worksheet);

                worksheet.mergeCells('U' + row + ':V' + row);
                worksheet.getCell('U' + row).value = products[i][3];
                worksheet.getCell('U' + row).font = { size: 12 };
                worksheet.getCell('U' + row).alignment = { wrapText: true, horizontal: 'center', vertical: 'middle' };
                setOuterBorder('U' + row + ':V' + row, worksheet);

                worksheet.mergeCells('W' + row + ':X' + row);
                if (products[i][4] === "-") {
                    worksheet.getCell('W' + row).value = "-";
                } else {
                    worksheet.getCell('W' + row).value = products[i][4];
                }
                worksheet.getCell('W' + row).font = { size: 12 };
                worksheet.getCell('W' + row).alignment = { wrapText: true, horizontal: 'center', vertical: 'middle' };
                setOuterBorder('W' + row + ':X' + row, worksheet);

                if (products[i][5] === "-") {
                    worksheet.getCell('Y' + row).value = "-";
                } else {
                    if (products[i][4] === "-") {
                        if (products[i][5] === "" || products[i][5] === 0) {
                            worksheet.getCell('Y' + row).value = "-";
                        } else {
                            worksheet.getCell('Y' + row).value = products[i][5];
                        }
                    } else {
                        worksheet.getCell('Y' + row).value = { formula: `S${row}*W${row}`, result: 0 };
                    }
                }
                worksheet.getCell('Y' + row).alignment = { wrapText: true, horizontal: 'center', vertical: 'middle' };
                worksheet.getCell('Y' + row).font = { size: 12 };
                worksheet.getCell('Y' + row).border = {
                    top: { style: 'thin', color: { argb: 'FF000000' } },     // black
                    left: { style: 'thin', color: { argb: 'FF000000' } },
                    bottom: { style: 'thin', color: { argb: 'FF000000' } },
                    right: { style: 'thin', color: { argb: 'FF000000' } },
                };

                worksheet.getCell('Z' + row).value = products[i][6];
                worksheet.getCell('Z' + row).alignment = { wrapText: true, horizontal: 'center', vertical: 'middle' };
                worksheet.getCell('Z' + row).font = { size: 12 };
                worksheet.getCell('Z' + row).border = {
                    top: { style: 'thin', color: { argb: 'FF000000' } },     // black
                    left: { style: 'thin', color: { argb: 'FF000000' } },
                    bottom: { style: 'thin', color: { argb: 'FF000000' } },
                    right: { style: 'thin', color: { argb: 'FF000000' } },
                };
                worksheet.getCell('Z' + row).numFmt = '0.00';

                // worksheet.getCell('AA' + row).value = products[i][7];
                if (products[i][1] === "-") {
                    if (products[i][5] === "" || products[i][5] === 0) {
                        worksheet.getCell('AA' + row).value = { formula: `ROUND(S${row}*Z${row}, 2)`, result: 0 };
                    } else {
                        worksheet.getCell('AA' + row).value = { formula: `ROUND(Y${row}*Z${row}, 2)`, result: 0 };
                    }
                } else {
                    worksheet.getCell('AA' + row).value = { formula: `ROUND(Y${row}*Z${row}, 2)`, result: 0 };
                }
                worksheet.getCell('AA' + row).numFmt = '0.00';
                worksheet.getCell('AA' + row).alignment = { wrapText: true, horizontal: 'center', vertical: 'middle' };
                worksheet.getCell('AA' + row).font = { size: 12 };
                worksheet.getCell('AA' + row).border = {
                    top: { style: 'thin', color: { argb: 'FF000000' } },     // black
                    left: { style: 'thin', color: { argb: 'FF000000' } },
                    bottom: { style: 'thin', color: { argb: 'FF000000' } },
                    right: { style: 'thin', color: { argb: 'FF000000' } },
                };

            }
        }
        else {
            row++;
            if (products[i].length === 2) {
                worksheet.mergeCells('E' + row + ':Q' + row);
                worksheet.getCell('E' + row).value = products[i][0];
                // worksheet.getCell('E' + row).fill = {
                //     type: 'pattern',
                //     pattern: 'solid',
                //     fgColor: { argb: 'FFFFCC99' }, // Light orange / peach
                // };

                worksheet.getCell('E' + row).font = { bold: true, size: 12 };
                worksheet.getCell('E' + row).alignment = { horizontal: 'center', vertical: 'middle' };
                worksheet.getRow(row).height = 46;
                setOuterBorder('E' + row + ':Q' + row, worksheet);
                hsnCode = Number(products[i][1]);
                if (i == 0) {
                    allProductsType = String(products[i][0]);
                }
                else {
                    allProductsType += '/' + String(products[i][0]);
                }

                if (i !== 0) {
                    worksheet.getCell('A' + row).border = {
                        top: { style: 'thin', color: { argb: 'FF000000' } },     // black
                        left: { style: 'thin', color: { argb: 'FF000000' } },
                        bottom: { style: 'thin', color: { argb: 'FF000000' } },
                        right: { style: 'thin', color: { argb: 'FF000000' } },
                    };

                    setOuterBorder('B' + row + ':D' + row, worksheet);
                }
                setOuterBorder('E' + row + ':Q' + row, worksheet);

                setOuterBorder('R' + row + ':S' + row, worksheet);
                setOuterBorder('T' + row + ':U' + row, worksheet);
                setOuterBorder('V' + row + ':X' + row, worksheet);
                setOuterBorder('Y' + row + ':AA' + row, worksheet);

            } else {
                worksheet.getCell('A' + row).value = srNo;
                worksheet.getCell('A' + row).alignment = { wrapText: true, horizontal: 'center', vertical: 'middle' };
                worksheet.getCell('A' + row).border = {
                    top: { style: 'thin', color: { argb: 'FF000000' } },     // black
                    left: { style: 'thin', color: { argb: 'FF000000' } },
                    bottom: { style: 'thin', color: { argb: 'FF000000' } },
                    right: { style: 'thin', color: { argb: 'FF000000' } },
                };
                srNo++;

                worksheet.mergeCells('B' + row + ':D' + row);
                worksheet.getCell('B' + row).value = hsnCode;
                worksheet.getCell('B' + row).font = { bold: true };
                worksheet.getCell('B' + row).alignment = { wrapText: true, horizontal: 'center', vertical: 'middle' };
                setOuterBorder('B' + row + ':D' + row, worksheet);

                worksheet.mergeCells('E' + row + ':Q' + row);
                worksheet.getCell('E' + row).value = products[i][0];
                worksheet.getCell('E' + row).font = { size: 12 };
                worksheet.getCell('E' + row).alignment = { wrapText: true, horizontal: 'center', vertical: 'middle' };
                setOuterBorder('E' + row + ':Q' + row, worksheet);
                if (String(products[i][0]).length > 56) {
                    worksheet.getRow(row).height = 36;
                }

                worksheet.mergeCells('R' + row + ':S' + row);
                worksheet.getCell('R' + row).value = products[i][2];
                worksheet.getCell('R' + row).font = { size: 12 };
                worksheet.getCell('R' + row).alignment = { wrapText: true, horizontal: 'center', vertical: 'middle' };
                setOuterBorder('R' + row + ':S' + row, worksheet);

                worksheet.mergeCells('T' + row + ':U' + row);
                worksheet.getCell('T' + row).value = products[i][3];
                worksheet.getCell('T' + row).font = { size: 12 };
                worksheet.getCell('T' + row).alignment = { wrapText: true, horizontal: 'center', vertical: 'middle' };
                setOuterBorder('T' + row + ':U' + row, worksheet);

                worksheet.mergeCells('V' + row + ':X' + row);
                worksheet.getCell('V' + row).value = products[i][6];
                worksheet.getCell('V' + row).numFmt = '0.00';
                worksheet.getCell('V' + row).font = { size: 12 };
                worksheet.getCell('V' + row).alignment = { wrapText: true, horizontal: 'center', vertical: 'middle' };
                setOuterBorder('V' + row + ':X' + row, worksheet);

                worksheet.mergeCells('Y' + row + ':AA' + row);
                // worksheet.getCell('Y' + row).value = products[i][7];
                worksheet.getCell('Y' + row).value = { formula: `ROUND(R${row}*V${row}, 2)`, result: 0 };
                worksheet.getCell('Y' + row).numFmt = '0.00';
                worksheet.getCell('Y' + row).font = { size: 12 };
                worksheet.getCell('Y' + row).alignment = { wrapText: true, horizontal: 'center', vertical: 'middle' };
                setOuterBorder('Y' + row + ':AA' + row, worksheet);
            }
        }
    }

    row++;
    worksheet.mergeCells('A' + row + ':D' + (row + 7));
    setOuterBorder('A' + row + ':D' + (row + 7), worksheet);

    let skipRow = 3;
    let addSkipRow = 6;
    if (taxStatus == "with") {
        skipRow = 2;
        addSkipRow = 7;
    }
    if (type !== "tiles") {
        for (let i = 0; i < skipRow; i++) {
            setOuterBorder('E' + row + ':Q' + row, worksheet);

            worksheet.getCell('R' + row).border = {
                top: { style: 'thin', color: { argb: 'FF000000' } },     // black
                left: { style: 'thin', color: { argb: 'FF000000' } },
                bottom: { style: 'thin', color: { argb: 'FF000000' } },
                right: { style: 'thin', color: { argb: 'FF000000' } },
            };

            setOuterBorder('S' + row + ':T' + row, worksheet);
            setOuterBorder('U' + row + ':V' + row, worksheet);
            setOuterBorder('W' + row + ':X' + row, worksheet);

            worksheet.getCell('Y' + row).border = {
                top: { style: 'thin', color: { argb: 'FF000000' } },     // black
                left: { style: 'thin', color: { argb: 'FF000000' } },
                bottom: { style: 'thin', color: { argb: 'FF000000' } },
                right: { style: 'thin', color: { argb: 'FF000000' } },
            };

            worksheet.getCell('Z' + row).border = {
                top: { style: 'thin', color: { argb: 'FF000000' } },     // black
                left: { style: 'thin', color: { argb: 'FF000000' } },
                bottom: { style: 'thin', color: { argb: 'FF000000' } },
                right: { style: 'thin', color: { argb: 'FF000000' } },
            };

            worksheet.getCell('AA' + row).border = {
                top: { style: 'thin', color: { argb: 'FF000000' } },     // black
                left: { style: 'thin', color: { argb: 'FF000000' } },
                bottom: { style: 'thin', color: { argb: 'FF000000' } },
                right: { style: 'thin', color: { argb: 'FF000000' } },
            };
            row++;
        }

        worksheet.mergeCells('R' + row + ':R' + (row + addSkipRow));
        setOuterBorder('R' + row + ':R' + (row + addSkipRow), worksheet);
        worksheet.mergeCells('S' + row + ':T' + (row + addSkipRow));
        setOuterBorder('S' + row + ':T' + (row + addSkipRow), worksheet);
        worksheet.mergeCells('U' + row + ':V' + (row + addSkipRow));
        setOuterBorder('U' + row + ':V' + (row + addSkipRow), worksheet);
        worksheet.mergeCells('W' + row + ':X' + (row + addSkipRow));
        setOuterBorder('W' + row + ':X' + (row + addSkipRow), worksheet);
        worksheet.mergeCells('Y' + row + ':Y' + (row + addSkipRow));
        setOuterBorder('Y' + row + ':Y' + (row + addSkipRow), worksheet);
        worksheet.mergeCells('Z' + row + ':Z' + (row + addSkipRow));
        setOuterBorder('Z' + row + ':Z' + (row + addSkipRow), worksheet);
        worksheet.mergeCells('AA' + row + ':AA' + (row + addSkipRow));
        setOuterBorder('AA' + row + ':AA' + (row + addSkipRow), worksheet);
    }
    else {
        for (let i = 0; i < skipRow; i++) {
            setOuterBorder('E' + row + ':Q' + row, worksheet);

            setOuterBorder('R' + row + ':S' + row, worksheet);
            setOuterBorder('T' + row + ':U' + row, worksheet);
            setOuterBorder('V' + row + ':X' + row, worksheet);
            setOuterBorder('Y' + row + ':AA' + row, worksheet);
            row++;
        }

        worksheet.mergeCells('R' + row + ':S' + (row + addSkipRow));
        setOuterBorder('R' + row + ':S' + (row + addSkipRow), worksheet);
        worksheet.mergeCells('T' + row + ':U' + (row + addSkipRow));
        setOuterBorder('T' + row + ':U' + (row + addSkipRow), worksheet);
        worksheet.mergeCells('V' + row + ':X' + (row + addSkipRow));
        setOuterBorder('V' + row + ':X' + (row + addSkipRow), worksheet);
        worksheet.mergeCells('Y' + row + ':AA' + (row + addSkipRow));
        setOuterBorder('Y' + row + ':AA' + (row + addSkipRow), worksheet);
    }

    if (taxStatus == "with") {
        worksheet.mergeCells('E' + row + ':Q' + row);
        worksheet.getCell('E' + row).value = "CERTIFIED THAT GOODS ARE OF INDIAN ORIGIN";
        worksheet.getCell('E' + row).font = { name: 'Arial' };
        worksheet.getCell('E' + row).alignment = { horizontal: 'center' };
        setOuterBorder('E' + row + ':Q' + row, worksheet);
        row++;
    }

    worksheet.mergeCells('E' + row + ':Q' + row);
    worksheet.getCell('E' + row).value = "Export Under Duty Drawback Scheme";
    worksheet.getCell('E' + row).font = { bold: true };
    worksheet.getCell('E' + row).alignment = { horizontal: 'center' };
    setOuterBorder('E' + row + ':Q' + row, worksheet);
    row++;

    worksheet.mergeCells('E' + row + ':Q' + (row + 1));
    worksheet.getCell('E' + row).value = "I/we shall claim under chapter 3 incentive of FTP as admissible at time policy in force - MEIS, RODTEP ";
    worksheet.getCell('E' + row).font = { bold: true };
    worksheet.getCell('E' + row).alignment = { wrapText: true, horizontal: 'center' };
    setOuterBorder('E' + row + ':Q' + (row + 1), worksheet);
    row += 2;

    worksheet.mergeCells('E' + row + ':Q' + (row + 1));
    setOuterBorder('E' + row + ':Q' + (row + 1), worksheet);
    row += 2;

    if (type !== 'tiles') {
        worksheet.mergeCells('A' + row + ':E' + row);
        worksheet.getCell('A' + row).value = "NET WT. (KGS): ";
        worksheet.getCell('A' + row).font = { underline: true };
        worksheet.getCell('A' + row).alignment = { horizontal: 'right' };
        setOuterBorder('A' + row + ':E' + row, worksheet);

        worksheet.mergeCells('F' + row + ':H' + row);
        worksheet.getCell('F' + row).value = netWeight;
        worksheet.getCell('F' + row).numFmt = '0.00';
        // worksheet.getCell('F' + row).fill = {
        //     type: 'pattern',
        //     pattern: 'solid',
        //     fgColor: { argb: 'FFFFFF00' },
        // };
        worksheet.getCell('F' + row).font = { bold: true, underline: true };
        worksheet.getCell('F' + row).alignment = { horizontal: 'left' };
        setOuterBorder('F' + row + ':H' + row, worksheet);

        worksheet.mergeCells('I' + row + ':Q' + row);
        setOuterBorder('I' + row + ':Q' + row, worksheet);
        row++;

        worksheet.mergeCells('A' + row + ':E' + row);
        worksheet.getCell('A' + row).value = "GROSS WT.(KGS): ";
        worksheet.getCell('A' + row).font = { underline: true };
        worksheet.getCell('A' + row).alignment = { horizontal: 'right' };
        setOuterBorder('A' + row + ':E' + row, worksheet);

        worksheet.mergeCells('F' + row + ':H' + row);
        worksheet.getCell('F' + row).value = grossWeight;
        worksheet.getCell('F' + row).numFmt = '0.00';
        // worksheet.getCell('F' + row).fill = {
        //     type: 'pattern',
        //     pattern: 'solid',
        //     fgColor: { argb: 'FFFFFF00' },
        // };
        worksheet.getCell('F' + row).font = { bold: true, underline: true };
        worksheet.getCell('F' + row).alignment = { horizontal: 'left' };
        setOuterBorder('F' + row + ':H' + row, worksheet);

        worksheet.mergeCells('I' + row + ':Q' + row);
        setOuterBorder('I' + row + ':Q' + row, worksheet);
        row++;
    } else {
        worksheet.mergeCells('A' + row + ':D' + row);
        worksheet.getCell('A' + row).value = "NET WT. (KGS): ";
        worksheet.getCell('A' + row).font = { underline: true };
        worksheet.getCell('A' + row).alignment = { horizontal: 'right' };
        setOuterBorder('A' + row + ':D' + row, worksheet);

        worksheet.mergeCells('E' + row + ':G' + row);
        worksheet.getCell('E' + row).value = netWeight;
        worksheet.getCell('E' + row).numFmt = '0.00';
        // worksheet.getCell('E' + row).fill = {
        //     type: 'pattern',
        //     pattern: 'solid',
        //     fgColor: { argb: 'FFFFFF00' },
        // };
        worksheet.getCell('E' + row).font = { bold: true, underline: true };
        worksheet.getCell('E' + row).alignment = { horizontal: 'left' };
        setOuterBorder('E' + row + ':G' + row, worksheet);

        worksheet.mergeCells('H' + row + ':Q' + row);
        setOuterBorder('H' + row + ':Q' + row, worksheet);
        row++;

        worksheet.mergeCells('A' + row + ':D' + row);
        worksheet.getCell('A' + row).value = "GROSS WT.(KGS): ";
        worksheet.getCell('A' + row).font = { underline: true };
        worksheet.getCell('A' + row).alignment = { horizontal: 'right' };
        setOuterBorder('A' + row + ':D' + row, worksheet);

        worksheet.mergeCells('E' + row + ':G' + row);
        worksheet.getCell('E' + row).value = grossWeight;
        worksheet.getCell('E' + row).numFmt = '0.00';
        // worksheet.getCell('E' + row).fill = {
        //     type: 'pattern',
        //     pattern: 'solid',
        //     fgColor: { argb: 'FFFFFF00' },
        // };
        worksheet.getCell('E' + row).font = { bold: true, underline: true };
        worksheet.getCell('E' + row).alignment = { horizontal: 'left' };
        setOuterBorder('E' + row + ':G' + row, worksheet);

        worksheet.mergeCells('H' + row + ':Q' + row);
        setOuterBorder('H' + row + ':Q' + row, worksheet);
        row++;
    }

    worksheet.mergeCells('A' + row + ':G' + row);
    worksheet.getCell('A' + row).value = "Nos. of Kind Packages";
    worksheet.getCell('A' + row).font = { bold: true };
    worksheet.getCell('A' + row).alignment = { horizontal: 'center' };

    worksheet.mergeCells('H' + row + ':Q' + (row + 1));
    worksheet.getCell('H' + row).value = "Total     >>>>>>>>>>";
    worksheet.getCell('H' + row).font = { bold: true };
    worksheet.getCell('H' + row).alignment = { horizontal: 'center', vertical: 'middle' };
    setOuterBorder('H' + row + ':Q' + (row + 1), worksheet);

    if (type !== "tiles") {
        setOuterBorder('R' + row + ':R' + (row + 1), worksheet);

        worksheet.mergeCells('S' + row + ':T' + row);
        worksheet.getCell('S' + row).value = { formula: `SUM(S30:S${row - 1})`, result: 0 };
        ;
        worksheet.getCell('S' + row).font = { bold: true };
        worksheet.getCell('S' + row).alignment = { horizontal: 'center' };

        setOuterBorder('U' + row + ':V' + (row + 1), worksheet);

        worksheet.mergeCells('W' + row + ':Y' + row);
        worksheet.getCell('W' + row).value = `TOTAL SQM`;
        worksheet.getCell('W' + row).font = { bold: true };
        worksheet.getCell('W' + row).alignment = { horizontal: 'center' };

        worksheet.mergeCells('W' + (row + 1) + ':Y' + (row + 1));
        worksheet.getCell('W' + (row + 1)).value = { formula: `SUM(Y30:Y${row - 1})`, result: 0 };
        ;
        worksheet.getCell('W' + (row + 1)).font = { bold: true };
        worksheet.getCell('W' + (row + 1)).alignment = { horizontal: 'center' };
        setOuterBorder('W' + row + ':Y' + (row + 1), worksheet);

        worksheet.mergeCells('Z' + row + ':Z' + (row + 1));
        if (termsOfDeliveryMain === "CIF -> FOB") {
            worksheet.getCell('Z' + row).value = `CIF ${currency}`;
            // } else if (termsOfDeliveryMain === "CNF") {
            //     worksheet.getCell('Z' + row).value = `TOTAL ${termsOfDelivery} ${currency}`;
        } else {
            worksheet.getCell('Z' + row).value = `${termsOfDelivery} ${currency}`;
        }
        worksheet.getCell('Z' + row).font = { bold: true };
        worksheet.getCell('Z' + row).alignment = { wrapText: true, horizontal: 'center', vertical: 'middle' };
        setOuterBorder('Z' + row + ':Z' + (row + 1), worksheet);

        worksheet.mergeCells('AA' + row + ':AA' + (row + 1));
        if (termsOfDeliveryMain === "CIF -> FOB") {
            worksheet.getCell('AA' + row).value = { formula: `ROUND(SUM(AA${row + 2}:AA${row + 4}), 2)`, result: 0 };
        } else {
            worksheet.getCell('AA' + row).value = { formula: `ROUND(SUM(AA28:AA${row - 1}), 2)`, result: 0 };
        }        // worksheet.getCell('AA' + row).value = {
        //   formula: `SUM(AA30:AA${row-1})`,
        //   result: 0, // optional static value
        // };
        worksheet.getCell('AA' + row).font = { bold: true };
        worksheet.getCell('AA' + row).alignment = { horizontal: 'center', vertical: 'middle' };
        setOuterBorder('AA' + row + ':AA' + (row + 1), worksheet);
    }
    else {
        worksheet.mergeCells('R' + row + ':S' + row);
        worksheet.getCell('R' + row).value = { formula: `ROUND(SUM(R30:R${row - 1}), 2)`, result: 0 };
        worksheet.getCell('R' + row).font = { bold: true };
        worksheet.getCell('R' + row).alignment = { horizontal: 'center' };

        worksheet.mergeCells('T' + row + ':U' + row);
        worksheet.getCell('T' + row).value = "UNIT TYPE";
        worksheet.getCell('T' + row).font = { bold: true };
        worksheet.getCell('T' + row).alignment = { horizontal: 'center', vertical: 'middle' };
        setOuterBorder('T' + row + ':U' + row, worksheet);

        worksheet.mergeCells('T' + (row + 1) + ':U' + (row + 1));
        worksheet.getCell('T' + (row + 1)).value = packegingType;
        worksheet.getCell('T' + (row + 1)).font = { bold: true };
        worksheet.getCell('T' + (row + 1)).alignment = { horizontal: 'center', vertical: 'middle' };
        setOuterBorder('T' + (row + 1) + ':U' + (row + 1), worksheet);

        worksheet.mergeCells('V' + row + ':X' + (row + 1));
        if (termsOfDeliveryMain === "CIF -> FOB") {
            worksheet.getCell('V' + row).value = `CIF ${currency}`;
            // } else if (termsOfDeliveryMain === "CNF") {
            //     worksheet.getCell('V' + row).value = `TOTAL ${termsOfDelivery} ${currency}`;
        } else {
            worksheet.getCell('V' + row).value = `${termsOfDelivery} ${currency}`;
        }
        worksheet.getCell('V' + row).font = { bold: true };
        worksheet.getCell('V' + row).alignment = { horizontal: 'center', vertical: 'middle' };
        setOuterBorder('V' + row + ':X' + (row + 1), worksheet);



        worksheet.mergeCells('Y' + row + ':AA' + (row + 1));
        if (termsOfDeliveryMain === "CIF -> FOB") {
            worksheet.getCell('Y' + row).value = { formula: `ROUND(SUM(Y${row + 2}:Y${row + 4}), 2)`, result: 0 };
        } else {
            worksheet.getCell('Y' + row).value = { formula: `ROUND(SUM(Y30:Y${row - 1}), 2)`, result: 0 };
        }
        worksheet.getCell('Y' + row).font = { bold: true };
        worksheet.getCell('Y' + row).alignment = { horizontal: 'center', vertical: 'middle' };
        setOuterBorder('Y' + row + ':AA' + (row + 1), worksheet);
    }
    row++;

    worksheet.mergeCells('A' + row + ':G' + row);
    if (type !== "tiles") {
        worksheet.getCell('A' + row).value = { formula: `INT(SUM(S30:S${row - 2})) & " ${unitOfIt}"`, result: `0${unitOfIt}`, };
    }
    else {
        worksheet.getCell('A' + row).value = { formula: `INT(SUM(R30:R${row - 2})) & " ${unitOfIt}"`, result: `0${unitOfIt}`, };
    }
    worksheet.getCell('A' + row).font = { bold: true };
    worksheet.getCell('A' + row).alignment = { horizontal: 'center' };
    setOuterBorder('A' + (row - 1) + ':G' + row, worksheet);

    if (type !== "tiles") {
        worksheet.mergeCells('S' + row + ':T' + row);
        worksheet.getCell('S' + row).value = unitOfIt;
        worksheet.getCell('S' + row).font = { bold: true };
        worksheet.getCell('S' + row).alignment = { horizontal: 'center' };
        setOuterBorder('S' + (row - 1) + ':T' + row, worksheet);
    }
    else {
        worksheet.mergeCells('R' + row + ':S' + row);
        worksheet.getCell('R' + row).value = unitOfIt;
        worksheet.getCell('R' + row).font = { bold: true };
        worksheet.getCell('R' + row).alignment = { horizontal: 'center' };
        setOuterBorder('R' + (row - 1) + ':S' + row, worksheet);
    }
    row++;

    worksheet.mergeCells('A' + row + ':Q' + row);
    worksheet.getCell('A' + row).value = `TOTAL ${termsOfDelivery} ${currency}:`;
    worksheet.getCell('A' + row).font = { bold: true };
    worksheet.getCell('A' + row).alignment = { horizontal: 'left' };
    setOuterBorder('A' + row + ':Q' + row, worksheet);

    if (type === "sanitary" && termsOfDelivery === "CIF") {
        setOuterBorder('R' + row + ':R' + row, worksheet);
        setOuterBorder('S' + row + ':Y' + row, worksheet);

        worksheet.mergeCells('Z' + row + ':Z' + row);
        worksheet.getCell('Z' + row).value = "INSURANCE";
        worksheet.getCell('Z' + row).font = { bold: true };
        worksheet.getCell('Z' + row).alignment = { horizontal: 'center' };
        setOuterBorder('Z' + row + ':Z' + row, worksheet);

        worksheet.mergeCells('AA' + row + ':AA' + row);
        worksheet.getCell('AA' + row).value = insurance;
        worksheet.getCell('AA' + row).font = { bold: true };
        worksheet.getCell('AA' + row).alignment = { horizontal: 'center' };
        setOuterBorder('AA' + row + ':AA' + row, worksheet);
    }
    else if (type === "tiles" && termsOfDelivery === "CIF") {
        worksheet.mergeCells('R' + row + ':X' + row);
        worksheet.getCell('R' + row).value = "INSURANCE";
        worksheet.getCell('R' + row).font = { bold: true };
        worksheet.getCell('R' + row).alignment = { horizontal: 'right' };
        setOuterBorder('R' + row + ':X' + row, worksheet);

        worksheet.mergeCells('Y' + row + ':AA' + row);
        worksheet.getCell('Y' + row).value = insurance;
        worksheet.getCell('Y' + row).font = { bold: true };
        worksheet.getCell('Y' + row).alignment = { horizontal: 'center' };
        setOuterBorder('Y' + row + ':AA' + row, worksheet);
    } else if (type === "sanitary") {
        setOuterBorder('R' + row + ':R' + row, worksheet);
        setOuterBorder('S' + row + ':Y' + row, worksheet);

        worksheet.mergeCells('Z' + row + ':Z' + row);
        setOuterBorder('Z' + row + ':Z' + row, worksheet);

        worksheet.mergeCells('AA' + row + ':AA' + row);
        setOuterBorder('AA' + row + ':AA' + row, worksheet);
    } else if (type === "tiles") {
        worksheet.mergeCells('R' + row + ':X' + row);
        setOuterBorder('R' + row + ':X' + row, worksheet);

        worksheet.mergeCells('Y' + row + ':AA' + row);
        setOuterBorder('Y' + row + ':AA' + row, worksheet);
    }
    row++;

    worksheet.mergeCells('A' + row + ':Q' + (row + 1));
    worksheet.getCell('A' + row).value = `${amountInWords}.`;
    // worksheet.getCell('A' + row).fill = {
    //     type: 'pattern',
    //     pattern: 'solid',
    //     fgColor: { argb: 'FFFFFF00' },
    // };

    worksheet.getCell('A' + row).font = { bold: true };
    worksheet.getCell('A' + row).alignment = { horizontal: 'left', vertical: 'top' };
    setOuterBorder('A' + row + ':Q' + (row + 1), worksheet);

    if (type === "sanitary") {
        worksheet.getCell('R' + row).border = {
            top: { style: 'thin', color: { argb: 'FF000000' } },     // black
            left: { style: 'thin', color: { argb: 'FF000000' } },
            bottom: { style: 'thin', color: { argb: 'FF000000' } },
            right: { style: 'thin', color: { argb: 'FF000000' } },
        };

        worksheet.getCell('R' + (row + 1)).border = {
            top: { style: 'thin', color: { argb: 'FF000000' } },     // black
            left: { style: 'thin', color: { argb: 'FF000000' } },
            bottom: { style: 'thin', color: { argb: 'FF000000' } },
            right: { style: 'thin', color: { argb: 'FF000000' } },
        };
    }

    setOuterBorder('S' + row + ':Y' + row, worksheet);

    if (type === "sanitary" && termsOfDelivery !== "FOB") {
        worksheet.mergeCells('Z' + row + ':Z' + row);
        worksheet.getCell('Z' + row).value = "FREIGHT";
        worksheet.getCell('Z' + row).font = { bold: true };
        worksheet.getCell('Z' + row).alignment = { horizontal: 'center' };
        setOuterBorder('Z' + row + ':Z' + row, worksheet);

        worksheet.mergeCells('AA' + row + ':AA' + row);
        worksheet.getCell('AA' + row).value = freight;
        worksheet.getCell('AA' + row).font = { bold: true };
        worksheet.getCell('AA' + row).alignment = { horizontal: 'center' };
        setOuterBorder('AA' + row + ':AA' + row, worksheet);
    }
    else if (type === "tiles" && termsOfDelivery !== "FOB") {
        worksheet.mergeCells('R' + row + ':X' + row);
        worksheet.getCell('R' + row).value = "FREIGHT";
        worksheet.getCell('R' + row).font = { bold: true };
        worksheet.getCell('R' + row).alignment = { horizontal: 'right' };
        setOuterBorder('R' + row + ':X' + row, worksheet);

        worksheet.mergeCells('Y' + row + ':AA' + row);
        worksheet.getCell('Y' + row).value = freight;
        worksheet.getCell('Y' + row).font = { bold: true };
        worksheet.getCell('Y' + row).alignment = { horizontal: 'center' };
        setOuterBorder('Y' + row + ':AA' + row, worksheet);
    } else if (type === "sanitary") {
        worksheet.mergeCells('Z' + row + ':Z' + row);
        setOuterBorder('Z' + row + ':Z' + row, worksheet);

        worksheet.mergeCells('AA' + row + ':AA' + row);
        setOuterBorder('AA' + row + ':AA' + row, worksheet);
    }
    else if (type === "tiles") {
        worksheet.mergeCells('R' + row + ':X' + row);
        setOuterBorder('R' + row + ':X' + row, worksheet);

        worksheet.mergeCells('Y' + row + ':AA' + row);
        setOuterBorder('Y' + row + ':AA' + row, worksheet);
    }
    row++;

    if (type === "sanitary") {
        worksheet.mergeCells('S' + row + ':Y' + row);
        if (termsOfDeliveryMain === "CIF -> FOB") {
            worksheet.getCell('S' + row).value = `TOTAL FOB ${currency}`;
        } else {
            worksheet.getCell('S' + row).value = `TOTAL ${termsOfDelivery} ${currency}`;
        }
        worksheet.getCell('S' + row).font = { bold: true };
        worksheet.getCell('S' + row).alignment = { horizontal: 'right' };
        setOuterBorder('S' + row + ':Y' + row, worksheet);

        if (termsOfDeliveryMain === "CIF -> FOB" || termsOfDeliveryMain === "FOB") {
            worksheet.getCell('AA' + row).value = { formula: `ROUND(SUM(AA28:AA${row - 5}), 4)`, result: 0 };
        } else {
            worksheet.getCell('AA' + row).value = { formula: `ROUND(SUM(AA${row - 5}:AA${row - 1}), 4)`, result: 0 };
        }
        worksheet.getCell('AA' + row).font = { bold: true };
        worksheet.getCell('AA' + row).alignment = { horizontal: 'center' };
        worksheet.getCell('AA' + row).border = {
            top: { style: 'thin', color: { argb: 'FF000000' } },     // black
            left: { style: 'thin', color: { argb: 'FF000000' } },
            bottom: { style: 'thin', color: { argb: 'FF000000' } },
            right: { style: 'thin', color: { argb: 'FF000000' } },
        };

    }
    else if (type === "tiles") {
        worksheet.mergeCells('R' + row + ':X' + row);
        if (termsOfDeliveryMain === "CIF -> FOB") {
            worksheet.getCell('R' + row).value = `TOTAL FOB ${currency}`;
        } else {
            worksheet.getCell('R' + row).value = `TOTAL ${termsOfDelivery} ${currency}`;
        }
        worksheet.getCell('R' + row).font = { bold: true };
        worksheet.getCell('R' + row).alignment = { horizontal: 'right' };
        setOuterBorder('R' + row + ':X' + row, worksheet);

        worksheet.mergeCells('Y' + row + ':AA' + row);
        // worksheet.getCell('Y' + row).value = totalFOBEuro;
        if (termsOfDeliveryMain === "CIF -> FOB" || termsOfDeliveryMain === "FOB") {
            worksheet.getCell('Y' + row).value = { formula: `ROUND(SUM(Y28:Y${row - 5}), 4)`, result: 0 };
        } else {
            worksheet.getCell('Y' + row).value = { formula: `ROUND(SUM(Y${row - 5}:Y${row - 1}), 4)`, result: 0 };
        }

        worksheet.getCell('Y' + row).font = { bold: true };
        worksheet.getCell('Y' + row).alignment = { horizontal: 'center' };
        setOuterBorder('Y' + row + ':AA' + row, worksheet);

    }

    worksheet.getCell('R' + (row + 1)).border = {
        top: { style: 'thin', color: { argb: 'FF000000' } },     // black
        left: { style: 'thin', color: { argb: 'FF000000' } },
        bottom: { style: 'thin', color: { argb: 'FF000000' } },
        right: { style: 'thin', color: { argb: 'FF000000' } },
    };

    row++;

    worksheet.mergeCells('A' + row + ':AA' + row);
    worksheet.getCell('A' + row).value = gstCirculerNumber;
    worksheet.getCell('A' + row).font = { italic: true };
    worksheet.getCell('A' + row).alignment = { horizontal: 'left' };
    setOuterBorder('A' + row + ':AA' + row, worksheet);
    row++;

    worksheet.mergeCells('A' + row + ':AA' + (row + 1));
    if (taxStatus === "without") {
        worksheet.getCell('A' + row).value = `LETTER OF UNDERTAKING NO.ACKNOWLEDGMENT FOR LUT  APPLICATION REFERENCE NUMBER (ARN) ${arn}\nDT:${lutDate}`;
    } else {
        worksheet.getCell('A' + row).value = `SUPPLY MEANT FOR EXPORT ON PAYMENT OF IGST UNDER CLAIM OF REFUND RS. TOTAL : ${gstValue}\n(TAXABLE ${termsOfDelivery} INR VALUE ${totalInINR}@ 18%)                                                                            ${gstValue}  `;
    }
    worksheet.getCell('A' + row).font = { name: 'Arial', italic: true, color: { argb: 'FFFF0000' } };
    worksheet.getCell('A' + row).alignment = { wrapText: true, horizontal: 'left', vertical: 'top' };
    setOuterBorder('A' + row + ':AA' + (row + 1), worksheet);
    row += 2;

    if (taxStatus === "with") {
        for (let i = 0; i < 4; i++) {
            worksheet.getCell('A' + (row + i)).border = {
                left: { style: 'thin', color: { argb: 'FF000000' } },
            }
        }
    }

    if (taxStatus == "without") {


        for (let i = 0; i < supplierDetails.length; i++) {
            if (type === "sanitary") {
                if (i % 2 === 0) {
                    worksheet.mergeCells('A' + row + ':Q' + row);
                    worksheet.getCell('A' + row).value = `SUPPLIER DETAILS :- ${i + 1}`;
                    worksheet.getCell('A' + row).font = { bold: true };
                    worksheet.getCell('A' + row).alignment = { horizontal: 'center' };
                    setOuterBorder('A' + row + ':Q' + row, worksheet, 'medium'); // Removable

                    worksheet.mergeCells('A' + (row + 1) + ':F' + (row + 1));
                    worksheet.getCell('A' + (row + 1)).value = "NAME:";
                    worksheet.getCell('A' + (row + 1)).font = { bold: true };
                    worksheet.getCell('A' + (row + 1)).alignment = { horizontal: 'center' };
                    setOuterBorder('A' + (row + 1) + ':F' + (row + 1), worksheet, 'medium'); // Removable

                    worksheet.mergeCells('G' + (row + 1) + ':Q' + (row + 1));
                    worksheet.getCell('G' + (row + 1)).value = supplierDetails[i][0];
                    worksheet.getCell('G' + (row + 1)).alignment = { horizontal: 'center' };
                    setOuterBorder('G' + (row + 1) + ':Q' + (row + 1), worksheet);

                    worksheet.mergeCells('A' + (row + 2) + ':F' + (row + 2));
                    worksheet.getCell('A' + (row + 2)).value = "GSTIN NO.";
                    worksheet.getCell('A' + (row + 2)).font = { bold: true };
                    worksheet.getCell('A' + (row + 2)).alignment = { horizontal: 'center' };
                    setOuterBorder('A' + (row + 2) + ':F' + (row + 2), worksheet, 'medium'); // Removable

                    worksheet.mergeCells('G' + (row + 2) + ':Q' + (row + 2));
                    worksheet.getCell('G' + (row + 2)).value = supplierDetails[i][1];
                    worksheet.getCell('G' + (row + 2)).alignment = { horizontal: 'center' };
                    setOuterBorder('G' + (row + 2) + ':Q' + (row + 2), worksheet);

                    worksheet.mergeCells('A' + (row + 3) + ':F' + (row + 3));
                    worksheet.getCell('A' + (row + 3)).value = "TAX INVOICE NO & DATE:";
                    worksheet.getCell('A' + (row + 3)).font = { bold: true };
                    worksheet.getCell('A' + (row + 3)).alignment = { horizontal: 'center' };
                    setOuterBorder('A' + (row + 3) + ':F' + (row + 3), worksheet, 'medium'); // Removable

                    worksheet.mergeCells('G' + (row + 3) + ':K' + (row + 3));
                    worksheet.getCell('G' + (row + 3)).value = supplierDetails[i][2];
                    // worksheet.getCell('G' + (row + 3)).fill = {
                    //     type: 'pattern',
                    //     pattern: 'solid',
                    //     fgColor: { argb: 'FFFFFF00' }, // Yellow fill
                    // };
                    worksheet.getCell('G' + (row + 3)).alignment = { horizontal: 'center' };
                    setOuterBorder('G' + (row + 3) + ':K' + (row + 3), worksheet);

                    worksheet.mergeCells('L' + (row + 3) + ':Q' + (row + 3));
                    worksheet.getCell('L' + (row + 3)).value = supplierDetails[i][3];
                    // worksheet.getCell('L' + (row + 3)).fill = {
                    //     type: 'pattern',
                    //     pattern: 'solid',
                    //     fgColor: { argb: 'FFFFFF00' }, // Yellow fill
                    // };
                    worksheet.getCell('L' + (row + 3)).alignment = { horizontal: 'center' };
                    setOuterBorder('L' + (row + 3) + ':Q' + (row + 3), worksheet);
                } else {
                    worksheet.mergeCells('R' + row + ':AA' + row);
                    worksheet.getCell('R' + row).value = `SUPPLIER DETAILS :- ${i + 1}`;
                    worksheet.getCell('R' + row).font = { bold: true };
                    worksheet.getCell('R' + row).alignment = { horizontal: 'center' };
                    setOuterBorder('R' + row + ':AA' + row, worksheet, 'medium'); // Removable

                    worksheet.mergeCells('R' + (row + 1) + ':U' + (row + 1));
                    worksheet.getCell('R' + (row + 1)).value = "NAME:";
                    worksheet.getCell('R' + (row + 1)).font = { bold: true };
                    worksheet.getCell('R' + (row + 1)).alignment = { horizontal: 'center' };
                    setOuterBorder('R' + (row + 1) + ':U' + (row + 1), worksheet, 'medium'); // Removable

                    worksheet.mergeCells('V' + (row + 1) + ':AA' + (row + 1));
                    worksheet.getCell('V' + (row + 1)).value = supplierDetails[i][0];
                    worksheet.getCell('V' + (row + 1)).alignment = { horizontal: 'center' };
                    setOuterBorder('V' + (row + 1) + ':AA' + (row + 1), worksheet);

                    worksheet.mergeCells('R' + (row + 2) + ':U' + (row + 2));
                    worksheet.getCell('R' + (row + 2)).value = "GSTIN NO.";
                    worksheet.getCell('R' + (row + 2)).font = { bold: true };
                    worksheet.getCell('R' + (row + 2)).alignment = { horizontal: 'center' };
                    setOuterBorder('R' + (row + 2) + ':U' + (row + 2), worksheet, 'medium'); // Removable

                    worksheet.mergeCells('V' + (row + 2) + ':AA' + (row + 2));
                    worksheet.getCell('V' + (row + 2)).value = supplierDetails[i][1];
                    worksheet.getCell('V' + (row + 2)).alignment = { horizontal: 'center' };
                    setOuterBorder('V' + (row + 2) + ':AA' + (row + 2), worksheet);

                    worksheet.mergeCells('R' + (row + 3) + ':U' + (row + 3));
                    worksheet.getCell('R' + (row + 3)).value = "TAX INVOICE NO & DATE:";
                    worksheet.getCell('R' + (row + 3)).font = { bold: true };
                    worksheet.getCell('R' + (row + 3)).alignment = { horizontal: 'center' };
                    setOuterBorder('R' + (row + 3) + ':U' + (row + 3), worksheet, 'medium'); // Removable

                    worksheet.mergeCells('V' + (row + 3) + ':Y' + (row + 3));
                    worksheet.getCell('V' + (row + 3)).value = supplierDetails[i][2];
                    // worksheet.getCell('V' + (row + 3)).fill = {
                    //     type: 'pattern',
                    //     pattern: 'solid',
                    //     fgColor: { argb: 'FFFFFF00' }, // Yellow fill
                    // };
                    worksheet.getCell('V' + (row + 3)).alignment = { horizontal: 'center' };
                    setOuterBorder('V' + (row + 3) + ':Y' + (row + 3), worksheet);

                    worksheet.mergeCells('Z' + (row + 3) + ':AA' + (row + 3));
                    worksheet.getCell('Z' + (row + 3)).value = supplierDetails[i][3];
                    // worksheet.getCell('Z' + (row + 3)).fill = {
                    //     type: 'pattern',
                    //     pattern: 'solid',
                    //     fgColor: { argb: 'FFFFFF00' }, // Yellow fill
                    // };
                    worksheet.getCell('Z' + (row + 3)).alignment = { horizontal: 'center' };
                    setOuterBorder('Z' + (row + 3) + ':AA' + (row + 3), worksheet);
                    row += 4;
                }
            }
            else if (type === "tiles") {
                if (i % 2 === 0) {
                    worksheet.mergeCells('A' + row + ':M' + row);
                    worksheet.getCell('A' + row).value = `SUPPLIER DETAILS :- ${i + 1}`;
                    worksheet.getCell('A' + row).font = { bold: true };
                    worksheet.getCell('A' + row).alignment = { horizontal: 'center' };
                    setOuterBorder('A' + row + ':M' + row, worksheet, 'medium'); // Removable

                    worksheet.mergeCells('A' + (row + 1) + ':E' + (row + 1));
                    worksheet.getCell('A' + (row + 1)).value = "NAME:";
                    worksheet.getCell('A' + (row + 1)).font = { bold: true };
                    worksheet.getCell('A' + (row + 1)).alignment = { horizontal: 'center' };
                    setOuterBorder('A' + (row + 1) + ':E' + (row + 1), worksheet, 'medium'); // Removable

                    worksheet.mergeCells('F' + (row + 1) + ':M' + (row + 1));
                    worksheet.getCell('F' + (row + 1)).value = supplierDetails[i][0];
                    worksheet.getCell('F' + (row + 1)).alignment = { horizontal: 'center' };
                    setOuterBorder('F' + (row + 1) + ':M' + (row + 1), worksheet);

                    worksheet.mergeCells('A' + (row + 2) + ':E' + (row + 2));
                    worksheet.getCell('A' + (row + 2)).value = "GSTIN NO.";
                    worksheet.getCell('A' + (row + 2)).font = { bold: true };
                    worksheet.getCell('A' + (row + 2)).alignment = { horizontal: 'center' };
                    setOuterBorder('A' + (row + 2) + ':E' + (row + 2), worksheet, 'medium'); // Removable

                    worksheet.mergeCells('F' + (row + 2) + ':M' + (row + 2));
                    worksheet.getCell('F' + (row + 2)).value = supplierDetails[i][1];
                    worksheet.getCell('F' + (row + 2)).alignment = { horizontal: 'center' };
                    setOuterBorder('F' + (row + 2) + ':M' + (row + 2), worksheet);

                    worksheet.mergeCells('A' + (row + 3) + ':E' + (row + 3));
                    worksheet.getCell('A' + (row + 3)).value = "TAX INVOICE NO & DATE:";
                    worksheet.getCell('A' + (row + 3)).font = { bold: true };
                    worksheet.getCell('A' + (row + 3)).alignment = { horizontal: 'center' };
                    setOuterBorder('A' + (row + 3) + ':E' + (row + 3), worksheet, 'medium'); // Removable

                    worksheet.mergeCells('F' + (row + 3) + ':I' + (row + 3));
                    worksheet.getCell('F' + (row + 3)).value = supplierDetails[i][2];
                    // worksheet.getCell('F' + (row + 3)).fill = {
                    //     type: 'pattern',
                    //     pattern: 'solid',
                    //     fgColor: { argb: 'FFFFFF00' }, // Yellow fill
                    // };
                    worksheet.getCell('F' + (row + 3)).alignment = { horizontal: 'center' };
                    setOuterBorder('F' + (row + 3) + ':I' + (row + 3), worksheet);

                    worksheet.mergeCells('J' + (row + 3) + ':M' + (row + 3));
                    worksheet.getCell('J' + (row + 3)).value = supplierDetails[i][3];
                    // worksheet.getCell('J' + (row + 3)).fill = {
                    //     type: 'pattern',
                    //     pattern: 'solid',
                    //     fgColor: { argb: 'FFFFFF00' }, // Yellow fill
                    // };
                    worksheet.getCell('J' + (row + 3)).alignment = { horizontal: 'center' };
                    setOuterBorder('J' + (row + 3) + ':M' + (row + 3), worksheet);
                } else {
                    worksheet.mergeCells('N' + row + ':AA' + row);
                    worksheet.getCell('N' + row).value = `SUPPLIER DETAILS :- ${i + 1}`;
                    worksheet.getCell('N' + row).font = { bold: true };
                    worksheet.getCell('N' + row).alignment = { horizontal: 'center' };
                    setOuterBorder('N' + row + ':AA' + row, worksheet, 'medium'); // Removable

                    worksheet.mergeCells('N' + (row + 1) + ':S' + (row + 1));
                    worksheet.getCell('N' + (row + 1)).value = "NAME:";
                    worksheet.getCell('N' + (row + 1)).font = { bold: true };
                    worksheet.getCell('N' + (row + 1)).alignment = { horizontal: 'center' };
                    setOuterBorder('N' + (row + 1) + ':S' + (row + 1), worksheet, 'medium'); // Removable

                    worksheet.mergeCells('T' + (row + 1) + ':AA' + (row + 1));
                    worksheet.getCell('T' + (row + 1)).value = supplierDetails[i][0];
                    worksheet.getCell('T' + (row + 1)).alignment = { horizontal: 'center' };
                    setOuterBorder('T' + (row + 1) + ':AA' + (row + 1), worksheet);

                    worksheet.mergeCells('N' + (row + 2) + ':S' + (row + 2));
                    worksheet.getCell('N' + (row + 2)).value = "GSTIN NO.";
                    worksheet.getCell('N' + (row + 2)).font = { bold: true };
                    worksheet.getCell('N' + (row + 2)).alignment = { horizontal: 'center' };
                    setOuterBorder('N' + (row + 2) + ':S' + (row + 2), worksheet, 'medium'); // Removable

                    worksheet.mergeCells('T' + (row + 2) + ':AA' + (row + 2));
                    worksheet.getCell('T' + (row + 2)).value = supplierDetails[i][1];
                    worksheet.getCell('T' + (row + 2)).alignment = { horizontal: 'center' };
                    setOuterBorder('T' + (row + 2) + ':AA' + (row + 2), worksheet);

                    worksheet.mergeCells('N' + (row + 3) + ':S' + (row + 3));
                    worksheet.getCell('N' + (row + 3)).value = "TAX INVOICE NO & DATE:";
                    worksheet.getCell('N' + (row + 3)).font = { bold: true };
                    worksheet.getCell('N' + (row + 3)).alignment = { horizontal: 'center' };
                    setOuterBorder('N' + (row + 3) + ':S' + (row + 3), worksheet, 'medium'); // Removable

                    worksheet.mergeCells('T' + (row + 3) + ':W' + (row + 3));
                    worksheet.getCell('T' + (row + 3)).value = supplierDetails[i][2];
                    // worksheet.getCell('T' + (row + 3)).fill = {
                    //     type: 'pattern',
                    //     pattern: 'solid',
                    //     fgColor: { argb: 'FFFFFF00' }, // Yellow fill
                    // };
                    worksheet.getCell('T' + (row + 3)).alignment = { horizontal: 'center' };
                    setOuterBorder('T' + (row + 3) + ':W' + (row + 3), worksheet);

                    worksheet.mergeCells('X' + (row + 3) + ':AA' + (row + 3));
                    worksheet.getCell('X' + (row + 3)).value = supplierDetails[i][3];
                    // worksheet.getCell('X' + (row + 3)).fill = {
                    //     type: 'pattern',
                    //     pattern: 'solid',
                    //     fgColor: { argb: 'FFFFFF00' }, // Yellow fill
                    // };
                    worksheet.getCell('X' + (row + 3)).alignment = { horizontal: 'center' };
                    setOuterBorder('X' + (row + 3) + ':AA' + (row + 3), worksheet);
                    row += 4;
                }
            }
        }

    }

    if (supplierDetails.length % 2 === 0 || supplierDetails.length == 0) {
        if (type == "tiles") {
            worksheet.mergeCells('A' + row + ':M' + row);
            setOuterBorder('A' + row + ':M' + row, worksheet);

            worksheet.mergeCells('A' + (row + 1) + ':E' + (row + 1));
            setOuterBorder('A' + (row + 1) + ':E' + (row + 1), worksheet);

            worksheet.mergeCells('F' + (row + 1) + ':M' + (row + 1));
            setOuterBorder('F' + (row + 1) + ':M' + (row + 1), worksheet);

            worksheet.mergeCells('A' + (row + 2) + ':E' + (row + 2));
            setOuterBorder('A' + (row + 2) + ':E' + (row + 2), worksheet);

            worksheet.mergeCells('F' + (row + 2) + ':M' + (row + 2));
            setOuterBorder('F' + (row + 2) + ':M' + (row + 2), worksheet);

            worksheet.mergeCells('A' + (row + 3) + ':E' + (row + 3));
            setOuterBorder('A' + (row + 3) + ':E' + (row + 3), worksheet);

            worksheet.mergeCells('F' + (row + 3) + ':I' + (row + 3));
            // worksheet.getCell('F' + (row + 3)).fill = {
            //     type: 'pattern',
            //     pattern: 'solid',
            //     fgColor: { argb: 'FFFFFF00' }, // Yellow fill
            // };
            setOuterBorder('F' + (row + 3) + ':I' + (row + 3), worksheet);

            worksheet.mergeCells('J' + (row + 3) + ':M' + (row + 3));
            // worksheet.getCell('J' + (row + 3)).fill = {
            //     type: 'pattern',
            //     pattern: 'solid',
            //     fgColor: { argb: 'FFFFFF00' }, // Yellow fill
            // };
            setOuterBorder('J' + (row + 3) + ':M' + (row + 3), worksheet);
        } else {
            worksheet.mergeCells('A' + row + ':Q' + row);
            setOuterBorder('A' + row + ':Q' + row, worksheet);

            worksheet.mergeCells('A' + (row + 1) + ':F' + (row + 1));
            setOuterBorder('A' + (row + 1) + ':F' + (row + 1), worksheet);

            worksheet.mergeCells('G' + (row + 1) + ':Q' + (row + 1));
            setOuterBorder('G' + (row + 1) + ':Q' + (row + 1), worksheet);

            worksheet.mergeCells('A' + (row + 2) + ':F' + (row + 2));
            setOuterBorder('A' + (row + 2) + ':F' + (row + 2), worksheet);

            worksheet.mergeCells('G' + (row + 2) + ':Q' + (row + 2));
            setOuterBorder('G' + (row + 2) + ':Q' + (row + 2), worksheet);

            worksheet.mergeCells('A' + (row + 3) + ':F' + (row + 3));
            setOuterBorder('A' + (row + 3) + ':F' + (row + 3), worksheet);

            worksheet.mergeCells('G' + (row + 3) + ':K' + (row + 3));
            // worksheet.getCell('G' + (row + 3)).fill = {
            //     type: 'pattern',
            //     pattern: 'solid',
            //     fgColor: { argb: 'FFFFFF00' }, // Yellow fill
            // };
            setOuterBorder('G' + (row + 3) + ':K' + (row + 3), worksheet);

            worksheet.mergeCells('L' + (row + 3) + ':Q' + (row + 3));
            // worksheet.getCell('L' + (row + 3)).fill = {
            //     type: 'pattern',
            //     pattern: 'solid',
            //     fgColor: { argb: 'FFFFFF00' }, // Yellow fill
            // };
            setOuterBorder('L' + (row + 3) + ':Q' + (row + 3), worksheet);
        }
    }
    if (type === "sanitary") {
        worksheet.mergeCells('R' + row + ':AA' + row);
        worksheet.getCell('R' + row).value = "Signature & Date";
        worksheet.getCell('R' + row).font = { bold: true };
        worksheet.getCell('R' + row).alignment = { horizontal: 'right' };
        row++;

        worksheet.mergeCells('R' + row + ':AA' + row);
        worksheet.getCell('R' + row).value = "For, ZERIC CERAMICA";
        worksheet.getCell('R' + row).font = { bold: true };
        worksheet.getCell('R' + row).alignment = { horizontal: 'right' };

        worksheet.addImage(signature, {
            tl: { col: 24, row: (row - 1) }, // X66 (X = col 24 → 24 - 1 = 23 → 22 for 0-based)
            ext: { width: 100, height: 100 }, // adjust size as needed
        });
        row += 5;

        worksheet.mergeCells('R' + row + ':AA' + row);
        worksheet.getCell('R' + row).value = "AUTHORISED SIGN.";
        worksheet.getCell('R' + row).font = { bold: true };
        worksheet.getCell('R' + row).alignment = { horizontal: 'right' };
        setOuterBorder('R' + (row - 6) + ':AA' + row, worksheet);


        worksheet.mergeCells('A' + (row - 1) + ':Q' + row);
        worksheet.getCell('A' + (row - 1)).value = "Declaration:We declare that this invoice shows the actual price of the goods described and that all particulars are true and correct.";
        worksheet.getCell('A' + (row - 1)).font = { bold: true };
        worksheet.getCell('A' + (row - 1)).alignment = { wrapText: true, horizontal: 'left', vertical: 'top' };
        setOuterBorder('A' + (row - 1) + ':Q' + row, worksheet);
        setOuterBorder('A' + (row - 2) + ':Q' + (row - 2), worksheet);
    }
    else if (type === "tiles") {
        worksheet.mergeCells('N' + row + ':AA' + row);
        worksheet.getCell('N' + row).value = "Signature & Date";
        worksheet.getCell('N' + row).font = { bold: true };
        worksheet.getCell('N' + row).alignment = { horizontal: 'right' };
        row++;

        worksheet.mergeCells('N' + row + ':AA' + row);
        worksheet.getCell('N' + row).value = "For, ZERIC CERAMICA";
        worksheet.getCell('N' + row).font = { bold: true };
        worksheet.getCell('N' + row).alignment = { horizontal: 'right' };

        worksheet.addImage(signature, {
            tl: { col: 20, row: (row - 1) }, // X66 (X = col 24 → 24 - 1 = 23 → 22 for 0-based)
            ext: { width: 100, height: 100 }, // adjust size as needed
        });
        row += 5;

        worksheet.mergeCells('N' + row + ':AA' + row);
        worksheet.getCell('N' + row).value = "AUTHORISED SIGN.";
        worksheet.getCell('N' + row).font = { bold: true };
        worksheet.getCell('N' + row).alignment = { horizontal: 'right' };
        setOuterBorder('N' + (row - 6) + ':AA' + row, worksheet);


        worksheet.mergeCells('A' + (row - 1) + ':M' + row);
        worksheet.getCell('A' + (row - 1)).value = "Declaration:We declare that this invoice shows the actual price of the goods described and that all particulars are true and correct.";
        worksheet.getCell('A' + (row - 1)).font = { bold: true };
        worksheet.getCell('A' + (row - 1)).alignment = { wrapText: true, horizontal: 'left', vertical: 'top' };
        setOuterBorder('A' + (row - 1) + ':M' + row, worksheet);
        setOuterBorder('A' + (row - 2) + ':M' + (row - 2), worksheet);
    }

    setOuterBorder('A1:AA' + row, worksheet, 'medium');

    worksheet.pageSetup.fitToPage = true;

    let MAX_WIDTH = 5;
    if (type === "tiles") {

        worksheet.columns.forEach((column) => {
            let maxLength = 10;

            column.eachCell({ includeEmpty: true }, (cell) => {
                const cellValue = cell.value ? cell.value.toString() : '';
                const lines = cellValue.split('\n');
                const longestLine = Math.max(...lines.map(line => line.length));
                if (longestLine > maxLength) {
                    maxLength = longestLine;
                }
            });

            column.width = Math.min(maxLength + 2, MAX_WIDTH); // 👈 LIMIT IT
        });
        worksheet.getColumn(1).width = pixelToExcelWidth(50);
    }
    else if (type === "sanitary") {
        columnWidths.forEach((px, index) => {
            worksheet.getColumn(index + 1).width = pixelToExcelWidth(px);
        });
    }

    setGlobalFontSize(worksheet);










































































    // Create a new workbook

    // The sheet comes off the workbook rather than the local binding: in some
    // sections that binding is declared inside a conditional and is not in
    // scope here. It is the same object either way.
    return {
        workbook: workbook,
        sheet: workbook.worksheets[0],
        state: { ...state, srNo, row, hsnCode, allProductsType, skipRow, addSkipRow, MAX_WIDTH },
        built: {
            ...built,
            workbook: workbook,
            worksheet: workbook.worksheets[0]
        }
    }
}
