/* eslint-disable */
// @ts-nocheck
// GENERATED by scripts/split-generator.mjs from ui/src/lib/excelGenerator.ts.
// The body below is a verbatim copy. Do not edit or reformat it by hand —
// re-run `npm run docs:split` instead. The original was written with
// TypeScript strictness disabled, so it is excluded from type checking;
// correctness is established by scripts/compare-generators.mts, which diffs
// every cell against the original generator.
// Source lines 4110-4847.

import ExcelJS from 'exceljs'
import { format } from 'date-fns'
import { convertNamesToInitials, formatNames, round3 } from '../helpers'
import { loadImageBuffer } from '../loadImageBuffer'
import type { DocumentContext } from '../context'
import type { SheetState } from '../state'

void ExcelJS
void format
void round3
void convertNamesToInitials
void formatNames
void loadImageBuffer

export const buildPackingList = async (
  ctx: DocumentContext,
  state: SheetState,
  built: Record<string, any> = {}
): Promise<{ workbook: any; sheet: any; state: SheetState; built: Record<string, any> }> => {
    void built
    const {
        companyName,
        companyAddress,
        email,
        taxid,
        ieCode,
        panNo,
        gstinNo,
        stateCode,
        invoiceNo,
        invoiceDate,
        buyersOrderNo,
        buyersOrderDate,
        poNo,
        formattedNotifyParty,
        preCarriage,
        vassalFlightNo,
        placeOfReceipt,
        portOfLoading,
        portOfDischarge,
        finalDestination,
        termsOfDelivery,
        termsOfDeliveryMainAt,
        paymentTerms,
        shippingMethod,
        containerType,
        marksAndNos,
        products,
        containerDetails,
        totalPallet,
        packegingType,
        taxStatus,
        type,
        signatureUrl,
        configurePrintSheet,
        setGlobalFontSize,
        pixelToExcelWidth,
        setOuterBorder
    } = ctx
    let { srNo, row, hsnCode, MAX_WIDTH } = state
    const { workbook } = built
    let signature: any, vgnSignatureW: any, vgnSignatureH: any

    const packingListWorkbook = new ExcelJS.Workbook();
    // New tab : PACKING LIST
    const packingList = packingListWorkbook.addWorksheet('PACKING LIST');
    if (signatureUrl) {

        const { buffer, extension, width, height } = await loadImageBuffer(signatureUrl);
        signature = packingListWorkbook.addImage({
            buffer: buffer,
            extension: extension,
        });
        vgnSignatureW = width;
        vgnSignatureH = height;

    }

    packingList.mergeCells('A1:AA1');
    packingList.getCell('A1').value = 'PACKING LIST';
    packingList.getCell('A1').font = { bold: true };
    packingList.getCell('A1').alignment = { horizontal: 'center' };
    setOuterBorder('A1:AA1', packingList);

    packingList.mergeCells('A2:M9');
    packingList.getCell('A2').value = `EXPORTER:\n${companyName}\n${companyAddress}`;
    packingList.getCell('A2').alignment = { wrapText: true, vertical: 'top' };
    packingList.getCell('A2').font = { bold: true };
    setOuterBorder('A2:M9', packingList);

    // ✅ Email & Tax No
    packingList.mergeCells('A10:B10');
    packingList.getCell('A10').value = `EMAIL:`;
    packingList.getCell('A10').font = { bold: true };
    packingList.getCell('A10').alignment = { wrapText: true };

    packingList.mergeCells('A11:B11');
    packingList.getCell('A11').value = `TAX ID:`;
    packingList.getCell('A11').font = { bold: true };
    packingList.getCell('A11').alignment = { wrapText: true };

    packingList.mergeCells('C10:M10');
    packingList.getCell('C10').value = email;
    packingList.getCell('C10').alignment = { wrapText: true };

    packingList.mergeCells('C11:M11');
    packingList.getCell('C11').value = taxid;
    packingList.getCell('C11').alignment = { wrapText: true };
    setOuterBorder('A10:M11', packingList);

    // ✅ Invoice No. & Date
    packingList.mergeCells('N2:T2');
    packingList.getCell('N2').value = "Invoice No. & Date:";
    packingList.getCell('N2').font = { bold: true };
    packingList.getCell('N2').alignment = { horizontal: 'center' };

    packingList.mergeCells('N3:T3');
    packingList.getCell('N3').value = `${invoiceNo}`;

    packingList.mergeCells('N4:T4');
    packingList.getCell('N4').value = `Dt. ${invoiceDate}`;

    setOuterBorder('N2:T4', packingList);

    // ✅ Exporter's Ref
    packingList.mergeCells('U2:AA2');
    packingList.getCell('U2').value = "Exporter’s Ref.:";
    packingList.getCell('U2').font = { bold: true };

    packingList.mergeCells('U3:AA11');
    packingList.getCell('U3').value = `I. E. Code #: ${ieCode}\nPAN No #: ${panNo}\nGSTIN No #: ${gstinNo}\nSTATE CODE : ${stateCode}`;
    packingList.getCell('U3').alignment = { wrapText: true, vertical: 'top' };
    setOuterBorder('U2:AA11', packingList);

    // ✅ Buyer's Order No
    packingList.mergeCells('N5:T5');
    packingList.getCell('N5').value = "Buyer's Order no. & Date";
    packingList.getCell('N5').font = { bold: true };

    packingList.mergeCells('N6:T7');
    packingList.getCell('N6').value = `${buyersOrderNo}    ${buyersOrderDate}`;
    packingList.getCell('N6').alignment = { wrapText: true, vertical: 'top' };

    packingList.mergeCells('N11:T11');
    packingList.getCell('N11').value = `PO No: ${poNo}`;
    setOuterBorder('N5:T11', packingList);

    // ✅ Consignee
    packingList.mergeCells('A12:M12');
    packingList.getCell('A12').value = "Consignee:";
    packingList.getCell('A12').font = { bold: true };

    packingList.mergeCells('A13:M18');
    packingList.getCell('A13').value = `TO THE ORDER`;
    packingList.getCell('A13').alignment = { wrapText: true, vertical: 'top' };
    setOuterBorder('A12:M18', packingList);

    // ✅ Notify Party
    packingList.mergeCells('N12:AA12');
    packingList.getCell('N12').value = "Notify Party # :";
    packingList.getCell('N12').font = { bold: true };

    packingList.mergeCells('N13:AA18');
    packingList.getCell('N13').value = `${formattedNotifyParty}`;
    packingList.getCell('N13').alignment = { wrapText: true, vertical: 'top' };
    setOuterBorder('N12:AA18', packingList);

    packingList.mergeCells('A19:F19');
    packingList.getCell('A19').value = 'Pre-Carriage By';
    packingList.getCell('A19').alignment = { horizontal: 'center' };

    packingList.mergeCells('A20:F20');
    packingList.getCell('A20').value = `${preCarriage}`;
    packingList.getCell('A20').font = { bold: true };
    packingList.getCell('A20').alignment = { horizontal: 'center' };
    setOuterBorder('A19:F20', packingList);

    packingList.mergeCells('G19:M19');
    packingList.getCell('G19').value = "Place of Receipt by Pre-Carrier";
    packingList.getCell('G19').alignment = { horizontal: 'center' };

    packingList.mergeCells('G20:M20');
    packingList.getCell('G20').value = `${placeOfReceipt}`;
    packingList.getCell('G20').font = { bold: true };
    packingList.getCell('G20').alignment = { horizontal: 'center' };
    setOuterBorder('G19:M20', packingList);

    packingList.mergeCells('N19:V19');
    packingList.getCell('N19').value = "Country of Origin of Goods : INDIA";
    packingList.getCell('N19').alignment = { horizontal: 'center' };

    packingList.mergeCells('N20:V20');
    packingList.getCell('N20').value = `ORIGIN : DISTRICT MORBI, STATE GUJARAT`;
    packingList.getCell('N20').font = { bold: true };
    packingList.getCell('N20').alignment = { horizontal: 'center' };
    setOuterBorder('N19:V20', packingList);

    packingList.mergeCells('W19:AA19');
    packingList.getCell('W19').value = "Country of Final Destination";
    packingList.getCell('W19').alignment = { horizontal: 'center' };

    packingList.mergeCells('W20:AA20');
    packingList.getCell('W20').value = `${finalDestination}`;
    packingList.getCell('W20').font = { bold: true };
    packingList.getCell('W20').alignment = { horizontal: 'center' };
    setOuterBorder('W19:AA20', packingList);

    packingList.mergeCells('A21:F21');
    packingList.getCell('A21').value = 'Vessel Flight No.';
    packingList.getCell('A21').alignment = { horizontal: 'center' };

    packingList.mergeCells('A22:F22');
    packingList.getCell('A22').value = `${vassalFlightNo}`;
    packingList.getCell('A22').font = { bold: true };
    packingList.getCell('A22').alignment = { horizontal: 'center' };
    setOuterBorder('A21:F22', packingList);

    packingList.mergeCells('G21:M21');
    packingList.getCell('G21').value = "Port of Loading";
    packingList.getCell('G21').alignment = { horizontal: 'center' };

    packingList.mergeCells('G22:M22');
    packingList.getCell('G22').value = `${portOfLoading}`;
    packingList.getCell('G22').font = { bold: true };
    packingList.getCell('G22').alignment = { horizontal: 'center' };
    setOuterBorder('G21:M22', packingList);

    packingList.mergeCells('A23:F23');
    packingList.getCell('A23').value = 'Port of Discharge';
    packingList.getCell('A23').alignment = { horizontal: 'center' };

    packingList.mergeCells('A24:F25');
    packingList.getCell('A24').value = `${portOfDischarge}`;
    packingList.getCell('A24').font = { bold: true };
    packingList.getCell('A24').alignment = { horizontal: 'center', vertical: 'middle' };
    setOuterBorder('A23:F25', packingList);

    packingList.mergeCells('G23:M23');
    packingList.getCell('G23').value = "Final Destination";
    packingList.getCell('G23').alignment = { horizontal: 'center' };

    packingList.mergeCells('G24:M25');
    packingList.getCell('G24').value = `${finalDestination}`;
    packingList.getCell('G24').font = { bold: true };
    packingList.getCell('G24').alignment = { horizontal: 'center', vertical: 'middle' };
    setOuterBorder('G23:M25', packingList);

    packingList.mergeCells('N21:AA21');
    packingList.getCell('N21').value = "Terms of Delivery & Payment :-";
    // packingList.getCell('N21').font = { bold: true };

    packingList.mergeCells('N22:AA22');
    if (termsOfDelivery === "FOB") {
        packingList.getCell('N22').value = termsOfDeliveryMainAt;
    } else {
        packingList.getCell('N22').value = termsOfDeliveryMainAt;
    }

    packingList.mergeCells('N23:AA24');
    packingList.getCell('N23').value = `PAYMENT : ${paymentTerms}`;
    packingList.getCell('N23').alignment = { wrapText: true, vertical: 'top' };

    packingList.mergeCells('N25:V25');
    packingList.getCell('N25').value = shippingMethod;
    packingList.getCell('N25').font = { bold: true };
    setOuterBorder('N21:AA25', packingList);

    configurePrintSheet(packingList);

    packingList.mergeCells('A26:D26');
    packingList.getCell('A26').value = "Marks & Nos.";
    packingList.getCell('A26').font = { bold: true };
    packingList.getCell('A26').alignment = { horizontal: 'center' };

    if (containerType === 'FCL') {
        packingList.mergeCells('A27:D27');
        packingList.getCell('A27').value = `${marksAndNos} ${containerType}`;
        packingList.getCell('A27').font = { bold: true };
        packingList.getCell('A27').alignment = { horizontal: 'center' };
        setOuterBorder('A26:D27', packingList);
    } else {
        packingList.mergeCells('A27:D27');
        packingList.getCell('A27').value = containerType;
        packingList.getCell('A27').font = { bold: true };
        packingList.getCell('A27').alignment = { horizontal: 'center' };
        setOuterBorder('A26:D27', packingList);
    }

    packingList.mergeCells('E26:P27');
    packingList.getCell('E26').value = "Description of Goods";
    packingList.getCell('E26').font = { bold: true };
    packingList.getCell('E26').alignment = { horizontal: 'center', vertical: 'middle' };
    setOuterBorder('E26:P27', packingList);

    packingList.mergeCells('Q26:U26');
    packingList.getCell('Q26').value = "QUANTITY";
    packingList.getCell('Q26').font = { bold: true };
    packingList.getCell('Q26').alignment = { horizontal: 'center' };

    packingList.mergeCells('Q27:U27');
    packingList.getCell('Q27').value = packegingType;
    packingList.getCell('Q27').font = { bold: true };
    packingList.getCell('Q27').alignment = { horizontal: 'center' };
    setOuterBorder('Q26:U27', packingList);

    packingList.mergeCells('V26:X26');
    packingList.getCell('V26').value = "NET. WT.";
    packingList.getCell('V26').font = { bold: true };
    packingList.getCell('V26').alignment = { horizontal: 'center' };

    packingList.mergeCells('V27:X27');
    packingList.getCell('V27').value = "IN KGS.";
    packingList.getCell('V27').font = { bold: true };
    packingList.getCell('V27').alignment = { horizontal: 'center' };
    setOuterBorder('V26:X27', packingList);

    packingList.mergeCells('Y26:AA26');
    packingList.getCell('Y26').value = "GRS. WT.";
    packingList.getCell('Y26').font = { bold: true };
    packingList.getCell('Y26').alignment = { horizontal: 'center' };

    packingList.mergeCells('Y27:AA27');
    packingList.getCell('Y27').value = "IN KGS.";
    packingList.getCell('Y27').font = { bold: true };
    packingList.getCell('Y27').alignment = { horizontal: 'center' };
    setOuterBorder('Y26:AA27', packingList);

    packingList.getCell('A28').value = "SR NO.";
    packingList.getCell('A28').font = { bold: true };
    packingList.getCell('A28').alignment = { horizontal: 'center', vertical: 'middle' };
    packingList.getCell('A28').border = {
        top: { style: 'thin', color: { argb: 'FF000000' } },
        left: { style: 'thin', color: { argb: 'FF000000' } },
        bottom: { style: 'thin', color: { argb: 'FF000000' } },
        right: { style: 'thin', color: { argb: 'FF000000' } },
    };

    packingList.mergeCells('B28:D28');
    packingList.getCell('B28').value = "HSN CODE";
    packingList.getCell('B28').font = { bold: true };
    packingList.getCell('B28').alignment = { horizontal: 'center', vertical: 'middle' };
    setOuterBorder('B28:D28', packingList);


    row = 27;
    srNo = 1;
    for (let i = 0; i < products.length; i++) {
        row++;
        if (products[i].length === 2) {
            packingList.mergeCells('E' + row + ':P' + row);
            packingList.getCell('E' + row).value = products[i][0];
            packingList.getCell('E' + row).font = { bold: true, size: 12 };
            packingList.getCell('E' + row).alignment = { horizontal: 'center', vertical: 'middle' };
            packingList.getRow(row).height = 46;
            setOuterBorder('E' + row + ':P' + row, packingList);
            hsnCode = Number(products[i][1]);

            if (i !== 0) {
                packingList.getCell('A' + row).border = {
                    top: { style: 'thin', color: { argb: 'FF000000' } },     // black
                    left: { style: 'thin', color: { argb: 'FF000000' } },
                    bottom: { style: 'thin', color: { argb: 'FF000000' } },
                    right: { style: 'thin', color: { argb: 'FF000000' } },
                };

                setOuterBorder('B' + row + ':D' + row, packingList);
            }
            setOuterBorder('E' + row + ':P' + row, packingList);

            setOuterBorder('Q' + row + ':U' + row, packingList);
            setOuterBorder('V' + row + ':X' + row, packingList);
            setOuterBorder('Y' + row + ':AA' + row, packingList);

        } else {
            packingList.getCell('A' + row).value = srNo;
            packingList.getCell('A' + row).alignment = { wrapText: true, horizontal: 'center', vertical: 'middle' };
            packingList.getCell('A' + row).font = { bold: true };
            packingList.getCell('A' + row).border = {
                top: { style: 'thin', color: { argb: 'FF000000' } },     // black
                left: { style: 'thin', color: { argb: 'FF000000' } },
                bottom: { style: 'thin', color: { argb: 'FF000000' } },
                right: { style: 'thin', color: { argb: 'FF000000' } },
            };
            srNo++;

            packingList.mergeCells('B' + row + ':D' + row);
            packingList.getCell('B' + row).value = hsnCode;
            packingList.getCell('B' + row).font = { bold: true };
            packingList.getCell('B' + row).alignment = { wrapText: true, horizontal: 'center', vertical: 'middle' };
            setOuterBorder('B' + row + ':D' + row, packingList);

            if (type !== 'tiles') {
                packingList.mergeCells('E' + row + ':J' + row);
                packingList.getCell('E' + row).value = products[i][0];
                packingList.getCell('E' + row).alignment = { wrapText: true, horizontal: 'center', vertical: 'middle' };
                setOuterBorder('E' + row + ':J' + row, packingList);

                packingList.mergeCells('K' + row + ':P' + row);
                packingList.getCell('K' + row).value = products[i][1];
                packingList.getCell('K' + row).alignment = { wrapText: true, horizontal: 'center', vertical: 'middle' };
                setOuterBorder('K' + row + ':P' + row, packingList);
            } else {
                packingList.mergeCells('E' + row + ':P' + row);
                packingList.getCell('E' + row).value = products[i][0];
                packingList.getCell('E' + row).alignment = { wrapText: true, horizontal: 'center', vertical: 'middle' };
                setOuterBorder('E' + row + ':P' + row, packingList);
            }
            if (String(products[i][0]).length > 26) {
                packingList.getRow(row).height = 36;
            }

            packingList.mergeCells('Q' + row + ':U' + row);
            packingList.getCell('Q' + row).value = products[i][2];
            packingList.getCell('Q' + row).font = { bold: true };
            packingList.getCell('Q' + row).alignment = { wrapText: true, horizontal: 'center', vertical: 'middle' };
            setOuterBorder('Q' + row + ':U' + row, packingList);

            packingList.mergeCells('V' + row + ':X' + row);
            packingList.getCell('V' + row).value = products[i][8];
            packingList.getCell('V' + row).numFmt = '0.00'
            // packingList.getCell('V' + row).fill = {
            //     type: 'pattern',
            //     pattern: 'solid',
            //     fgColor: { argb: 'FFFFFF00' },
            // };
            packingList.getCell('V' + row).alignment = { wrapText: true, horizontal: 'center', vertical: 'middle' };
            setOuterBorder('V' + row + ':X' + row, packingList);

            packingList.mergeCells('Y' + row + ':AA' + row);
            packingList.getCell('Y' + row).value = products[i][9];
            packingList.getCell('Y' + row).numFmt = '0.00'
            // packingList.getCell('Y' + row).fill = {
            //     type: 'pattern',
            //     pattern: 'solid',
            //     fgColor: { argb: 'FFFFFF00' },
            // };
            packingList.getCell('Y' + row).alignment = { wrapText: true, horizontal: 'center', vertical: 'middle' };
            setOuterBorder('Y' + row + ':AA' + row, packingList);
        }
    }


    row++;
    packingList.mergeCells('A' + row + ':D' + (row + 4));
    setOuterBorder('A' + row + ':D' + (row + 4), packingList);

    packingList.mergeCells('Q' + row + ':U' + (row + 5));
    setOuterBorder('Q' + row + ':U' + (row + 5), packingList);

    packingList.mergeCells('V' + row + ':X' + (row + 5));
    setOuterBorder('V' + row + ':AA' + (row + 5), packingList);

    packingList.mergeCells('Y' + row + ':AA' + (row + 5));
    setOuterBorder('Y' + row + ':AA' + (row + 5), packingList);

    if (taxStatus == "with") {
        packingList.mergeCells('E' + row + ':P' + row);
        packingList.getCell('E' + row).value = "CERTIFIED THAT GOODS ARE OF INDIAN ORIGIN";
        packingList.getCell('E' + row).font = { name: 'Arial' };
        packingList.getCell('E' + row).alignment = { horizontal: 'center' };
        setOuterBorder('E' + row + ':P' + row, packingList);
        row++;
    }

    packingList.mergeCells('E' + row + ':P' + row);
    packingList.getCell('E' + row).value = "Export Under Duty Drawback Scheme";
    packingList.getCell('E' + row).font = { bold: true };
    packingList.getCell('E' + row).alignment = { horizontal: 'center' };
    setOuterBorder('E' + row + ':P' + row, packingList);
    row++;

    packingList.mergeCells('E' + row + ':P' + (row + 1));
    packingList.getCell('E' + row).value = "I/we shall claim under chapter 3 incentive of FTP as admissible at time policy in force - MEIS, RODTEP ";
    packingList.getCell('E' + row).font = { bold: true };
    packingList.getCell('E' + row).alignment = { wrapText: true, horizontal: 'center' };
    setOuterBorder('E' + row + ':P' + (row + 1), packingList);
    row += 2;

    if (taxStatus == "without") {
        packingList.mergeCells('E' + row + ':P' + (row + 1));
        setOuterBorder('E' + row + ':P' + (row + 1), packingList);
        row += 2;
    } else {
        packingList.mergeCells('E' + row + ':P' + row);
        setOuterBorder('E' + row + ':P' + row, packingList);
        row++;
    }

    packingList.mergeCells('A' + row + ':D' + row);
    packingList.getCell('A' + row).value = "CONTAINER NO.";
    packingList.getCell('A' + row).font = { bold: true };
    packingList.getCell('A' + row).alignment = { horizontal: 'center' };
    setOuterBorder('A' + row + ':D' + row, packingList);

    packingList.mergeCells('E' + row + ':H' + row);
    packingList.getCell('E' + row).value = "LINE SEAL NO.";
    packingList.getCell('E' + row).font = { bold: true };
    packingList.getCell('E' + row).alignment = { horizontal: 'center' };
    setOuterBorder('E' + row + ':H' + row, packingList);

    packingList.mergeCells('I' + row + ':L' + row);
    packingList.getCell('I' + row).value = "RFID SEAL";
    packingList.getCell('I' + row).font = { bold: true };
    packingList.getCell('I' + row).alignment = { horizontal: 'center' };
    setOuterBorder('I' + row + ':L' + row, packingList);

    packingList.mergeCells('M' + row + ':P' + row);
    packingList.getCell('M' + row).value = "Design no";
    packingList.getCell('M' + row).font = { bold: true };
    packingList.getCell('M' + row).alignment = { horizontal: 'center' };
    setOuterBorder('M' + row + ':P' + row, packingList);

    row++;

    for (let i = 0; i < containerDetails.length; i++) {

        packingList.getRow(row).height = 36;  // fix height here

        packingList.mergeCells('A' + row + ':D' + row);
        packingList.getCell('A' + row).value = containerDetails[i][0];
        packingList.getCell('A' + row).font = { size: 11 };
        // packingList.getCell('A' + row).fill = {
        //     type: 'pattern',
        //     pattern: 'solid',
        //     fgColor: { argb: 'FFD9EAF7' },
        // };
        packingList.getCell('A' + row).alignment = { horizontal: 'center', vertical: 'middle' };
        setOuterBorder('A' + row + ':D' + row, packingList);

        packingList.mergeCells('E' + row + ':H' + row);
        packingList.getCell('E' + row).value = containerDetails[i][1];
        packingList.getCell('E' + row).font = { size: 11 };
        // packingList.getCell('E' + row).fill = {
        //     type: 'pattern',
        //     pattern: 'solid',
        //     fgColor: { argb: 'FFFFFF00' },
        // };
        packingList.getCell('E' + row).alignment = { horizontal: 'center', vertical: 'middle' };
        setOuterBorder('E' + row + ':H' + row, packingList);

        packingList.mergeCells('I' + row + ':L' + row);
        packingList.getCell('I' + row).value = containerDetails[i][2];
        packingList.getCell('I' + row).font = { size: 11 };
        // packingList.getCell('I' + row).fill = {
        //     type: 'pattern',
        //     pattern: 'solid',
        //     fgColor: { argb: 'FFFFFF00' },
        // };
        packingList.getCell('I' + row).alignment = { horizontal: 'center', vertical: 'middle' };
        setOuterBorder('I' + row + ':L' + row, packingList);

        packingList.mergeCells('M' + row + ':P' + row);
        packingList.getCell('M' + row).value = containerDetails[i][3];
        packingList.getCell('M' + row).font = { size: 11 };
        packingList.getCell('M' + row).alignment = { wrapText: true, horizontal: 'center', vertical: 'middle' };
        setOuterBorder('M' + row + ':P' + row, packingList);
        if (String(containerDetails[i][3]).length > 17) {
            packingList.getRow(row).height = 36;
        }

        packingList.mergeCells('Q' + row + ':U' + row);
        packingList.getCell('Q' + row).value = containerDetails[i][4];
        packingList.getCell('Q' + row).font = { size: 11 };
        packingList.getCell('Q' + row).alignment = { horizontal: 'center', vertical: 'middle' };
        setOuterBorder('Q' + row + ':U' + row, packingList);

        packingList.mergeCells('V' + row + ':X' + row);
        packingList.getCell('V' + row).value = containerDetails[i][5];
        packingList.getCell('V' + row).numFmt = '0.00'
        packingList.getCell('V' + row).font = { size: 11 };
        packingList.getCell('V' + row).alignment = { horizontal: 'center', vertical: 'middle' };
        setOuterBorder('V' + row + ':X' + row, packingList);

        packingList.mergeCells('Y' + row + ':AA' + row);
        packingList.getCell('Y' + row).value = containerDetails[i][6];
        packingList.getCell('Y' + row).numFmt = '0.00'
        packingList.getCell('Y' + row).font = { size: 11 };
        packingList.getCell('Y' + row).alignment = { horizontal: 'center', vertical: 'middle' };
        setOuterBorder('Y' + row + ':AA' + row, packingList);

        row++;

    }

    packingList.mergeCells('A' + row + ':D' + (row + 1));
    // packingList.getCell('A' + row).value = `Nos. of Kind Packages ${packegingType}`;
    packingList.getCell('A' + row).value = {
        formula: `"Nos. of Kind Packages " & SUM(Q${row - containerDetails.length}:Q${row - 1}) & " ${packegingType}"`,
        result: null
    };
    packingList.getCell('A' + row).font = { bold: true };
    packingList.getCell('A' + row).alignment = { wrapText: true, horizontal: 'center', vertical: 'middle' };
    setOuterBorder('A' + row + ':D' + (row + 1), packingList);
    if (packegingType.length > 10) {
        packingList.getRow(row).height = 32;
        packingList.getRow(row + 1).height = 32;
    }

    if (totalPallet > 0) {
        packingList.mergeCells('E' + row + ':H' + (row + 1));
        packingList.getCell('E' + row).value = "Total     >>>>>>>>>>";
        packingList.getCell('E' + row).font = { bold: true };
        packingList.getCell('E' + row).alignment = { horizontal: 'center', vertical: 'middle' };
        setOuterBorder('E' + row + ':H' + (row + 1), packingList);

        packingList.mergeCells('I' + row + ':P' + (row + 1));
        packingList.getCell('I' + row).value = `TOTAL PALLET - ${totalPallet} NOS`;
        packingList.getCell('I' + row).font = { name: 'Arial', bold: true };
        packingList.getCell('I' + row).alignment = { horizontal: 'center', vertical: 'middle' };
        setOuterBorder('I' + row + ':P' + (row + 1), packingList);
    } else {
        packingList.mergeCells('E' + row + ':P' + (row + 1));
        packingList.getCell('E' + row).value = "Total     >>>>>>>>>>";
        packingList.getCell('E' + row).font = { bold: true };
        packingList.getCell('E' + row).alignment = { horizontal: 'center', vertical: 'middle' };
        setOuterBorder('E' + row + ':P' + (row + 1), packingList);
    }

    packingList.mergeCells('Q' + row + ':U' + (row + 1));
    packingList.getCell('Q' + row).value = { formula: `SUM(Q${row - containerDetails.length}:Q${row - 1})`, result: 0 };
    packingList.getCell('Q' + row).font = { bold: true };
    packingList.getCell('Q' + row).alignment = { horizontal: 'center', vertical: 'middle' };
    setOuterBorder('Q' + row + ':U' + (row + 1), packingList);

    packingList.mergeCells('V' + row + ':X' + (row + 1));
    packingList.getCell('V' + row).value = { formula: `SUM(V${row - containerDetails.length}:V${row - 1})`, result: 0 };
    packingList.getCell('V' + row).numFmt = '0.00'
    packingList.getCell('V' + row).font = { bold: true };
    packingList.getCell('V' + row).alignment = { horizontal: 'center', vertical: 'middle' };
    setOuterBorder('V' + row + ':X' + (row + 1), packingList);

    packingList.mergeCells('Y' + row + ':AA' + (row + 1));
    packingList.getCell('Y' + row).value = { formula: `SUM(Y${row - containerDetails.length}:Y${row - 1})`, result: 0 };
    packingList.getCell('Y' + row).numFmt = '0.00'
    packingList.getCell('Y' + row).font = { bold: true };
    packingList.getCell('Y' + row).alignment = { horizontal: 'center', vertical: 'middle' };
    setOuterBorder('Y' + row + ':AA' + (row + 1), packingList);

    row += 2;

    packingList.mergeCells('A' + row + ':P' + row);
    setOuterBorder('A' + row + ':P' + row, packingList);

    packingList.mergeCells('Q' + row + ':U' + row);
    packingList.getCell('Q' + row).value = packegingType;
    packingList.getCell('Q' + row).font = { bold: true };
    packingList.getCell('Q' + row).alignment = { horizontal: 'center' };
    setOuterBorder('Q' + row + ':U' + row, packingList);

    packingList.mergeCells('V' + row + ':X' + row);
    packingList.getCell('V' + row).value = "KGS";
    packingList.getCell('V' + row).font = { bold: true };
    packingList.getCell('V' + row).alignment = { horizontal: 'center' };
    setOuterBorder('V' + row + ':X' + row, packingList);

    packingList.mergeCells('Y' + row + ':AA' + row);
    packingList.getCell('Y' + row).value = "KGS";
    packingList.getCell('Y' + row).font = { bold: true };
    packingList.getCell('Y' + row).alignment = { horizontal: 'center' };
    setOuterBorder('Y' + row + ':AA' + row, packingList);

    row++;
    packingList.mergeCells('Q' + row + ':AA' + row);
    packingList.getCell('Q' + row).value = "Signature & Date";
    packingList.getCell('Q' + row).font = { bold: true };
    packingList.getCell('Q' + row).alignment = { horizontal: 'right' };

    packingList.mergeCells('Q' + (row + 1) + ':AA' + (row + 1));
    packingList.getCell('Q' + (row + 1)).value = `For, ${companyName}`;
    packingList.getCell('Q' + (row + 1)).font = { bold: true };
    packingList.getCell('Q' + (row + 1)).alignment = { horizontal: 'right' };

    packingList.addImage(signature, {
        tl: { col: 20, row: row }, // X66 (X = col 24 → 24 - 1 = 23 → 22 for 0-based)
        ext: { width: 95, height: 95 }, // adjust size as needed
    });

    packingList.mergeCells('A' + row + ':P' + (row + 4));
    setOuterBorder('A' + row + ':P' + (row + 4), packingList);

    packingList.mergeCells('Q' + (row + 6) + ':AA' + (row + 6));
    packingList.getCell('Q' + (row + 6)).value = "AUTHORISED SIGN.";
    packingList.getCell('Q' + (row + 6)).font = { bold: true };
    packingList.getCell('Q' + (row + 6)).alignment = { horizontal: 'right' };
    setOuterBorder('Q' + row + ':AA' + (row + 6), packingList);

    row += 5;

    packingList.mergeCells('A' + row + ':P' + (row + 1));
    packingList.getCell('A' + row).value = "Declaration:We declare that this invoice shows the actual price of the goods described and that all particulars are true and correct.";
    packingList.getCell('A' + row).font = { bold: true };
    packingList.getCell('A' + row).alignment = { wrapText: true, horizontal: 'left', vertical: 'middle' };
    setOuterBorder('A' + row + ':P' + (row + 1), packingList);
    row++;

    setOuterBorder('A1:AA' + row, packingList, 'medium');

    MAX_WIDTH = 4; // reasonable width ~420px in Excel

    packingList.columns.forEach((column) => {
        let maxLength = 10;

        column.eachCell({ includeEmpty: true }, (cell) => {
            const cellValue = cell.value ? cell.value.toString() : '';
            const lines = cellValue.split('\n');
            const longestLine = Math.max(...lines.map(line => line.length));
            if (longestLine > maxLength) {
                maxLength = longestLine;
            }
        });

        column.width = Math.min(maxLength + 2, MAX_WIDTH); // 👈 LIMIT IT
    });

    setGlobalFontSize(packingList);
    packingList.getColumn(1).width = pixelToExcelWidth(50);
    packingList.getColumn(24).width = pixelToExcelWidth(45);
    packingList.getColumn(25).width = pixelToExcelWidth(45);


















































































    // Create a new workbook

    // The sheet comes off the workbook rather than the local binding: in some
    // sections that binding is declared inside a conditional and is not in
    // scope here. It is the same object either way.
    return {
        workbook: packingListWorkbook,
        sheet: packingListWorkbook.worksheets[0],
        state: { ...state, srNo, row, hsnCode, MAX_WIDTH },
        built: {
            ...built,
            packingListWorkbook: packingListWorkbook,
            packingList: packingListWorkbook.worksheets[0]
        }
    }
}
