/* eslint-disable */
// @ts-nocheck
// GENERATED by scripts/split-generator.mjs from ui/src/lib/excelGenerator.ts.
// The body below is a verbatim copy. Do not edit or reformat it by hand —
// re-run `npm run docs:split` instead. The original was written with
// TypeScript strictness disabled, so it is excluded from type checking;
// correctness is established by scripts/compare-generators.mts, which diffs
// every cell against the original generator.
// Source lines 5493-6077.

import ExcelJS from 'exceljs'
import { format } from 'date-fns'
import { convertNamesToInitials, formatNames, round3 } from '../helpers'
import { loadImageBuffer } from '../loadImageBuffer'
import type { DocumentContext } from '../context'
import type { SheetState } from '../state'

void ExcelJS
void format
void round3
void convertNamesToInitials
void formatNames
void loadImageBuffer

export const buildVgm = async (
  ctx: DocumentContext,
  state: SheetState,
  built: Record<string, any> = {}
): Promise<{ workbook: any; sheet: any; state: SheetState; built: Record<string, any> }> => {
    void built
    const {
        companyName,
        ieCode,
        invoiceDate,
        containerDetails,
        nameOfOfficial,
        numberOfOfficial,
        vgn5,
        containerSize,
        vgn7,
        vgn8,
        vgn9,
        unitOfMeasure,
        vgn12,
        vgn13,
        vgn14,
        type,
        headerUrl,
        footerUrl,
        signatureUrl,
        setGlobalFontSize,
        pixelToExcelWidth,
        setOuterBorder
    } = ctx
    let { row, MAX_WIDTH } = state
    let vgnHeader: any, vgnFooter: any, signature: any, vgnHeaderW: any, vgnHeaderH: any, vgnFooterW: any, vgnFooterH: any, vgnSignatureW: any, vgnSignatureH: any

    const vgnWorkbook = new ExcelJS.Workbook();
    const vgn = vgnWorkbook.addWorksheet('VGM');

    if (signatureUrl) {

        const { buffer, extension, width, height } = await loadImageBuffer(signatureUrl);
        signature = vgnWorkbook.addImage({
            buffer: buffer,
            extension: extension,
        });
        vgnSignatureW = width;
        vgnSignatureH = height;

    }

    // response = await fetch('/vgnHeader.png'); // <-- relative to `public/`
    // arrayBuf = await response.arrayBuffer();

    // Add vgnHeader
    if (headerUrl) {

        const { buffer, extension, width, height } = await loadImageBuffer(headerUrl);
        vgnHeader = vgnWorkbook.addImage({
            buffer: buffer,
            extension: extension,
        });
        vgnHeaderW = width;
        vgnHeaderH = height;
    }

    // response = await fetch('/vgnFooter.png'); // <-- relative to `public/`
    // arrayBuf = await response.arrayBuffer();

    // Add vgnHeader


    if (footerUrl) {

        const { buffer, extension, width, height } = await loadImageBuffer(footerUrl);
        vgnFooter = vgnWorkbook.addImage({
            buffer: buffer,
            extension: extension,
        });
        vgnFooterW = width;
        vgnFooterH = height;
    }

    // const vgnHeaderH = 216; // height in pixels (example)
    const estimatedRowsUsed = Math.ceil(vgnHeaderH / 20); // Convert px to row count
    row = Math.max(7, estimatedRowsUsed + 1); // Ensure at least row 7
    // row = 7;

    vgn.addImage(vgnHeader, {
        tl: { col: 0, row: 0 }, // X66 (X = col 24 → 24 - 1 = 23 → 22 for 0-based)
        ext: { width: vgnHeaderW, height: vgnHeaderH }, // adjust size as needed 116
    });

    vgn.mergeCells('A' + row + ':K' + row);
    vgn.getCell('A' + row).value = "INFORMATION ABOUT VERIFIED GROSS MASS OF CONTAINER";
    vgn.getCell('A' + row).font = { bold: true, underline: true, size: 14 };
    vgn.getCell('A' + row).alignment = { horizontal: 'center' }
    row++;

    vgn.getCell('A' + row).value = "SR. NO.";
    vgn.getCell('A' + row).font = { bold: true };
    vgn.getCell('A' + row).alignment = { horizontal: 'center' }
    vgn.getCell('A' + row).border = {
        top: { style: 'thin', color: { argb: 'FF000000' } },     // black
        left: { style: 'thin', color: { argb: 'FF000000' } },
        bottom: { style: 'thin', color: { argb: 'FF000000' } },
        right: { style: 'thin', color: { argb: 'FF000000' } },
    };

    vgn.mergeCells('B' + row + ':F' + row);
    vgn.getCell('B' + row).value = "Details of information";
    vgn.getCell('B' + row).font = { bold: true };
    vgn.getCell('B' + row).alignment = { horizontal: 'center' }
    setOuterBorder('B' + row + ':F' + row, vgn);

    vgn.mergeCells('G' + row + ':K' + row);
    vgn.getCell('G' + row).value = "Particulars";
    vgn.getCell('G' + row).font = { bold: true };
    vgn.getCell('G' + row).alignment = { horizontal: 'center' }
    setOuterBorder('G' + row + ':K' + row, vgn);
    row++;

    vgn.getCell('A' + row).value = 1;
    vgn.getCell('A' + row).alignment = { horizontal: 'center' }
    vgn.getCell('A' + row).border = {
        top: { style: 'thin', color: { argb: 'FF000000' } },     // black
        left: { style: 'thin', color: { argb: 'FF000000' } },
        bottom: { style: 'thin', color: { argb: 'FF000000' } },
        right: { style: 'thin', color: { argb: 'FF000000' } },
    };

    vgn.mergeCells('B' + row + ':F' + row);
    vgn.getCell('B' + row).value = "Name of the shipper";
    vgn.getCell('B' + row).alignment = { wrapText: true, horizontal: 'left' }
    setOuterBorder('B' + row + ':F' + row, vgn);

    vgn.mergeCells('G' + row + ':K' + row);
    vgn.getCell('G' + row).value = companyName;
    vgn.getCell('G' + row).font = { color: { argb: 'FFFF0000' } }
    vgn.getCell('G' + row).alignment = { horizontal: 'center' }
    setOuterBorder('G' + row + ':K' + row, vgn);
    row++;

    vgn.getCell('A' + row).value = 2;
    vgn.getCell('A' + row).alignment = { wrapText: true, horizontal: 'center' }
    vgn.getCell('A' + row).border = {
        top: { style: 'thin', color: { argb: 'FF000000' } },     // black
        left: { style: 'thin', color: { argb: 'FF000000' } },
        bottom: { style: 'thin', color: { argb: 'FF000000' } },
        right: { style: 'thin', color: { argb: 'FF000000' } },
    };

    vgn.mergeCells('B' + row + ':F' + row);
    vgn.getCell('B' + row).value = "Shipper Registration /License no.( IEC No/CIN No)**";
    vgn.getCell('B' + row).alignment = { wrapText: true, horizontal: 'left' }
    setOuterBorder('B' + row + ':F' + row, vgn);

    vgn.mergeCells('G' + row + ':K' + row);
    vgn.getCell('G' + row).value = `I.E. CODE #: ${ieCode}`;
    vgn.getCell('G' + row).alignment = { wrapText: true, horizontal: 'center' }
    setOuterBorder('G' + row + ':K' + row, vgn);
    row++;

    vgn.getCell('A' + row).value = 3;
    vgn.getCell('A' + row).alignment = { wrapText: true, horizontal: 'center' }
    vgn.getCell('A' + row).border = {
        top: { style: 'thin', color: { argb: 'FF000000' } },     // black
        left: { style: 'thin', color: { argb: 'FF000000' } },
        bottom: { style: 'thin', color: { argb: 'FF000000' } },
        right: { style: 'thin', color: { argb: 'FF000000' } },
    };

    vgn.mergeCells('B' + row + ':F' + row);
    vgn.getCell('B' + row).value = "Name and designation of official of the shipper authorizedto sign document";
    vgn.getCell('B' + row).alignment = { wrapText: true, horizontal: 'left' }
    setOuterBorder('B' + row + ':F' + row, vgn);

    vgn.mergeCells('G' + row + ':K' + row);
    vgn.getCell('G' + row).value = nameOfOfficial;
    vgn.getCell('G' + row).alignment = { wrapText: true, horizontal: 'center' }
    setOuterBorder('G' + row + ':K' + row, vgn);
    row++;

    vgn.getCell('A' + row).value = 4;
    vgn.getCell('A' + row).alignment = { wrapText: true, horizontal: 'center' }
    vgn.getCell('A' + row).border = {
        top: { style: 'thin', color: { argb: 'FF000000' } },     // black
        left: { style: 'thin', color: { argb: 'FF000000' } },
        bottom: { style: 'thin', color: { argb: 'FF000000' } },
        right: { style: 'thin', color: { argb: 'FF000000' } },
    };

    vgn.mergeCells('B' + row + ':F' + row);
    vgn.getCell('B' + row).value = "24 x 7 contact details of authorised official of shipper";
    vgn.getCell('B' + row).alignment = { wrapText: true, horizontal: 'left' }
    setOuterBorder('B' + row + ':F' + row, vgn);

    vgn.mergeCells('G' + row + ':K' + row);
    vgn.getCell('G' + row).value = Number(numberOfOfficial);
    vgn.getCell('G' + row).alignment = { wrapText: true, horizontal: 'center' }
    setOuterBorder('G' + row + ':K' + row, vgn);
    row++;

    vgn.getCell('A' + row).value = 5;
    vgn.getCell('A' + row).alignment = { wrapText: true, horizontal: 'center' }
    vgn.getCell('A' + row).border = {
        top: { style: 'thin', color: { argb: 'FF000000' } },     // black
        left: { style: 'thin', color: { argb: 'FF000000' } },
        bottom: { style: 'thin', color: { argb: 'FF000000' } },
        right: { style: 'thin', color: { argb: 'FF000000' } },
    };

    vgn.mergeCells('B' + row + ':F' + row);
    vgn.getCell('B' + row).value = "Container No.";
    vgn.getCell('B' + row).alignment = { wrapText: true, horizontal: 'left' }
    setOuterBorder('B' + row + ':F' + row, vgn);

    vgn.mergeCells('G' + row + ':K' + row);
    vgn.getCell('G' + row).value = vgn5;
    vgn.getCell('G' + row).alignment = { wrapText: true, horizontal: 'center' }
    setOuterBorder('G' + row + ':K' + row, vgn);
    row++;

    vgn.getCell('A' + row).value = 6;
    vgn.getCell('A' + row).alignment = { wrapText: true, horizontal: 'center' }
    vgn.getCell('A' + row).border = {
        top: { style: 'thin', color: { argb: 'FF000000' } },     // black
        left: { style: 'thin', color: { argb: 'FF000000' } },
        bottom: { style: 'thin', color: { argb: 'FF000000' } },
        right: { style: 'thin', color: { argb: 'FF000000' } },
    };

    vgn.mergeCells('B' + row + ':F' + row);
    vgn.getCell('B' + row).value = "Container Size ( TEU/FEU/other) ";
    vgn.getCell('B' + row).alignment = { wrapText: true, horizontal: 'left' }
    setOuterBorder('B' + row + ':F' + row, vgn);

    vgn.mergeCells('G' + row + ':K' + row);
    vgn.getCell('G' + row).value = `${containerSize}'`;
    vgn.getCell('G' + row).alignment = { wrapText: true, horizontal: 'center' }
    setOuterBorder('G' + row + ':K' + row, vgn);
    row++;

    vgn.mergeCells('A' + row + ':A' + (row + 1));
    vgn.getCell('A' + row).value = 7;
    vgn.getCell('A' + row).alignment = { wrapText: true, horizontal: 'center', vertical: 'top' }
    vgn.getCell('A' + row).border = {
        top: { style: 'thin', color: { argb: 'FF000000' } },     // black
        left: { style: 'thin', color: { argb: 'FF000000' } },
        bottom: { style: 'thin', color: { argb: 'FF000000' } },
        right: { style: 'thin', color: { argb: 'FF000000' } },
    };

    vgn.mergeCells('B' + row + ':F' + (row + 1));
    vgn.getCell('B' + row).value = "Maximum permissible weight of container as per the CSC plate";
    vgn.getCell('B' + row).alignment = { wrapText: true, horizontal: 'left' }
    setOuterBorder('B' + row + ':F' + (row + 1), vgn);

    vgn.mergeCells('G' + row + ':K' + (row + 1));
    vgn.getCell('G' + row).value = vgn7;
    vgn.getCell('G' + row).alignment = { wrapText: true, horizontal: 'center', vertical: 'top' }
    setOuterBorder('G' + row + ':K' + (row + 1), vgn);

    // vgn.getRow(row).height = 34;
    row += 2;

    vgn.getCell('A' + row).value = 8;
    vgn.getCell('A' + row).alignment = { wrapText: true, horizontal: 'center' }
    vgn.getCell('A' + row).border = {
        top: { style: 'thin', color: { argb: 'FF000000' } },     // black
        left: { style: 'thin', color: { argb: 'FF000000' } },
        bottom: { style: 'thin', color: { argb: 'FF000000' } },
        right: { style: 'thin', color: { argb: 'FF000000' } },
    };

    vgn.mergeCells('B' + row + ':F' + row);
    vgn.getCell('B' + row).value = "Weighbridge registration no. & Address of Weighbridge";
    vgn.getCell('B' + row).alignment = { wrapText: true, horizontal: 'left' }
    setOuterBorder('B' + row + ':F' + row, vgn);

    vgn.mergeCells('G' + row + ':K' + row);
    vgn.getCell('G' + row).value = vgn8;
    vgn.getCell('G' + row).alignment = { wrapText: true, horizontal: 'center' }
    setOuterBorder('G' + row + ':K' + row, vgn);
    row++;

    vgn.getCell('A' + row).value = 9;
    vgn.getCell('A' + row).alignment = { wrapText: true, horizontal: 'center' }
    vgn.getCell('A' + row).border = {
        top: { style: 'thin', color: { argb: 'FF000000' } },     // black
        left: { style: 'thin', color: { argb: 'FF000000' } },
        bottom: { style: 'thin', color: { argb: 'FF000000' } },
        right: { style: 'thin', color: { argb: 'FF000000' } },
    };

    vgn.mergeCells('B' + row + ':F' + row);
    vgn.getCell('B' + row).value = "Verified gross mass of container (method-1/method-2)";
    vgn.getCell('B' + row).alignment = { wrapText: true, horizontal: 'left' }
    setOuterBorder('B' + row + ':F' + row, vgn);

    vgn.mergeCells('G' + row + ':K' + row);
    vgn.getCell('G' + row).value = vgn9;
    vgn.getCell('G' + row).alignment = { wrapText: true, horizontal: 'center' }
    setOuterBorder('G' + row + ':K' + row, vgn);
    row++;

    vgn.getCell('A' + row).value = 10;
    vgn.getCell('A' + row).alignment = { wrapText: true, horizontal: 'center' }
    vgn.getCell('A' + row).border = {
        top: { style: 'thin', color: { argb: 'FF000000' } },     // black
        left: { style: 'thin', color: { argb: 'FF000000' } },
        bottom: { style: 'thin', color: { argb: 'FF000000' } },
        right: { style: 'thin', color: { argb: 'FF000000' } },
    };

    vgn.mergeCells('B' + row + ':F' + row);
    vgn.getCell('B' + row).value = "Unit of measure (KG / MT/ LBS)";
    vgn.getCell('B' + row).alignment = { wrapText: true, horizontal: 'left' }
    setOuterBorder('B' + row + ':F' + row, vgn);

    vgn.mergeCells('G' + row + ':K' + row);
    vgn.getCell('G' + row).value = unitOfMeasure;
    vgn.getCell('G' + row).alignment = { wrapText: true, horizontal: 'center' }
    setOuterBorder('G' + row + ':K' + row, vgn);
    row++;

    vgn.getCell('A' + row).value = 11;
    vgn.getCell('A' + row).alignment = { wrapText: true, horizontal: 'center' }
    vgn.getCell('A' + row).border = {
        top: { style: 'thin', color: { argb: 'FF000000' } },     // black
        left: { style: 'thin', color: { argb: 'FF000000' } },
        bottom: { style: 'thin', color: { argb: 'FF000000' } },
        right: { style: 'thin', color: { argb: 'FF000000' } },
    };

    vgn.mergeCells('B' + row + ':F' + row);
    vgn.getCell('B' + row).value = "Date and time of weighing";
    vgn.getCell('B' + row).alignment = { wrapText: true, horizontal: 'left' }
    setOuterBorder('B' + row + ':F' + row, vgn);

    vgn.mergeCells('G' + row + ':K' + row);
    vgn.getCell('G' + row).value = `Dt.${invoiceDate}`;
    vgn.getCell('G' + row).alignment = { wrapText: true, horizontal: 'center' }
    setOuterBorder('G' + row + ':K' + row, vgn);
    row++;

    vgn.getCell('A' + row).value = 12;
    vgn.getCell('A' + row).alignment = { wrapText: true, horizontal: 'center' }
    vgn.getCell('A' + row).border = {
        top: { style: 'thin', color: { argb: 'FF000000' } },     // black
        left: { style: 'thin', color: { argb: 'FF000000' } },
        bottom: { style: 'thin', color: { argb: 'FF000000' } },
        right: { style: 'thin', color: { argb: 'FF000000' } },
    };

    vgn.mergeCells('B' + row + ':F' + row);
    vgn.getCell('B' + row).value = "Weighing slip no.";
    vgn.getCell('B' + row).alignment = { wrapText: true, horizontal: 'left' }
    setOuterBorder('B' + row + ':F' + row, vgn);

    vgn.mergeCells('G' + row + ':K' + row);
    vgn.getCell('G' + row).value = vgn12;
    vgn.getCell('G' + row).alignment = { wrapText: true, horizontal: 'center' }
    setOuterBorder('G' + row + ':K' + row, vgn);
    row++;

    vgn.getCell('A' + row).value = 13;
    vgn.getCell('A' + row).alignment = { wrapText: true, horizontal: 'center' }
    vgn.getCell('A' + row).border = {
        top: { style: 'thin', color: { argb: 'FF000000' } },     // black
        left: { style: 'thin', color: { argb: 'FF000000' } },
        bottom: { style: 'thin', color: { argb: 'FF000000' } },
        right: { style: 'thin', color: { argb: 'FF000000' } },
    };

    vgn.mergeCells('B' + row + ':F' + row);
    vgn.getCell('B' + row).value = "Type (Normal/Reefer/Hazardous/others)";
    vgn.getCell('B' + row).alignment = { wrapText: true, horizontal: 'left' }
    setOuterBorder('B' + row + ':F' + row, vgn);

    vgn.mergeCells('G' + row + ':K' + row);
    vgn.getCell('G' + row).value = vgn13;
    vgn.getCell('G' + row).alignment = { wrapText: true, horizontal: 'center' }
    setOuterBorder('G' + row + ':K' + row, vgn);
    row++;

    vgn.getCell('A' + row).value = 14;
    vgn.getCell('A' + row).alignment = { wrapText: true, horizontal: 'center' }
    vgn.getCell('A' + row).border = {
        top: { style: 'thin', color: { argb: 'FF000000' } },     // black
        left: { style: 'thin', color: { argb: 'FF000000' } },
        bottom: { style: 'thin', color: { argb: 'FF000000' } },
        right: { style: 'thin', color: { argb: 'FF000000' } },
    };

    vgn.mergeCells('B' + row + ':F' + row);
    vgn.getCell('B' + row).value = "If Hazardous  UN NO.IMDG class";
    vgn.getCell('B' + row).alignment = { wrapText: true, horizontal: 'left' }
    setOuterBorder('B' + row + ':F' + row, vgn);

    vgn.mergeCells('G' + row + ':K' + row);
    vgn.getCell('G' + row).value = vgn14;
    vgn.getCell('G' + row).alignment = { wrapText: true, horizontal: 'center' }
    setOuterBorder('G' + row + ':K' + row, vgn);
    row += 2;

    vgn.mergeCells('C' + row + ':F' + row);
    vgn.getCell('C' + row).value = "Signature of authorised person of shipper";
    vgn.getCell('C' + row).alignment = { wrapText: true, horizontal: 'left' }

    vgn.mergeCells('H' + row + ':I' + row);
    vgn.getCell('H' + row).value = `For, ${companyName}`;
    vgn.getCell('H' + row).alignment = { wrapText: true, horizontal: 'left' }

    vgn.addImage(signature, {
        tl: { col: 9, row: (row - 1) }, // X66 (X = col 24 → 24 - 1 = 23 → 22 for 0-based)
        ext: { width: 100, height: 100 }, // adjust size as needed
    });
    row++;

    vgn.getCell('C' + row).value = `NAME:`;
    vgn.getCell('C' + row).alignment = { wrapText: true, horizontal: 'left' }

    vgn.mergeCells('D' + row + ':F' + row);
    vgn.getCell('D' + row).value = nameOfOfficial;
    vgn.getCell('D' + row).alignment = { wrapText: true, horizontal: 'left' }
    row++;

    vgn.getCell('C' + row).value = `DATE:`;
    vgn.getCell('C' + row).alignment = { wrapText: true, horizontal: 'left' }

    vgn.mergeCells('D' + row + ':F' + row);
    vgn.getCell('D' + row).value = invoiceDate;
    vgn.getCell('D' + row).alignment = { wrapText: true, horizontal: 'left' }
    row += 2;

    vgn.mergeCells('H' + row + ':K' + row);
    vgn.getCell('H' + row).value = "AUTHORISED SIGNATURE";
    vgn.getCell('H' + row).alignment = { wrapText: true, horizontal: 'left' }
    row += 2;

    vgn.mergeCells('A' + row + ':C' + (row + 1));
    vgn.getCell('A' + row).value = "BOOKING NO.";
    vgn.getCell('A' + row).font = { bold: true }
    vgn.getCell('A' + row).alignment = { wrapText: true, horizontal: 'center', vertical: 'middle' }
    setOuterBorder('A' + row + ':C' + row, vgn);

    vgn.mergeCells('D' + row + ':F' + (row + 1));
    vgn.getCell('D' + row).value = "CONTAINER NUMBER";
    vgn.getCell('D' + row).font = { bold: true }
    vgn.getCell('D' + row).alignment = { wrapText: true, horizontal: 'center', vertical: 'middle' }
    setOuterBorder('D' + row + ':F' + row, vgn);

    vgn.mergeCells('G' + row + ':K' + (row + 1));
    vgn.getCell('G' + row).value = "VGN (KGS)\n(CARGO + TARE WEIGHT)";
    vgn.getCell('G' + row).font = { bold: true }
    vgn.getCell('G' + row).alignment = { wrapText: true, horizontal: 'center', vertical: 'middle' }
    setOuterBorder('G' + row + ':K' + row, vgn);
    row += 2;

    for (let i = 0; i < containerDetails.length; i++) {
        vgn.mergeCells('A' + row + ':C' + row);
        vgn.getCell('A' + row).value = containerDetails[i][8];
        vgn.getCell('A' + row).alignment = { horizontal: 'center' }
        setOuterBorder('A' + row + ':C' + row, vgn);

        vgn.mergeCells('D' + row + ':F' + row);
        vgn.getCell('D' + row).value = containerDetails[i][0];
        vgn.getCell('D' + row).alignment = { horizontal: 'center' }
        setOuterBorder('D' + row + ':F' + row, vgn);

        vgn.getCell('G' + row).value = containerDetails[i][6];
        vgn.getCell('G' + row).numFmt = '0.00';
        // vgn.getCell('G' + row).fill = {
        //     type: 'pattern',
        //     pattern: 'solid',
        //     fgColor: { argb: 'FFFFFF00' },
        // };
        vgn.getCell('G' + row).alignment = { horizontal: 'center' }

        vgn.getCell('H' + row).value = "+";
        // vgn.getCell('H' + row).fill = {
        //     type: 'pattern',
        //     pattern: 'solid',
        //     fgColor: { argb: 'FFFFFF00' },
        // };
        vgn.getCell('H' + row).alignment = { horizontal: 'center' }

        vgn.getCell('I' + row).value = containerDetails[i][9];
        vgn.getCell('I' + row).numFmt = '0.00';
        // vgn.getCell('I' + row).fill = {
        //     type: 'pattern',
        //     pattern: 'solid',
        //     fgColor: { argb: 'FFFFFF00' },
        // };
        vgn.getCell('I' + row).alignment = { horizontal: 'center' }

        vgn.getCell('J' + row).value = "=";
        // vgn.getCell('J' + row).fill = {
        //     type: 'pattern',
        //     pattern: 'solid',
        //     fgColor: { argb: 'FFFFFF00' },
        // };
        vgn.getCell('J' + row).alignment = { horizontal: 'center' }

        vgn.getCell('K' + row).value = { formula: `G${row}+I${row}`, result: 0 };
        vgn.getCell('K' + row).numFmt = '0.00';
        // vgn.getCell('K' + row).fill = {
        //     type: 'pattern',
        //     pattern: 'solid',
        //     fgColor: { argb: 'FFFFFF00' },
        // };
        vgn.getCell('K' + row).alignment = { horizontal: 'center' }

        setOuterBorder('G' + row + ':K' + row, vgn);

        row++;
    }

    vgn.addImage(vgnFooter, {
        tl: { col: 0, row: (row + 1) }, // X66 (X = col 24 → 24 - 1 = 23 → 22 for 0-based)
        ext: { width: vgnFooterW, height: vgnFooterH }, // adjust size as needed
    });

    vgn.pageSetup.fitToPage = true;

    MAX_WIDTH = 8.4;

    vgn.columns.forEach((column) => {
        let maxLength = 10;

        column.eachCell({ includeEmpty: true }, (cell) => {
            const cellValue = cell.value ? cell.value.toString() : '';
            const lines = cellValue.split('\n');
            const longestLine = Math.max(...lines.map(line => line.length));
            if (longestLine > maxLength) {
                maxLength = longestLine;
            }
        });

        column.width = Math.min(maxLength + 2, MAX_WIDTH); // 👈 LIMIT IT
    });

    vgn.getColumn(6).width = pixelToExcelWidth(80);

    setGlobalFontSize(vgn);












































































    // The sheet comes off the workbook rather than the local binding: in some
    // sections that binding is declared inside a conditional and is not in
    // scope here. It is the same object either way.
    return {
        workbook: vgnWorkbook,
        sheet: vgnWorkbook.worksheets[0],
        state: { ...state, row, MAX_WIDTH },
        built: {
            ...built,
            vgnWorkbook: vgnWorkbook,
            vgn: vgnWorkbook.worksheets[0]
        }
    }
}
